### ISSUE TITLE
Error running "make static-dist" in docker alpine

### ISSUE THREAD

**Issue by johnwu96822** [hashicorp/vault#10069]
Hi, I am trying to build a Vault production binary (v1.5.3) with: `make bootstrp static-dist bin` using a Go 1.4 alpine docker image (`make dev` works fine btw). I had nodejs, npm, and yarn installed. 
1. I wonder if `make bootstrp static-dist bin` is the correct steps to produce a production binary, because I can only find dev-related steps in the Vault documentations.
2. I got the bellow error with `make static-dist`:
```
--> Installing JavaScript assets
yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @storybook/addon-knobs@5.3.19" has unmet peer dependency "react@*".
warning "@storybook/addon-knobs > @storybook/api@5.3.19" has unmet peer dependency "regenerator-runtime@*".
warning "@storybook/addon-knobs > @storybook/components@5.3.19" has unmet peer dependency "react@*".
warning "@storybook/addon-knobs > @storybook/components@5.3.19" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-knobs > @storybook/theming@5.3.19" has unmet peer dependency "react@*".
warning "@storybook/addon-knobs > @storybook/theming@5.3.19" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-knobs > react-select@3.1.0" has unmet peer dependency "react@^16.8.0".
warning "@storybook/addon-knobs > react-select@3.1.0" has unmet peer dependency "react-dom@^16.8.0".
warning "@storybook/addon-knobs > @storybook/api > @reach/router@1.2.1" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-links > @storybook/router@5.3.19" has unmet peer dependency "react@*".
warning "@storybook/addon-links > @storybook/router@5.3.19" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-notes > markdown-to-jsx@6.11.4" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-knobs > @storybook/theming > @emotion/core@10.0.28" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-knobs > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-knobs > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-knobs > react-color > @icons/material@0.2.4" has unmet peer dependency "react@*".
warning "@storybook/addon-knobs > react-select > @emotion/core@10.0.15" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-knobs > react-select > react-input-autosize@2.2.2" has unmet peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning "@storybook/addon-knobs > react-select > react-transition-group@4.4.1" has unmet peer dependency "react@>=16.6.0".
warning "@storybook/addon-knobs > react-select > react-transition-group@4.4.1" has unmet peer dependency "react-dom@>=16.6.0".
warning "@storybook/addon-knobs > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
warning " > @storybook/addon-links@5.3.19" has unmet peer dependency "react@*".
warning " > @storybook/addon-notes@5.3.19" has unmet peer dependency "react@*".
warning " > @storybook/addon-viewport@5.3.19" has unmet peer dependency "react@*".
warning " > @storybook/ember@5.3.19" has unmet peer dependency "babel-plugin-ember-modules-api-polyfill@^2.12.0".
warning " > @storybook/ember@5.3.19" has incorrect peer dependency "ember-source@^3.16.0".
warning "@storybook/ember > @storybook/core@5.3.19" has unmet peer dependency "react@*".
warning "@storybook/ember > @storybook/core@5.3.19" has unmet peer dependency "react-dom@*".
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
[5/5] Building fresh packages...
Done in 1020.65s.

> node-sass@4.12.0 install /go/src/vault/ui/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /go/src/vault/ui/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node

> node-sass@4.12.0 postinstall /go/src/vault/ui/node_modules/node-sass
> node scripts/build.js

Binary found at /go/src/vault/ui/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
Testing binary
Binary is fine
node-sass@4.12.0 /go/src/vault/ui/node_modules/node-sass
--> Building Ember application
yarn run v1.19.1
$ ember build -prod
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
- Building
Environment: production
- Building
[BABEL] Note: The code generator has deoptimised the styling of /go/src/vault/ui/node_modules/swagger-ui-dist/swagger-ui-bundle.js as it exceeds the max of 500KB.
[WARN] (broccoli-uglify-sourcemap) Minifying "assets/vault.js" took: 27024ms (more than 20,000ms)
[WARN] (broccoli-uglify-sourcemap) Minifying "assets/chunk.3.8a54c464b94ded3a466a.js" took: 38742ms (more than 20,000ms)
- cleaning up
- cleaning up
cleaning up...
Build Error (UglifyWriter)

Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`


Stack Trace and Error Report: /tmp/error.dump.5f46d4dfb2112e24cd60e3fdc12f9e62.log
error Command failed with exit code 1.
```
This the error dump:
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`

    at ChildProcess.<anonymous> (/go/src/vault/ui/node_modules/workerpool/lib/WorkerHandler.js:260:13)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  - code: [undefined]
  - codeFrame: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`

  - errorMessage: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`

        at UglifyWriter
-~- created here: -~-
    at UglifyWriter.Plugin (/go/src/vault/ui/node_modules/broccoli-plugin/index.js:7:31)
    at new UglifyWriter (/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:38:10)
    at UglifyWriter (/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:33:12)
    at Class.postprocessTree (/go/src/vault/ui/node_modules/ember-cli-uglify/index.js:54:50)
    at projectOrAddon.addons.reduce (/go/src/vault/ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/go/src/vault/ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/go/src/vault/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:866:12)
    at EmberApp.host.addonPostprocessTree (/go/src/vault/ui/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/go/src/vault/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`

        at UglifyWriter
-~- created here: -~-
    at UglifyWriter.Plugin (/go/src/vault/ui/node_modules/broccoli-plugin/index.js:7:31)
    at new UglifyWriter (/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:38:10)
    at UglifyWriter (/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:33:12)
    at Class.postprocessTree (/go/src/vault/ui/node_modules/ember-cli-uglify/index.js:54:50)
    at projectOrAddon.addons.reduce (/go/src/vault/ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/go/src/vault/ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/go/src/vault/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:866:12)
    at EmberApp.host.addonPostprocessTree (/go/src/vault/ui/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/go/src/vault/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: UglifyWriter
  - originalErrorMessage: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`

  - stack: Error: Workerpool Worker terminated Unexpectedly
    exitCode: `null`
    signalCode: `SIGKILL`
    workerpool.script: `/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnArgs: `/usr/bin/node,/go/src/vault/ui/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/lib/worker.js`
    spawnfile: `/usr/bin/node`
    stdout: `null`
    stderr: `null`

    at ChildProcess.<anonymous> (/go/src/vault/ui/node_modules/workerpool/lib/WorkerHandler.js:260:13)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

**Comment by raskchanky** [comment]
`make bootstrap` downloads tools that are used for development on Vault, so if all you're after is a binary, you can probably skip that. `make static-dist` compiles the UI assets so if you don't need to serve the Vault UI, you can skip that step.  `make bin` I think produces the binary you're after, though if you want it to serve the UI, you'll need `make static-dist` too.

I can't tell definitively what's causing the error you posted, but if I had to guess, it's that minifying the assets took too long and the process was killed by the task runner (which I think is broccoli?). Is there any way to test this theory by increasing the compute resources for the container that's running this build?

**Comment by johnwu96822** [comment]
@raskchanky Thanks for your response. You mentioned that if I don't need the UI, I can run `make bin` directly without `static-dist`. However, every time I did that I got:
```
==> Building...
Number of parallel builds: 5

-->     linux/arm64: github.com/hashicorp/vault

1 errors occurred:
--> linux/arm64 error: exit status 2
Stderr: # github.com/hashicorp/vault/http
http/handler.go:156:148: undefined: assetFS
http/handler.go:157:130: undefined: assetFS

make: *** [Makefile:34: bin] Error 1
```
Which is why I thought assets are required for the `make bin` build. Or could it be something else? Thanks for you help!

**Comment by raskchanky** [comment]
@johnwu96822 You're likely right then, that `make static-dist` is required for `bin`. I figured if it was, the `bin` target would depend on `static-dist` inside the `Makefile` but I guess that's not the case.

Is there any way to increase the compute resources for the container that's running, so it doesn't time out? That's my best guess as to what's causing this error. I can run `make static-dist` on my 2019 MBP and it completes without issue.

**Comment by johnwu96822** [comment]
@raskchanky I increased docker resource from 2GB to 3GB (with 1GB swap) and then it got past `make static-dist`. Thanks for the help!!

**Comment by raskchanky** [comment]
@johnwu96822 You bet! I'm glad you got it sorted out.
