### ISSUE TITLE
Vault 1.7.0 panic on arm platform

### ISSUE THREAD

**Issue by dcarbone** [hashicorp/vault#11197]
**Describe the bug**
Vault 1.7.0 on arm (pi4 4gb) panics during what I presume to be leader election

**To Reproduce**
1. Update vault
2. unseal vault
3. wait.

**Expected behavior**
it doesn't panic.

**Environment:**
Vault v1.7.0
Pi4 4GB latest Raspbian

**Additional context**
```
Mar 24 22:21:12 vault[642]: ==> Vault server started! Log data will stream in below:
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.500-0500 [INFO]  core.cluster-listener.tcp: starting listener: listener_address=127.0.0.1:8201
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.500-0500 [INFO]  core.cluster-listener.tcp: starting listener: listener_address=10.0.30.16:8201
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.500-0500 [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.500-0500 [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=10.0.30.16:8201
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.500-0500 [INFO]  core: vault is unsealed
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.500-0500 [WARN]  service_registration.consul: concurrent initalize state change notify dropped
Mar 24 22:23:45 vault[642]: 2021-03-24T22:23:45.501-0500 [INFO]  core: entering standby mode
Mar 24 22:30:31 vault[642]: 2021-03-24T22:30:31.275-0500 [INFO]  core: acquired lock, enabling active operation
Mar 24 22:30:31 vault[642]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 24 22:30:31 vault[642]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11db8]
Mar 24 22:30:31 vault[642]: goroutine 174 [running]:
Mar 24 22:30:31 vault[642]: runtime/internal/atomic.goStore64(0x744724c, 0x0, 0x0)
Mar 24 22:30:31 vault[642]:         /goroot/src/runtime/internal/atomic/atomic_arm.go:144 +0x1c
Mar 24 22:30:31 vault[642]: github.com/hashicorp/vault/vendor/go.uber.org/atomic.(*Int64).Store(...)
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vendor/go.uber.org/atomic/atomic.go:119
Mar 24 22:30:31 vault[642]: github.com/hashicorp/vault/vault.(*AESGCMBarrier).ReloadKeyring(0x74471f0, 0x475b0f8, 0x77f5580, 0x0, 0x0)
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:348 +0x2c0
Mar 24 22:30:31 vault[642]: github.com/hashicorp/vault/vault.(*Core).performKeyUpgrades(0x73d1c00, 0x475b0f8, 0x77f5580, 0x0, 0x0)
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vault/ha.go:874 +0x90
Mar 24 22:30:31 vault[642]: github.com/hashicorp/vault/vault.(*Core).waitForLeadership(0x73d1c00, 0x0, 0x78b8540, 0x78b8780)
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vault/ha.go:506 +0x588
Mar 24 22:30:31 vault[642]: github.com/hashicorp/vault/vault.(*Core).runStandby.func7(0x78b6030, 0x418be50)
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vault/ha.go:387 +0x34
Mar 24 22:30:31 vault[642]: github.com/hashicorp/vault/vendor/github.com/oklog/run.(*Group).Run.func1(0x731c940, 0x73f0d20, 0x712cf00)
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vendor/github.com/oklog/run/group.go:38 +0x1c
Mar 24 22:30:31 vault[642]: created by github.com/hashicorp/vault/vendor/github.com/oklog/run.(*Group).Run
Mar 24 22:30:31 vault[642]:         /gopath/src/github.com/hashicorp/vault/vendor/github.com/oklog/run/group.go:37 +0x84
Mar 24 22:30:31 systemd[1]: vault.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 24 22:30:31 systemd[1]: vault.service: Failed with result 'exit-code'.
```

times are in CST.

**Comment by HridoyRoy** [comment]
I'm going to close this issue as the fix has been merged. It will be available in the next point release. Thanks!

**Comment by HridoyRoy** [comment]
@mladlow Let's close this when we release 1.7.1

**Comment by tjhorner** [comment]
Does this have the same underlying issue as trying to `vault operator init` on ARM as well? Here's the stack trace:

```
2021-04-19T22:15:36.043-0400 [INFO]  http: panic serving 192.168.1.90:59785: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*conn).serve.func1(0x76b2f00)
	/goroot/src/net/http/server.go:1801 +0xf0
panic(0x38150b8, 0x6d73700)
	/goroot/src/runtime/panic.go:975 +0x47c
runtime/internal/atomic.goXadd64(0x77e9a1c, 0x1, 0x0, 0x1, 0x475b178)
	/goroot/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/hashicorp/vault/vendor/go.uber.org/atomic.(*Int64).Add(...)
	/gopath/src/github.com/hashicorp/vault/vendor/go.uber.org/atomic/atomic.go:94
github.com/hashicorp/vault/vault.(*AESGCMBarrier).encryptTracked(0x77e99d0, 0x3f2b67a, 0xb, 0x1, 0x475b178, 0x7848b40, 0x7762f80, 0x72, 0x80, 0x790a500, ...)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:1126 +0xc8
github.com/hashicorp/vault/vault.(*AESGCMBarrier).persistKeyring(0x77e99d0, 0x475b118, 0x7454068, 0x7742510, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:254 +0x338
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Initialize(0x77e99d0, 0x475b118, 0x7454068, 0x7b015a0, 0x20, 0x20, 0x7b015c0, 0x20, 0x20, 0x47219d0, ...)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:182 +0x1e0
github.com/hashicorp/vault/vault.(*Core).Initialize(0x7a57c00, 0x475b118, 0x7454068, 0x79dda8c, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/init.go:284 +0x58c
github.com/hashicorp/vault/http.handleSysInitPut(0x7a57c00, 0x4758cf8, 0x74c5ae0, 0x752aa80)
	/gopath/src/github.com/hashicorp/vault/http/sys_init.go:67 +0x17c
github.com/hashicorp/vault/http.handleSysInit.func1(0x4758cf8, 0x74c5ae0, 0x752aa80)
	/gopath/src/github.com/hashicorp/vault/http/sys_init.go:18 +0x88
net/http.HandlerFunc.ServeHTTP(0x77c0508, 0x4758cf8, 0x74c5ae0, 0x752aa80)
	/goroot/src/net/http/server.go:2042 +0x34
net/http.(*ServeMux).ServeHTTP(0x7583470, 0x4758cf8, 0x74c5ae0, 0x752aa80)
	/goroot/src/net/http/server.go:2417 +0x16c
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x4758cf8, 0x74c5ae0, 0x752aa80)
	/gopath/src/github.com/hashicorp/vault/http/help.go:24 +0x144
net/http.HandlerFunc.ServeHTTP(0x78c3230, 0x4758cf8, 0x74c5ae0, 0x752aa80)
	/goroot/src/net/http/server.go:2042 +0x34
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x4758cf8, 0x74c5ae0, 0x752aa80)
	/gopath/src/github.com/hashicorp/vault/http/cors.go:29 +0x738
net/http.HandlerFunc.ServeHTTP(0x78c3240, 0x4758cf8, 0x74c5ae0, 0x752aa80)
	/goroot/src/net/http/server.go:2042 +0x34
github.com/hashicorp/vault/http.rateLimitQuotaWrapping.func1(0x4758cf8, 0x74c5ae0, 0x752aa80)
	/gopath/src/github.com/hashicorp/vault/http/util.go:98 +0x7e0
net/http.HandlerFunc.ServeHTTP(0x78c3250, 0x4758cf8, 0x74c5ae0, 0x752aa80)
	/goroot/src/net/http/server.go:2042 +0x34
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x4758cf8, 0x74c5ae0, 0x752a900)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:323 +0x3dc
net/http.HandlerFunc.ServeHTTP(0x77289a0, 0x4758cf8, 0x74c5ae0, 0x752a900)
	/goroot/src/net/http/server.go:2042 +0x34
github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x4758cf8, 0x74c5ae0, 0x752a900)
	/gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/handlers.go:42 +0xa4
net/http.HandlerFunc.ServeHTTP(0x78c3260, 0x4758cf8, 0x74c5ae0, 0x752a900)
	/goroot/src/net/http/server.go:2042 +0x34
net/http.serverHandler.ServeHTTP(0x7958120, 0x4758cf8, 0x74c5ae0, 0x752a900)
	/goroot/src/net/http/server.go:2843 +0x88
net/http.(*conn).serve(0x76b2f00, 0x475b0f8, 0x798b1e0)
	/goroot/src/net/http/server.go:1925 +0x7d0
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2969 +0x2d0
```

**Comment by ncabatoff** [comment]
@tjhorner yup same issue, same fix.

**Comment by dcarbone** [comment]
Just deployed v1.7.1 in my cluster, so far so good.

No panics :)

Thanks for the quick identification and resolution on this!
