### ISSUE TITLE
Vault 1.7.0 i386 dev server panics on start on Win 10 x64

### ISSUE THREAD

**Issue by smeualex** [hashicorp/vault#11264]
**Describe the bug**
Not sure if this is a bug or running the 32 bit executable on Windows 64 bit OS is not supported.

On the starting of the dev server I get a panic message.

Starting command: `vault server -dev`

Output:
```bat
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Go Version: go1.15.10
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.7.0
             Version Sha: 4e222b85c40a810b74400ee3c54449479e32bb9f

2021-04-02T12:13:22.421+0300 [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=192.168.99.100,192.168.99.101
2021-04-02T12:13:22.422+0300 [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2021-04-02T12:13:22.515+0300 [INFO]  core: security barrier not initialized
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xfe204c]

goroutine 1 [running]:
runtime/internal/atomic.Xadd64(0x1c56323c, 0x1, 0x0, 0x1, 0x58aef80)
        /goroot/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/hashicorp/vault/vendor/go.uber.org/atomic.(*Int64).Add(...)
        /gopath/src/github.com/hashicorp/vault/vendor/go.uber.org/atomic/atomic.go:94
github.com/hashicorp/vault/vault.(*AESGCMBarrier).encryptTracked(0x1c5631f0, 0x505c91b, 0xb, 0x1, 0x58aef80, 0x1c0b7b00, 0x1c40e880, 0x72, 0x80, 0x1c2828c0, ...)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:1126 +0xda
github.com/hashicorp/vault/vault.(*AESGCMBarrier).persistKeyring(0x1c5631f0, 0x58aef60, 0x1c4de3e0, 0x1c381530, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:254 +0x38c
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Initialize(0x1c5631f0, 0x58aef60, 0x1c4de3e0, 0x1c36bfc0, 0x20, 0x20, 0x1c01a000, 0x20, 0x20, 0x586df40, ...)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:182 +0x20c
github.com/hashicorp/vault/vault.(*Core).Initialize(0x1c4d4800, 0x58aef60, 0x1c4de3e0, 0x1c915828, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/init.go:284 +0x642
github.com/hashicorp/vault/command.(*ServerCommand).enableDev(0x1c0b0b40, 0x1c4d4800, 0x1c957000, 0x1c0b0b40, 0x2, 0x1c092550)
        /gopath/src/github.com/hashicorp/vault/command/server.go:1995 +0x12c
github.com/hashicorp/vault/command.(*ServerCommand).Run(0x1c0b0b40, 0x1c05d990, 0x1, 0x2, 0x0)
        /gopath/src/github.com/hashicorp/vault/command/server.go:1671 +0x4754
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0x1c628000, 0x1c628000, 0x1c2d8560, 0x1c2d84e0)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:261 +0x1ba
github.com/hashicorp/vault/command.RunCustom(0x1c05d988, 0x2, 0x3, 0x1c3f2630, 0x1c0541b0)
        /gopath/src/github.com/hashicorp/vault/command/main.go:180 +0x6a0
github.com/hashicorp/vault/command.Run(...)
        /gopath/src/github.com/hashicorp/vault/command/main.go:88
main.main()
        /gopath/src/github.com/hashicorp/vault/main.go:10 +0x56
```

Vault version:
```bat
>vault -v
Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)
```

OS: Windows 10 x64

**To Reproduce**
1. Download and unzip vault 32 bit from https://releases.hashicorp.com/vault/1.7.0/vault_1.7.0_windows_386.zip
2. cd into the vault folder
3. Run cmd  `vault server -dev`

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):  command is not succesfull
* Vault CLI Version (retrieve with `vault version`): Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)
* Server Operating System/Architecture: Windows 10 - Version 1909 (OS Build 18363.1316)

**Comment by ncabatoff** [comment]
Hi @smeualex,

Thanks for the bug report.  This is the same underlying issue as https://github.com/hashicorp/vault/issues/11197, so I'm closing this bug report as a duplicate.  There should be a fix out soon.
