### ISSUE TITLE
http: panic serving 127.0.0.1:37560: send on closed channel

### ISSUE THREAD

**Issue by jippi** [hashicorp/vault#1241]
Hi,

I'm currently testing Vault + Consul in a local environment, and I'm seeing this kind of errors happen once in a while

````
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: consul (HA available)
 Advertise Address: http://10.0.2.15:8200
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
           Version: Vault v0.5.1

==> Vault server started! Log data will stream in below:

2016/03/21 10:12:27 [INFO] core: vault is unsealed
2016/03/21 10:12:27 [INFO] core: entering standby mode
2016/03/21 10:13:01 [INFO] core: acquired lock, enabling active operation
2016/03/21 10:13:01 [INFO] core: post-unseal setup starting
2016/03/21 10:13:01 [INFO] core: mounted backend of type generic at secret/
2016/03/21 10:13:01 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/03/21 10:13:01 [INFO] core: mounted backend of type system at sys/
2016/03/21 10:13:01 [INFO] core: mounted backend of type mysql at mysql/
2016/03/21 10:13:01 [INFO] core: mounted backend of type generic at frontend/
2016/03/21 10:13:01 [INFO] rollback: starting rollback manager
2016/03/21 10:13:01 [INFO] expire: restored 14 leases
2016/03/21 10:13:01 [INFO] core: post-unseal setup complete
2016/03/21 10:14:30 http: panic serving 127.0.0.1:37560: send on closed channel
goroutine 619 [running]:
net/http.(*conn).serve.func1(0xc820486d80)
	/goroot/src/net/http/server.go:1389 +0xc1
panic(0xf20220, 0xc820526000)
	/goroot/src/runtime/panic.go:426 +0x4e9
database/sql.(*DB).putConnDBLocked(0xc82034ebb0, 0xc820198230, 0x0, 0x0, 0xc820013090)
	/goroot/src/database/sql/sql.go:939 +0x198
database/sql.(*DB).putConn(0xc82034ebb0, 0xc820198230, 0x0, 0x0)
	/goroot/src/database/sql/sql.go:905 +0x23f
database/sql.(*Tx).close(0xc82012f400, 0x0, 0x0)
	/goroot/src/database/sql/sql.go:1225 +0xad
database/sql.(*Tx).Rollback(0xc82012f400, 0x0, 0x0)
	/goroot/src/database/sql/sql.go:1272 +0x134
github.com/hashicorp/vault/builtin/logical/mysql.(*backend).pathRoleCreateRead(0xc8203cea60, 0xc820486e80, 0xc820479c60, 0x0, 0x7fcb0c1f9028, 0xc82000f6d0)
	/gopath/src/github.com/hashicorp/vault/builtin/logical/mysql/path_role_create.go:94 +0xb91
github.com/hashicorp/vault/builtin/logical/mysql.(*backend).(github.com/hashicorp/vault/builtin/logical/mysql.pathRoleCreateRead)-fm(0xc820486e80, 0xc820479c60, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/logical/mysql/path_role_create.go:23 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc82034e2c0, 0xc820486e80, 0xc820486e80, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:189 +0x833
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc8202b6570, 0xc820486e80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9f
github.com/hashicorp/vault/vault.(*Router).Route(0xc8202b6570, 0xc820486e80, 0xc820486e80, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc8202f6000, 0xc820486e80, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/core.go:534 +0x9c8
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc8202f6000, 0xc820486e80, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/core.go:455 +0x7dc
github.com/hashicorp/vault/http.request(0xc8202f6000, 0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0, 0xc820486e80, 0x0, 0xc820135860)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:84 +0x2f
github.com/hashicorp/vault/http.handleLogical.func1(0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0)
	/gopath/src/github.com/hashicorp/vault/http/logical.go:77 +0x608
net/http.HandlerFunc.ServeHTTP(0xc8202bd2c0, 0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0)
	/goroot/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8202b67e0, 0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0)
	/goroot/src/net/http/server.go:1910 +0x17d
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0)
	/gopath/src/github.com/hashicorp/vault/http/help.go:18 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc8202bd300, 0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0)
	/goroot/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc8202f2100, 0x7fcb0c1be960, 0xc82036d380, 0xc8204748c0)
	/goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820486d80)
	/goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2137 +0x44e
```

```
-> cat /etc/vault/config.hcl
###############################################################
# Backend
###############################################################

backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault/"
  token = "FgfxSd64tl39MyzbOn4wZQ=="
}

###############################################################
# Listener
###############################################################

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
```

```
-> cat /etc/consul-template/config/config.hcl
consul = "127.0.0.1:8500"
token = "FgfxSd64tl39MyzbOn4wZQ=="
wait = "5s"


vault { # token is from ENV
  address = "http://localhost:8200" 
  renew   = false
}
```

From Consul 
```
2016/03/21 10:14:30 [ERR] (view) "secret(mysql/creds/frontend_main)" error reading from vault: Get http://localhost:8200/v1/mysql/creds/frontend_main: EOF
2016/03/21 10:14:30 [ERR] (runner) watcher reported error: error reading from vault: Get http://localhost:8200/v1/mysql/creds/frontend_main: EOF
2016/03/21 10:15:03 [ERR] (view) "secret(mysql/creds/frontend_test)" error reading from vault: Get http://localhost:8200/v1/mysql/creds/frontend_test: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/03/21 10:15:03 [ERR] (runner) watcher reported error: error reading from vault: Get http://localhost:8200/v1/mysql/creds/frontend_test: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Vault is executed under supervisor like so:

```
/usr/local/bin/vault server -config /etc/vault/config.hcl
````

Consul Template is executed under supervisor like so:

```
/usr/local/bin/envconsul -config /etc/envconsul/config.hcl -prefix consul/template -sanitize -upcase /usr/local/bin/consul-template -config /etc/consul-template/config
```

**Comment by jefferai** [comment]
Hi,

This error is coming because your MySQL connections are being closed outside of Vault. This is usually either due to server configuration or due to firewall configuration.

**Comment by jippi** [comment]
@jefferai shouldn't that be handled gracefully by vault with a simple reconnect ?

**Comment by jefferai** [comment]
Yes and no. The problem is that if it were merely an error, we'd catch it and could maybe do something useful with it. However, the code further down in the Go SQL stack panics, and that's a different story.

You said you see this kind of error happen once in a while. Does the next attempt succeed? I would hope that the SQL connection pool would detect that it's a broken connection and then open a new one next time. Or do you have to restart Vault?

**Comment by jippi** [comment]
@jefferai my setup currently running side a vagrant box on my laptop, so there are plenty of suspend/resume doing the day, which may cause things like mysql pausing for a great while when suspended etc. 

So far i've to restart vault to get things running again

**Comment by jippi** [comment]
@jefferai so, i've pushed my code to our staging server, which run mysql with 

```
[mysql]
wait_timeout=31536000
```

but still see the same error as originally reported :( 

mysql uptime show it has not been restarted for 4-5 days, and vault/consul-template did not get deployed until yesterday evening

**Comment by jefferai** [comment]
The last time that a user had this issue, it was because something in the middle -- neither Vault nor MySQL -- was interrupting the connection. In their case, it was a stateful firewall that decided that the connection didn't need to still be up and tore it down.

**Comment by jippi** [comment]
Not the case for me either ,everything is running localhost , talking to each other on loopback / localhost :(

**Comment by jippi** [comment]
things has been running smoothly for a while now, unsure if its bumping versions of our software or just cosmic randomness, but i can't reproduce the issue atm

**Comment by jefferai** [comment]
@jippi I think that this was caused by #1257 , so fixing that issue likely fixed this too!
