### ISSUE TITLE
SIGSEGV on web UI group create

### ISSUE THREAD

**Issue by MaciejKucia** [hashicorp/vault#12439]
**Describe the bug**
Vault restarts.

**To Reproduce**
1. Login with root token in the web UI
2. Add a new group: Access -> Groups -> Create group -> enter any name -> Create

**Expected behavior**
Vault does not restart and seal, group is created.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.0
* Vault CLI Version (retrieve with `vault version`): irrelevant
* Server Operating System/Architecture: Amazon Linux 2 **aarch64**

Vault server configuration file(s):

```hcl
storage "dynamodb" {
  ha_enabled = "true"
  region     = "xxx"
  table      = "vault"
}

listener "tcp" {
  address     = "[::]:8200"

  tls_disable_client_certs = true
  tls_cert_file = "/x.crt"
  tls_key_file  = "/x.pem"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
ui = true
```

**Additional context**

Journal:
```
unexpected fault address 0x3935356261632f
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3935356261632f pc=0x39b500]
goroutine 221424 [running]:
runtime.throw(0x44a0c39, 0x5)
/goroot/src/runtime/panic.go:1117 +0x54 fp=0x4001143b90 sp=0x4001143b60 pc=0x44994
runtime.sigpanic()
/goroot/src/runtime/signal_unix.go:741 +0x230 fp=0x4001143bd0 sp=0x4001143b90 pc=0x5c600
github.com/golang/snappy.encodeBlock(0x4001128014, 0x12ac8, 0x12ac8, 0x40010ca000, 0xe5, 0x10000, 0x406d453e33)
/gopath/pkg/mod/github.com/golang/snappy@v0.0.2/encode_arm64.s:666 +0x360 fp=0x400114bc70 sp=0x4001143be0 pc=0x39b500
github.com/golang/snappy.Encode(0x4001128012, 0x12aca, 0x12aca, 0x0, 0x0, 0x0, 0x4001043da8, 0x1c9b8, 0x40012937a0)
/gopath/pkg/mod/github.com/golang/snappy@v0.0.2/encode.go:39 +0x17c fp=0x400114bcc0 sp=0x400114bc70 pc=0x39a18c
github.com/golang/snappy.(*Writer).write(0x40012937a0, 0x40010ca000, 0x0, 0x10000, 0x40010ca000, 0x4001168000, 0xe5)
/gopath/pkg/mod/github.com/golang/snappy@v0.0.2/encode.go:233 +0x130 fp=0x400114bd60 sp=0x400114bcc0 pc=0x39a6a0
github.com/golang/snappy.(*Writer).Flush(0x40012937a0, 0xe5, 0x1)
/gopath/pkg/mod/github.com/golang/snappy@v0.0.2/encode.go:276 +0x60 fp=0x400114bdb0 sp=0x400114bd60 pc=0x39aa60
github.com/golang/snappy.(*Writer).Close(0x40012937a0, 0x4001168000, 0xe5)
/gopath/pkg/mod/github.com/golang/snappy@v0.0.2/encode.go:283 +0x28 fp=0x400114bde0 sp=0x400114bdb0 pc=0x39aad8
github.com/hashicorp/vault/sdk/helper/compressutil.Compress(0x4001168000, 0xe5, 0xe5, 0x4001043f08, 0x4000e91200, 0x0, 0x4001168000, 0xe5, 0xe5)
/gopath/src/github.com/hashicorp/vault/sdk/helper/compressutil/compress.go:130 +0x178 fp=0x400114be60 sp=0x400114bde0 pc=0x3a1dd8
github.com/hashicorp/vault/helper/storagepacker.(*StoragePacker).putBucket(0x4001305810, 0x4e2f130, 0x4000d4f0e0, 0x4000e91200, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/helper/storagepacker/storagepacker.go:249 +0x220 fp=0x400114bf60 sp=0x400114be60 pc=0x11c4790
github.com/hashicorp/vault/helper/storagepacker.(*StoragePacker).PutItem(0x4001305810, 0x4e2f130, 0x4000d4f0e0, 0x4001363cc0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/helper/storagepacker/storagepacker.go:356 +0x594 fp=0x400114c070 sp=0x400114bf60 pc=0x11c5564
github.com/hashicorp/vault/vault.(*IdentityStore).UpsertGroupInTxn(0x40005b92c0, 0x4e2f130, 0x4000d4f0e0, 0x40013639c0, 0x40007fe1e0, 0x1, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/identity_store_util.go:1443 +0x2a0 fp=0x400114c120 sp=0x400114c070 pc=0x215d980
github.com/hashicorp/vault/vault.(*IdentityStore).sanitizeAndUpsertGroup(0x40005b92c0, 0x4e2f130, 0x4000d4f0e0, 0x40007fe1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/identity_store_util.go:1242 +0x364 fp=0x400114c350 sp=0x400114c120 pc=0x215b9d4
github.com/hashicorp/vault/vault.(*IdentityStore).handleGroupUpdateCommon(0x40005b92c0, 0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x4000f797a0, 0x0, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/identity_store_groups.go:256 +0x6fc fp=0x400114c460 sp=0x400114c350 pc=0x2142cdc
github.com/hashicorp/vault/vault.(*IdentityStore).pathGroupNameUpdate.func1(0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x4000f797a0, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/identity_store_groups.go:170 +0x238 fp=0x400114c500 sp=0x400114c460 pc=0x2223288
github.com/hashicorp/vault/vault.(*IdentityStore).pathGroupRegister.func1(0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x4000f797a0, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/identity_store_groups.go:124 +0xc0 fp=0x400114c580 sp=0x400114c500 pc=0x2222b80
github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0x4001310f70, 0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/sdk/framework/backend.go:274 +0x3ac fp=0x400114c7b0 sp=0x400114c580 pc=0x8b9f3c
github.com/hashicorp/vault/vault.(*Router).routeCommon(0x400014a4b0, 0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0xc041ed4848d86100, 0x0, 0x40014e0000, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/router.go:686 +0x700 fp=0x400114cc40 sp=0x400114c7b0 pc=0x21e46f0
github.com/hashicorp/vault/vault.(*Router).Route(...)
/gopath/src/github.com/hashicorp/vault/vault/router.go:484
github.com/hashicorp/vault/vault.(*Core).doRouting(0x400034a000, 0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x4000b9ea20, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:724 +0x48 fp=0x400114cca0 sp=0x400114cc40 pc=0x21d98a8
github.com/hashicorp/vault/vault.(*Core).handleRequest(0x400034a000, 0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x0, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:897 +0xa5c fp=0x400114d210 sp=0x400114cca0 pc=0x21da37c
github.com/hashicorp/vault/vault.(*Core).handleCancelableRequest(0x400034a000, 0x4e2f130, 0x4000d4f0e0, 0x4000f98840, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:592 +0x1040 fp=0x400114d370 sp=0x400114d210 pc=0x21d8ba0
github.com/hashicorp/vault/vault.(*Core).switchedLockHandleRequest(0x400034a000, 0x4e2f130, 0x4000d4ec90, 0x4000f98840, 0x40014e9401, 0x0, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:425 +0x2f0 fp=0x400114d410 sp=0x400114d370 pc=0x21d7a10
github.com/hashicorp/vault/vault.(*Core).HandleRequest(...)
/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:391
github.com/hashicorp/vault/http.request(0x400034a000, 0x4e171a0, 0x4000115208, 0x4000f2c700, 0x4000f98840, 0x0, 0x0)
/gopath/src/github.com/hashicorp/vault/http/handler.go:832 +0x58 fp=0x400114d540 sp=0x400114d410 pc=0x225b1c8
github.com/hashicorp/vault/http.handleLogicalInternal.func1(0x4e171a0, 0x4000115208, 0x4000f2c700)
/gopath/src/github.com/hashicorp/vault/http/logical.go:310 +0xe4 fp=0x400114d5e0 sp=0x400114d540 pc=0x2266e34
net/http.HandlerFunc.ServeHTTP(0x400011ffc8, 0x4e171a0, 0x4000115208, 0x4000f2c700)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114d610 sp=0x400114d5e0 pc=0x2ae8f0
github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x4e171a0, 0x4000115208, 0x4000f2c700)
/gopath/src/github.com/hashicorp/vault/http/handler.go:766 +0x210 fp=0x400114d6c0 sp=0x400114d610 pc=0x2266510
net/http.HandlerFunc.ServeHTTP(0x4000bd77e0, 0x4e171a0, 0x4000115208, 0x4000f2c700)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114d6f0 sp=0x400114d6c0 pc=0x2ae8f0
net/http.(*ServeMux).ServeHTTP(0x40003410c0, 0x4e171a0, 0x4000115208, 0x4000f2c700)
/goroot/src/net/http/server.go:2448 +0x190 fp=0x400114d750 sp=0x400114d6f0 pc=0x2b0360
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x4e171a0, 0x4000115208, 0x4000f2c700)
/gopath/src/github.com/hashicorp/vault/http/help.go:23 +0x140 fp=0x400114d7a0 sp=0x400114d750 pc=0x2266980
net/http.HandlerFunc.ServeHTTP(0x4000bd7840, 0x4e171a0, 0x4000115208, 0x4000f2c700)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114d7d0 sp=0x400114d7a0 pc=0x2ae8f0
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x4e171a0, 0x4000115208, 0x4000f2c700)
/gopath/src/github.com/hashicorp/vault/http/cors.go:29 +0x7c0 fp=0x400114d8c0 sp=0x400114d7d0 pc=0x2264480
net/http.HandlerFunc.ServeHTTP(0x4000bd7860, 0x4e171a0, 0x4000115208, 0x4000f2c700)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114d8f0 sp=0x400114d8c0 pc=0x2ae8f0
github.com/hashicorp/vault/http.rateLimitQuotaWrapping.func1(0x4e171a0, 0x4000115208, 0x4000f2c700)
/gopath/src/github.com/hashicorp/vault/http/util.go:97 +0x7f0 fp=0x400114db10 sp=0x400114d8f0 pc=0x226a800
net/http.HandlerFunc.ServeHTTP(0x4000bd7880, 0x4e171a0, 0x4000115208, 0x4000f2c700)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114db40 sp=0x400114db10 pc=0x2ae8f0
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x4e171a0, 0x4000115208, 0x4000d2dd00)
/gopath/src/github.com/hashicorp/vault/http/handler.go:353 +0x430 fp=0x400114dc70 sp=0x400114db40 pc=0x2264e80
net/http.HandlerFunc.ServeHTTP(0x4000341200, 0x4e171a0, 0x4000115208, 0x4000d2dd00)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114dca0 sp=0x400114dc70 pc=0x2ae8f0
github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x4e171a0, 0x4000115208, 0x4000d2dd00)
/gopath/pkg/mod/github.com/hashicorp/go-cleanhttp@v0.5.2/handlers.go:42 +0xb0 fp=0x400114dcf0 sp=0x400114dca0 pc=0x318580
net/http.HandlerFunc.ServeHTTP(0x4000bd78a0, 0x4e171a0, 0x4000115208, 0x4000d2dd00)
/goroot/src/net/http/server.go:2069 +0x40 fp=0x400114dd20 sp=0x400114dcf0 pc=0x2ae8f0
net/http.serverHandler.ServeHTTP(0x4000796ee0, 0x4e171a0, 0x4000115208, 0x4000d2dd00)
/goroot/src/net/http/server.go:2887 +0xbc fp=0x400114dd50 sp=0x400114dd20 pc=0x2b183c
net/http.initALPNRequest.ServeHTTP(0x4e2f130, 0x4000ec9560, 0x4000b4f880, 0x4000796ee0, 0x4e171a0, 0x4000115208, 0x4000d2dd00)
/goroot/src/net/http/server.go:3459 +0x60 fp=0x400114ded0 sp=0x400114dd50 pc=0x2b3090
net/http.(*initALPNRequest).ServeHTTP(0x4000e9f780, 0x4e171a0, 0x4000115208, 0x4000d2dd00)
<autogenerated>:1 +0x68 fp=0x400114df20 sp=0x400114ded0 pc=0x2d9128
net/http.Handler.ServeHTTP-fm(0x4e171a0, 0x4000115208, 0x4000d2dd00)
/goroot/src/net/http/server.go:87 +0x50 fp=0x400114df50 sp=0x400114df20 pc=0x2d23c0
Aug 26 07:07:13 domain systemd[1]: vault.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

Systemd unit:
```
cat /etc/systemd/system/vault.service
[Unit]
Description="HashiCorp Vault - A tool for managing secrets"
Documentation=https://www.vaultproject.io/docs/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/vault.d/vault.hcl
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=vault
Group=vault
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
PrivateDevices=yes
SecureBits=keep-caps
AmbientCapabilities=CAP_IPC_LOCK
Capabilities=CAP_IPC_LOCK+ep
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
NoNewPrivileges=yes
ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=5
TimeoutStopSec=30
StartLimitInterval=60
StartLimitIntervalSec=60
StartLimitBurst=3
LimitNOFILE=65536
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
```

**Comment by MaciejKucia** [comment]
This seems to be resolved after the upgrade to 1.8.2
