### ISSUE TITLE
`panic: runtime error: invalid memory address or nil pointer dereference` in Vault 1.9

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault#13326]
**Describe the bug**

Vault is crashing constantly.  This happens on 1.9.0 and 1.8.4.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x27445dc]

goroutine 4237 [running]:
github.com/hashicorp/vault/vault.(*namedKey).rotate(0xc000de4cf0, {0x5e4e9b8, 0xc000dee120}, {0x5f1ade0, 0xc000ff3aa0}, {0x5e502e0, 0xc0014455c0}, 0xffffffffffffffff)
	/home/runner/work/vault/vault/vault/identity_store_oidc.go:1492 +0x29c
github.com/hashicorp/vault/vault.(*IdentityStore).oidcKeyRotation(0xc00111aa00, {0x5e4e9b8, 0xc000dee120}, {0x5e502e0, 0xc0014455c0})
	/home/runner/work/vault/vault/vault/identity_store_oidc.go:1821 +0x6c5
github.com/hashicorp/vault/vault.(*IdentityStore).oidcPeriodicFunc(0xc00111aa00, {0x5e4e9b8, 0xc000dee120})
	/home/runner/work/vault/vault/vault/identity_store_oidc.go:1870 +0x3d9
github.com/hashicorp/vault/vault.NewIdentityStore.func1({0x5e4e9b8, 0xc000dee120}, 0x0)
	/home/runner/work/vault/vault/vault/identity_store.go:110 +0x30
github.com/hashicorp/vault/sdk/framework.(*Backend).handleRollback(0xc000b8f1e0, {0x5e4e9b8, 0xc000dee120}, 0xc00109ba00)
	/home/runner/work/vault/vault/sdk/framework/backend.go:531 +0x5f
github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc000b8f1e0, {0x5e4e9b8, 0xc000dee120}, 0xc0006cd500)
	/home/runner/work/vault/vault/sdk/framework/backend.go:196 +0x111
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc00135b7c0, {0x5e4e9b8, 0xc000dee120}, 0xc0006cd500, 0x0)
	/home/runner/work/vault/vault/vault/router.go:708 +0x15ec
github.com/hashicorp/vault/vault.(*Router).Route(...)
	/home/runner/work/vault/vault/vault/router.go:505
github.com/hashicorp/vault/vault.(*RollbackManager).attemptRollback(0xc000cc5cb0, {0x5e4e9f0, 0xc0013f0990}, {0xc0011ca396, 0x9}, 0xc0013dff40, 0x1)
	/home/runner/work/vault/vault/vault/rollback.go:225 +0x5d0
created by github.com/hashicorp/vault/vault.(*RollbackManager).startOrLookupRollback
	/home/runner/work/vault/vault/vault/rollback.go:161 +0x298
```

**To Reproduce**

Not sure how to reproduce this.

**Expected behavior**

Not to crash

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.0
* Vault CLI Version (retrieve with `vault version`): 1.9.0
* Server Operating System/Architecture: GKE 1.20 installed with Vault Helm Chart running on COS AMD64 images.

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
  address         = "[::]:8200"
  cluster_address = "[::]:8201"

  tls_cert_file    = "/vault/tls/cert"
  tls_key_file     = "/vault/tls/key"
  tls_ciper_suites = ""

  telemetry {
    unauthenticated_metrics_access = true
  }
}

seal "gcpckms" {
  project    = "x"
  region     = "asia-southeast1"
  key_ring   = "vault"
  crypto_key = "unseal"
}

service_registration "kubernetes" {}


storage "raft" {
  path = "/vault/data"


  retry_join {
    leader_api_addr = "https://vault-0.vault-internal.core.svc:8200"
    leader_ca_cert  = "STRIP"
  }

  retry_join {
    leader_api_addr = "https://vault-1.vault-internal.core.svc:8200"
    leader_ca_cert  = "STRIP"
  }

  retry_join {
    leader_api_addr = "https://vault-2.vault-internal.core.svc:8200"
    leader_ca_cert  = "STRIP"
  }

  retry_join {
    leader_api_addr = "https://vault-3.vault-internal.core.svc:8200"
    leader_ca_cert  = "STRIP"
  }

  retry_join {
    leader_api_addr = "https://vault-4.vault-internal.core.svc:8200"
    leader_ca_cert  = "STRIP"
  }
}

telemetry {
  prometheus_retention_time = "1440h"
  disable_hostname          = true
}
```

**Additional context**

**Comment by hsimon-hashicorp** [comment]
I believe this may be fixed by https://github.com/hashicorp/vault/pull/13318.

**Comment by kalafut** [comment]
Duplicate (I believe) of https://github.com/hashicorp/vault/issues/13223, which is fixed in https://github.com/hashicorp/vault/pull/13298 scheduled for 1.9.1.

cc @fairclothjm  for confirmation that they're the same issue.

**Comment by lawliet89** [comment]
Thanks. I have increased the key rotation to 30d for now.

**Comment by fairclothjm** [comment]
Yes, this is a duplicate of #13223. Thanks for reporting!

**Comment by lawliet89** [comment]
OK I will close this since the original issue is fixed. Awaiting the release of 1.9.1.
