### ISSUE TITLE
runtime error in aws-ec2 auth backend

### ISSUE THREAD

**Issue by ewdurbin** [hashicorp/vault#1541]
We have a vault installation that is failing hard on calls to renew a token from the new `auth/aws-ec2` backend. Please let me know if there's any specific information I can provide to assist in resolving.

Vault 0.6.0, running the binary supplied here on github.

```
2016/06/20 13:20:43 http: panic serving 127.0.0.1:59226: runtime error: invalid memory address or nil pointer dereference
goroutine 97 [running]:
net/http.(*conn).serve.func1(0xc820583700)
	/goroot/src/net/http/server.go:1389 +0xc1
panic(0x148b560, 0xc8200100a0)
	/goroot/src/runtime/panic.go:443 +0x4e9
github.com/hashicorp/vault/builtin/credential/aws-ec2.(*backend).pathLoginRenew(0xc820068090, 0xc820448b40, 0x0, 0x81e7575ff7a06f68, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws-ec2/path_login.go:497 +0x435
github.com/hashicorp/vault/builtin/credential/aws-ec2.(*backend).(github.com/hashicorp/vault/builtin/credential/aws-ec2.pathLoginRenew)-fm(0xc820448b40, 0x0, 0x6b07a5, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/aws-ec2/backend.go:72 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).handleAuthRenew(0xc8200c8160, 0xc820448b40, 0x1727a68, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:429 +0x1bf
github.com/hashicorp/vault/logical/framework.(*Backend).handleRevokeRenew(0xc8200c8160, 0xc820448b40, 0x1727a68, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:379 +0xba
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc8200c8160, 0xc820448b40, 0xc820448b40, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:149 +0x10c
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc82015eb40, 0xc820448b40, 0x40f700, 0x0, 0x1640000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9b
github.com/hashicorp/vault/vault.(*Router).Route(0xc82015eb40, 0xc820448b40, 0x1744510, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*ExpirationManager).renewAuthEntry(0xc8204b81c0, 0xc820448630, 0xc820448870, 0x68c61714000, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:626 +0x2b9
github.com/hashicorp/vault/vault.(*ExpirationManager).RenewToken(0xc8204b81c0, 0xc820448630, 0xc8206c7840, 0x12, 0xc820651770, 0x24, 0x68c61714000, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:370 +0x335
github.com/hashicorp/vault/vault.(*TokenStore).handleRenew(0xc820344fc0, 0xc820448630, 0xc8206e2920, 0xc820806fb0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/token_store.go:1379 +0x763
github.com/hashicorp/vault/vault.(*TokenStore).handleRenewSelf(0xc820344fc0, 0xc820448630, 0xc8206e2920, 0x8000101, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/token_store.go:1348 +0xd7
github.com/hashicorp/vault/vault.(*TokenStore).(github.com/hashicorp/vault/vault.handleRenewSelf)-fm(0xc820448630, 0xc8206e2920, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/token_store.go:376 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc8200c8f20, 0xc820448630, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:203 +0x833
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc82015eb40, 0xc820448630, 0x0, 0x0, 0x7000000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9b
github.com/hashicorp/vault/vault.(*Router).Route(0xc82015eb40, 0xc820448630, 0xc820448630, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc820333200, 0xc820448630, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:163 +0x1027
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc820333200, 0xc820448630, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:42 +0x9a6
github.com/hashicorp/vault/http.request(0xc820333200, 0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960, 0xc820448630, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:95 +0x32
github.com/hashicorp/vault/http.handleLogical.func1(0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960)
	/gopath/src/github.com/hashicorp/vault/http/logical.go:103 +0x150
net/http.HandlerFunc.ServeHTTP(0xc8204b0f20, 0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960)
	/goroot/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82015ede0, 0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960)
	/goroot/src/net/http/server.go:1910 +0x17d
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960)
	/gopath/src/github.com/hashicorp/vault/http/help.go:18 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc8204b0f60, 0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960)
	/goroot/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820193200, 0x7fb55d4d9180, 0xc8200dcf70, 0xc82062d960)
	/goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820583700)
	/goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2137 +0x44e```

**Comment by jefferai** [comment]
Hi @ewdurbin 

Did you happen to be using this backend during its development? It's a bit of an odd error in the current code, but I can see a missed upgrade path that might be causing issues.

**Comment by ewdurbin** [comment]
no, even the roles and policies associated with the instance that instigate this problem are new.

retrieving a new token resolved.

**Comment by vishalnayak** [comment]
@ewdurbin 

The panic is in the renewal function of the token. The backend maintains a whitelist of successful logins indexed by instance IDs. This whitelist entry is referred during the renewal to fetch the role details and here is where the panic is, the whitelist entry is nil. So, a nil check will solve this problem.

However, this essentially needs your confirmation that you deleted the whitelist entry, probably while testing, before the renewal of token. If not, this will need further investigation as to why the whitelist entry was found to be nil.

Did you delete the whitelist entry?

**Comment by ewdurbin** [comment]
@vishalnayak yes! that's an important oversight in my bug report :) Thanks!
