### ISSUE TITLE
tls-certificate backend panics if client certificate is not supplied

### ISSUE THREAD

**Issue by mp911de** [hashicorp/vault#1637]
Login using the `cert` auth backend without supplying a certificate causes a http panic.

Invocation:
```
url --cacert work/ca/certs/ca.cert.pem https://localhost:8200/v1/auth/cert/login -XPOST -v                       
*   Trying ::1...
* Connected to localhost (::1) port 8200 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: localhost
* Server certificate: CA Certificate
> POST /v1/auth/cert/login HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/7.43.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Vault log:
```
2016/07/21 13:48:27 http: TLS handshake error from 127.0.0.1:50222: EOF
2016/07/21 13:48:27 http: panic serving 127.0.0.1:50223: runtime error: index out of range
goroutine 42 [running]:
net/http.(*conn).serve.func1(0xc8205a0300)
	/goroot/src/net/http/server.go:1389 +0xc1
panic(0xdeeee0, 0xc8200100b0)
	/goroot/src/runtime/panic.go:426 +0x4e9
github.com/hashicorp/vault/builtin/credential/cert.(*backend).verifyCredentials(0xc8205d1a00, 0xc820096b80, 0x273985, 0xb73f20, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:146 +0x646
github.com/hashicorp/vault/builtin/credential/cert.(*backend).pathLogin(0xc8205d1a00, 0xc820096b80, 0xc820201620, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:37 +0x52
github.com/hashicorp/vault/builtin/credential/cert.(*backend).(github.com/hashicorp/vault/builtin/credential/cert.pathLogin)-fm(0xc820096b80, 0xc820201620, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:28 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc820591ad0, 0xc820096b80, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:189 +0x833
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc8205da660, 0xc820096b80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9f
github.com/hashicorp/vault/vault.(*Router).Route(0xc8205da660, 0xc820096b80, 0xc820096b80, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0xc8201d4000, 0xc820096b80, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/core.go:626 +0x39b
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc8201d4000, 0xc820096b80, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/core.go:459 +0x4d0
github.com/hashicorp/vault/http.request(0xc8201d4000, 0x1d9cae0, 0xc8203f2a90, 0xc820121b20, 0xc820096b80, 0x30, 0xc8205c8330)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:75 +0x2f
github.com/hashicorp/vault/http.handleLogical.func1(0x1d9cae0, 0xc8203f2a90, 0xc820121b20)
	/gopath/src/github.com/hashicorp/vault/http/logical.go:77 +0x608
net/http.HandlerFunc.ServeHTTP(0xc8200300c0, 0x1d9cae0, 0xc8203f2a90, 0xc820121b20)
	/goroot/src/net/http/server.go:1618 +0x3a
```

**Comment by jefferai** [comment]
@mp911de Just an FYI, you didn't specify the version of Vault so while I think I solved your problem, I couldn't line up the stacktrace with current code. If you can specify which version you were using I can verify it.

**Comment by mp911de** [comment]
It's `Version: Vault v0.5.2`. Let me try with a newer version.

**Comment by mp911de** [comment]
With `Vault v0.6.0` the line numbers are slightly different

```
2016/07/21 16:11:31 http: panic serving [::1]:51757: runtime error: index out of range
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc8205be100)
	/goroot/src/net/http/server.go:1389 +0xc1
panic(0x1087b40, 0xc8200100b0)
	/goroot/src/runtime/panic.go:443 +0x4e9
github.com/hashicorp/vault/builtin/credential/cert.(*backend).verifyCredentials(0xc820609a00, 0xc820513050, 0x2a3755, 0xd81220, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:152 +0x666
github.com/hashicorp/vault/builtin/credential/cert.(*backend).pathLogin(0xc820609a00, 0xc820513050, 0xc8204e92d0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:39 +0x52
github.com/hashicorp/vault/builtin/credential/cert.(*backend).(github.com/hashicorp/vault/builtin/credential/cert.pathLogin)-fm(0xc820513050, 0xc8204e92d0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:30 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc8205f8580, 0xc820513050, 0x0, 0x0, 0x0)
```

**Comment by jefferai** [comment]
Got it, thanks.

**Comment by jefferai** [comment]
^ That should do it!

**Comment by mp911de** [comment]
Amazing, thank you, that did the trick

```
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Date: Thu, 21 Jul 2016 14:37:35 GMT
< Content-Length: 51
< 
{"errors":["client certificate must be supplied"]}
```
