### ISSUE TITLE
MSSQL Connection String containing an instance causes a panic when calling rotate-root

### ISSUE THREAD

**Issue by AnthonyHerman** [hashicorp/vault#17090]
**Describe the bug**
I'm not sure exactly what is going on here yet but it seems to be in general an issue with how the `connection_url` is parsed when a backslash is introduced. For reference when connecting to a MSSQL server `instance` the `server=` will contain `servername\instance` as described here-> https://www.connectionstrings.com/sqlconnection/connection-to-a-sql-server-instance/

For instance this does not work when attempting to connect to instance `B` on server `mydb` (single backslash shown here but same thing with escaped backslash - also note it's the same behavior when attempting creation via TF resources):
```bash
$ vault write database/config/mydb \
>     plugin_name=mssql-database-plugin \
> verify_connection=true \
>     connection_url="server=mydb\B;user id={{username}};password={{password}}; max_connection_lifetime:5s max_open_connections:5" \
>     allowed_roles="*" \
> username="vault_admin" \
> password="test1*2345"
Error writing data to database/config/mydb: Error making API request.

URL: PUT https://myvault:8200/v1/database/config/mydb
Code: 400. Errors:

* error creating database object: error verifying connection: Login error: mssql: Login failed for user 'vault_admin'.
```

I've tried moving around the ordering of the variables but always with the same effect.

Defining the password straight in the connection string however does work:
```bash
$ vault write database/config/mydb \
     plugin_name=mssql-database-plugin \
 verify_connection=true \
     connection_url="server=mydb\B;user id={{username}};password=test1*2345; max_connection_lifetime:5s max_open_connections:5" \
     allowed_roles="*" \
 username="vault_admin"
```

And this actually works, I can get creds with configured roles. This is obviously undesirable from an IaC standpoint because I want to be able create this with Terraform and make use of a templated password pulled from a vault Kv2 path instead of having it defined straight in the connection string.

However, if I try to rotate-root:
```bash
$ vault write -f database/rotate-root/mydb
Error writing data to database/rotate-root/mydb: Put "https://myvault:8200/v1/database/rotate-root/mydb": stream error: stream ID 1; INTERNAL_ERROR
```

And the follow trace gets printed in the log:
```bash
2022-09-09T12:38:58.467-0500 [INFO]  http2: panic serving 10.64.61.3:64807: interface conversion: interface {} is nil, not string
goroutine 70875131 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc14aa4f350, 0xc087175f8e, 0xc0caf78780)
        /goroot/src/net/http/h2_bundle.go:5712 +0x16f
panic(0x4f055c0, 0xc12f37e090)
        /goroot/src/runtime/panic.go:969 +0x1b9
github.com/hashicorp/vault/builtin/logical/database.(*databaseBackend).pathRotateRootCredentialsUpdate.func1(0x6357860, 0xc125334c00, 0xc155568280, 0xc0fda00380, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/logical/database/path_rotate_credentials.go:100 +0xedc
github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc000fe4b60, 0x6357860, 0xc125334c00, 0xc155568280, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/sdk/framework/backend.go:272 +0x4cc
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc0008420f0, 0x6357860, 0xc125334c00, 0xc155568280, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:684 +0x959
github.com/hashicorp/vault/vault.(*Router).Route(...)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:484
github.com/hashicorp/vault/vault.(*Core).doRouting(0xc000904800, 0x6357860, 0xc125334c00, 0xc155568280, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:598 +0x5f
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc000904800, 0x6357860, 0xc125334c00, 0xc155568280, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:771 +0x6b2
github.com/hashicorp/vault/vault.(*Core).handleCancelableRequest(0xc000904800, 0x6357860, 0xc125334ba0, 0x920e880, 0xc155568280, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:466 +0x120f
github.com/hashicorp/vault/vault.(*Core).switchedLockHandleRequest(0xc000904800, 0x6357860, 0xc125334600, 0xc155568280, 0xc08219b001, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:426 +0x385
github.com/hashicorp/vault/vault.(*Core).HandleRequest(...)
        /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:391
github.com/hashicorp/vault/http.request(0xc000904800, 0x6328420, 0xc14aa4f350, 0xc062311200, 0xc155568280, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:852 +0x7e
github.com/hashicorp/vault/http.handleLogicalInternal.func1(0x6328420, 0xc14aa4f350, 0xc062311200)
        /gopath/src/github.com/hashicorp/vault/http/logical.go:444 +0x39e
net/http.HandlerFunc.ServeHTTP(0xc0008663e0, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2042 +0x44
github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x6328420, 0xc14aa4f350, 0xc062311200)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:786 +0x2c2
net/http.HandlerFunc.ServeHTTP(0xc000866400, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0005acd40, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2417 +0x1ad
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x6328420, 0xc14aa4f350, 0xc062311200)
        /gopath/src/github.com/hashicorp/vault/http/help.go:24 +0x14a
net/http.HandlerFunc.ServeHTTP(0xc000866620, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2042 +0x44
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x6328420, 0xc14aa4f350, 0xc062311200)
        /gopath/src/github.com/hashicorp/vault/http/cors.go:29 +0x91e
net/http.HandlerFunc.ServeHTTP(0xc000866640, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2042 +0x44
github.com/hashicorp/vault/http.rateLimitQuotaWrapping.func1(0x6328420, 0xc14aa4f350, 0xc062311200)
        /gopath/src/github.com/hashicorp/vault/http/util.go:98 +0xa95
net/http.HandlerFunc.ServeHTTP(0xc000866660, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2042 +0x44
github.com/hashicorp/vault/http.wrapDRSecondaryHandler.func1(0x6328420, 0xc14aa4f350, 0xc062311200)
        /gopath/src/github.com/hashicorp/vault/http/util_ent.go:82 +0x48b
net/http.HandlerFunc.ServeHTTP(0xc000866680, 0x6328420, 0xc14aa4f350, 0xc062311200)
        /goroot/src/net/http/server.go:2042 +0x44
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x6328420, 0xc14aa4f350, 0xc062310f00)
        /gopath/src/github.com/hashicorp/vault/http/handler.go:353 +0x55a
net/http.HandlerFunc.ServeHTTP(0xc0005ace40, 0x6328420, 0xc14aa4f350, 0xc062310f00)
        /goroot/src/net/http/server.go:2042 +0x44
github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x6328420, 0xc14aa4f350, 0xc062310f00)
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/handlers.go:42 +0xba
net/http.HandlerFunc.ServeHTTP(0xc0008666a0, 0x6328420, 0xc14aa4f350, 0xc062310f00)
        /goroot/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc0002be620, 0x6328420, 0xc14aa4f350, 0xc062310f00)
        /goroot/src/net/http/server.go:2843 +0xa3
net/http.initALPNRequest.ServeHTTP(0x6357860, 0xc1069c3d70, 0xc010661c00, 0xc0002be620, 0x6328420, 0xc14aa4f350, 0xc062310f00)
        /goroot/src/net/http/server.go:3415 +0x8d
net/http.(*http2serverConn).runHandler(0xc0caf78780, 0xc14aa4f350, 0xc062310f00, 0xc191bd42c0)
Monitor dropped 3 logs during monitor request
```

**Expected behavior**
I can use the {{username}} and {{password}} along with a backslash which is needed to specify a MSSQL instance. Further, a rotate-root should no longer cause a panic.

**Environment:**
* Vault Server Version (retrieve with `vault status`): I've tried it on 1.7.5+ent as well as 1.11.3+ent with the same behavior.
* Vault CLI Version (retrieve with `vault version`): v1.8.4. Also happens with latest terraform provider.
* Server Operating System/Architecture: Tried in x64 on RH and in a K8s cluster running Ubuntu nodes.

**Comment by aphorise** [comment]
While the exception is a valid point - the actual `connection_url` is likely not valid and might be intending to be something like:

```shell
vault write database/config/mysql plugin_name=mysql-database-plugin verify_connection=true allowed_roles="*" \
    connection_url="{{username}}:{{password}}@tcp(localhost:3306)/" username="vault_admin" password="test1*2345" ;
```

The `max_connection_lifetime:5s max_open_connections:5` portion I'm not sure about at all.

**Comment by aphorise** [comment]
Hey @AnthonyHerman I'm curious - is there any easy way you can share a reproduction of this using a vagrant box or mysql docker setup? - I made a few erogenous attempts with 1.11.3 and in every case I got a response without any exception.

**Comment by aphorise** [comment]
Hey @AnthonyHerman I didnt hear back from you - but in any case I was able to reproduce this using the latest 1.12.3 binaries and the following exact steps:

```bash
# // launch vault in dev mode eg:
vault server -dev -dev-root-token-id=root -log-level='TRACE' ;

# // run MSSQL server using docker
docker run -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest  -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=test1*2345" ;

vault secrets enable database ;

vault write database/config/mydb plugin_name=mssql-database-plugin verify_connection=true allowed_roles="*" \
  connection_url="user id=SA;password=test1*2345;" username="SA" ;

# // try rotating root - when you'll then hit exception in logs
vault write -f database/rotate-root/mydb ;
  # Error writing data to database/rotate-root/mydb: Put "http://127.0.0.1:8200/v1/database/rotate-root/mydb": EOF
```

The issue seems to occur when [the `password` parameter](https://developer.hashicorp.com/vault/api-docs/secret/databases/mssql#password) is omitted - so for example the following does work without issue:

```bash
vault write database/config/mydb plugin_name=mssql-database-plugin verify_connection=true allowed_roles="*" \
  connection_url="user id=SA;password=test1*2345;" username="SA" password="test1*2345" ;
```

While I agree that the exception should not be happening - there are a couple other points worth making with reference to [the go-mssqldb library (README.md)](https://github.com/denisenkom/go-mssqldb#the-connection-string-can-be-specified-in-one-of-three-formats) that's used in Vault.

1. The convention with `sqlserver://username:password@address?database=...&connection+timeout=30, etc.` seems to be the way to go as per what's [already demonstrated in the Vault documentation](https://developer.hashicorp.com/vault/docs/secrets/databases/mssql#setup). I am not sure about other ADO or ODBC type directives which may not work.

2. I dont see `max_connection_lifetime:5s max_open_connections:5` or any of these type options mentioned anywhere in the [go-mssqldb repository](https://github.com/denisenkom/go-mssqldb)

**Comment by heatherezell** [comment]
Closing this issue - for Enterprise, please always use the [support channels as documented here](https://www.ibm.com/mysupport/s/createrecord/NewCase). Thanks!
