### ISSUE TITLE
Vault agent crashes after restart

### ISSUE THREAD

**Issue by h1ght1me** [hashicorp/vault#17166]
**Describe the bug**
Vault agent with templates crashes with panic when restarted:
```
$ vault agent -config=/etc/vault.d/vault-agent.hcl
==> Vault agent started! Log data will stream in below:

==> Vault agent configuration:

           Api Address 1: http://127.0.0.1:8100
           Api Address 2: http://bufconn
                     Cgo: disabled
               Log Level: info
                 Version: Vault v1.11.3, built 2022-08-26T10:27:10Z
             Version Sha: 17250b25303c6418c283c95b1d5a9c9f16174fe8

2022-09-16T06:50:11.373Z [INFO]  template.server: starting template server
2022-09-16T06:50:11.373Z [INFO] (runner) creating new runner (dry: false, once: false)
2022-09-16T06:50:11.374Z [INFO] (runner) creating watcher
2022-09-16T06:50:11.374Z [INFO]  auth.handler: starting auth handler
2022-09-16T06:50:11.374Z [INFO]  auth.handler: authenticating
2022-09-16T06:50:11.375Z [INFO]  sink.server: starting sink server
2022-09-16T06:50:11.403Z [INFO]  auth.handler: authentication successful, sending token to sinks
2022-09-16T06:50:11.403Z [INFO]  auth.handler: starting renewal process
2022-09-16T06:50:11.403Z [INFO]  template.server: template server received new token
2022-09-16T06:50:11.404Z [INFO] (runner) stopping
2022-09-16T06:50:11.404Z [INFO] (runner) creating new runner (dry: false, once: false)
2022-09-16T06:50:11.404Z [INFO] (runner) creating watcher
2022-09-16T06:50:11.404Z [INFO] (runner) starting
2022-09-16T06:50:11.407Z [INFO]  cache: received request: method=PUT path=/v1/pki-int/issue/consul
2022-09-16T06:50:11.407Z [INFO]  cache.apiproxy: forwarding request: method=PUT path=/v1/pki-int/issue/consul
2022-09-16T06:50:11.407Z [INFO]  auth.handler: renewed auth token
2022-09-16T06:50:11.408Z [INFO]  cache: received request: method=PUT path=/v1/pki-int/issue/consul
2022-09-16T06:50:11.408Z [INFO]  cache: received request: method=PUT path=/v1/pki-int/issue/consul
2022-09-16T06:50:11.410Z [INFO]  cache.apiproxy: forwarding request: method=PUT path=/v1/pki-int/issue/consul
2022-09-16T06:50:11.410Z [INFO]  cache.apiproxy: forwarding request: method=PUT path=/v1/pki-int/issue/consul
2022-09-16T06:50:11.508Z [INFO] (runner) rendered "(dynamic)" => "/etc/consul.d/key.pem"
2022-09-16T06:50:11.512Z [INFO] (runner) rendered "(dynamic)" => "/etc/consul.d/cert.pem"
2022-09-16T06:50:11.524Z [INFO] (runner) rendered "(dynamic)" => "/etc/consul.d/ca.pem"
^C==> Vault agent shutdown triggered
2022-09-16T06:50:18.413Z [INFO]  sink.server: sink server stopped
2022-09-16T06:50:18.413Z [INFO]  sinks finished, exiting
2022-09-16T06:50:18.413Z [INFO] (runner) stopping
2022-09-16T06:50:18.413Z [INFO]  template.server: template server stopped
2022-09-16T06:50:18.413Z [INFO]  auth.handler: shutdown triggered, stopping lifetime watcher
2022-09-16T06:50:18.413Z [INFO]  auth.handler: auth handler stopped
$ vault agent -config=/etc/vault.d/vault-agent.hcl
==> Vault agent started! Log data will stream in below:

==> Vault agent configuration:

           Api Address 1: http://127.0.0.1:8100
           Api Address 2: http://bufconn
                     Cgo: disabled
               Log Level: info
                 Version: Vault v1.11.3, built 2022-08-26T10:27:10Z
             Version Sha: 17250b25303c6418c283c95b1d5a9c9f16174fe8

2022-09-16T06:50:26.826Z [INFO]  template.server: starting template server
2022-09-16T06:50:26.826Z [INFO] (runner) creating new runner (dry: false, once: false)
2022-09-16T06:50:26.826Z [INFO] (runner) creating watcher
2022-09-16T06:50:26.826Z [INFO]  auth.handler: starting auth handler
2022-09-16T06:50:26.827Z [INFO]  auth.handler: authenticating
2022-09-16T06:50:26.827Z [INFO]  sink.server: starting sink server
2022-09-16T06:50:26.851Z [INFO]  auth.handler: authentication successful, sending token to sinks
2022-09-16T06:50:26.852Z [INFO]  auth.handler: starting renewal process
2022-09-16T06:50:26.852Z [INFO]  template.server: template server received new token
2022-09-16T06:50:26.852Z [INFO] (runner) stopping
2022-09-16T06:50:26.852Z [INFO] (runner) creating new runner (dry: false, once: false)
2022-09-16T06:50:26.853Z [INFO] (runner) creating watcher
2022-09-16T06:50:26.853Z [INFO] (runner) starting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2b0 pc=0x2c6bd26]

goroutine 41 [running]:
github.com/hashicorp/consul-template/dependency.goodFor(0xc0008f8e00)
	/home/runner/go/pkg/mod/github.com/hashicorp/consul-template@v0.29.2/dependency/vault_pki.go:114 +0x26
github.com/hashicorp/consul-template/dependency.(*VaultPKIQuery).Fetch.func1(0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/consul-template@v0.29.2/dependency/vault_pki.go:89 +0x125
github.com/hashicorp/consul-template/dependency.(*VaultPKIQuery).Fetch(0xc0005f66c0, 0xc000920090, 0xc000087790)
	/home/runner/go/pkg/mod/github.com/hashicorp/consul-template@v0.29.2/dependency/vault_pki.go:96 +0x115
github.com/hashicorp/consul-template/watch.(*View).fetch(0xc000c77b80, 0xc000071260, 0x6492378, 0xc000c46ac0)
	/home/runner/go/pkg/mod/github.com/hashicorp/consul-template@v0.29.2/watch/view.go:203 +0x131
created by github.com/hashicorp/consul-template/watch.(*View).poll
	/home/runner/go/pkg/mod/github.com/hashicorp/consul-template@v0.29.2/watch/view.go:117 +0x145
```
Problem solves when rendered files are deleted manually. 

**To Reproduce**

1. vault agent -config=/etc/vault.d/vault-agent.hcl    // first run, templates rendered as expected
2. stop agent
3. vault agent -config=/etc/vault.d/vault-agent.hcl    // crashes
4. rm /etc/consul.d/ca.pem /etc/consul.d/cert.pem /etc/consul.d/key.pem
5. vault agent -config=/etc/vault.d/vault-agent.hcl    // works

**Expected behavior**
I expected Vault starts and continues working. 

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.11.3
Build Date      2022-08-26T10:27:10Z
Storage Type    file
Cluster Name    vault-cluster-fdcd6905
Cluster ID      1397ac07-92ed-6107-a015-03b644b141a9
HA Enabled      false
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8), built 2022-08-26T10:27:10Z
```
* Server Operating System/Architecture:
Ubuntu 22.04 x86_64

Vault server configuration file(s):
```
$ cat /etc/vault.d/vault-agent.hcl

vault {
  address = "https://vault.*****.com:8200"
  retry {
    num_retries = 5
  }
}

auto_auth {
  method {
    type = "approle"

    config = {
      role_id_file_path                   = "roleid"
      secret_id_file_path                 = "secretid"
      remove_secret_id_file_after_reading = false
    }
  }
}

cache {
  use_auto_auth_token = true
}


listener "tcp" {
  address     = "127.0.0.1:8100"
  tls_disable = true
}

template {
  contents    = <<EOT
{{ with pkiCert "pki-int/issue/consul" "common_name=consul.*****.com" }}
{{ .Data.Key }}
{{ end }}
EOT
  destination = "/etc/consul.d/key.pem"
}

template {
  contents    = <<EOT
{{ with pkiCert "pki-int/issue/consul" "common_name=consul.*****.com" }}
{{ .Data.Cert }}
{{ end }}
EOT
  destination = "/etc/consul.d/cert.pem"
}

template {
  contents    = <<EOT
{{ with pkiCert "pki-int/issue/consul" "common_name=consul.*****.com" }}
{{ .Data.CA }}
{{ end }}
EOT
  destination = "/etc/consul.d/ca.pem"
}
```

**Comment by h1ght1me** [comment]
UPD reproduced on macOS Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8), built 2022-08-26T10:27:10Z

**Comment by mpalmi** [comment]
This has been addressed in: https://github.com/hashicorp/consul-template/pull/1639. Thanks for the report!

**Comment by mpalmi** [comment]
My apologies, I got a bit hasty. Opening this back up until the aforementioned fix is tagged and brought into Vault.

**Comment by Planokur** [comment]
I have the same issue. To mention that in debug log we can see that there were 
```
(runner) watching 3 dependencies
```
That means there are 3 different POST to the vault that result in 3 different cert/key. 
To be sure, inspect the CRT and key file, and you'll see that they didn't match. They result from 2 different issuing call from vault. 
Everything works well, just if you have been rendering all data in one template like in example below
```
{{ with secret "pki/issue/test" "common_name=test.test" "ttl=1m" }}
{{ .Data.Cert }}
{{ .Data.Key }}
{{ end }}
```
In this case, we'll have just one.
```
 watching 1 dependencie
```
