### ISSUE TITLE
secret/ssh: panic on unmount

### ISSUE THREAD

**Issue by BSick7** [hashicorp/vault#1779]
When trying to unmount ssh backend, I get `Unmount error: EOF`.
Looking in the logs yields a server panic.

## Info
- Client: 0.6.1
- Server: 0.6.1

## Crash Log
```
vault[1111]: http: panic serving 172.31.255.4:52055: interface conversion: interface is json.Number, not float64
goroutine 2042370 [running]:
net/http.(*conn).serve.func1(0xc421414380)
	   /goroot/src/net/http/server.go:1491 +0x12a
panic(0x129d340, 0xc421222600)
	   /goroot/src/runtime/panic.go:458 +0x243
github.com/hashicorp/vault/builtin/logical/ssh.(*backend).secretDynamicKeyRevoke(0xc4203a0d50, 0xc420f60280, 0xc420f4f210, 0x12f2a80, 0x68f901, 0xc420f4f210)
	   /gopath/src/github.com/hashicorp/vault/builtin/logical/ssh/secret_dynamic_key.go:95 +0x50b
github.com/hashicorp/vault/builtin/logical/ssh.(*backend).(github.com/hashicorp/vault/builtin/logical/ssh.secretDynamicKeyRevoke)-fm(0xc420f60280, 0xc420f4f210, 0x0, 0x2, 0xc420512690)
	   /gopath/src/github.com/hashicorp/vault/builtin/logical/ssh/secret_dynamic_key.go:27 +0x3e
github.com/hashicorp/vault/logical/framework.(*Secret).HandleRevoke(0xc420512690, 0xc420f60280, 0x1460c4e, 0x6, 0xc420ef1701)
	   /gopath/src/github.com/hashicorp/vault/logical/framework/secret.go:86 +0x8b
github.com/hashicorp/vault/logical/framework.(*Backend).handleRevokeRenew(0xc4203c0300, 0xc420f60280, 0x1460c4e, 0x6, 0x1)
	   /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:407 +0x23d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc4203c0300, 0xc420f60280, 0xc420f60280, 0xc420f4ee90, 0xe)
	   /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:152 +0x7dd
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc4201a8540, 0xc420f60280, 0x40ef00, 0x0, 0x1410000, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/router.go:269 +0x748
github.com/hashicorp/vault/vault.(*Router).Route(0xc4201a8540, 0xc420f60280, 0x10c0, 0x1280e40, 0xc4218be750)
	   /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3a
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeEntry(0xc4204feec0, 0xc4218be750, 0x33, 0xc4218be750)
	   /gopath/src/github.com/hashicorp/vault/vault/expiration.go:598 +0x22c
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeCommon(0xc4204feec0, 0xc421222540, 0x33, 0xc420c20000, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/expiration.go:201 +0x351
github.com/hashicorp/vault/vault.(*ExpirationManager).revokePrefixCommon(0xc4204feec0, 0xc420c2b366, 0x4, 0x0, 0x2, 0xecf4f77bb)
	   /gopath/src/github.com/hashicorp/vault/vault/expiration.go:297 +0x1f5
github.com/hashicorp/vault/vault.(*ExpirationManager).RevokePrefix(0xc4204feec0, 0xc420c2b366, 0x4, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/expiration.go:246 +0x10d
github.com/hashicorp/vault/vault.(*Core).unmount(0xc4200ee380, 0xc420c2b366, 0x4, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/mount.go:265 +0x3a5
github.com/hashicorp/vault/vault.(*SystemBackend).handleUnmount(0xc420474d00, 0xc420f600a0, 0xc420f4ec20, 0x2000107, 0x0, 0xffffffffffffffff)
	   /gopath/src/github.com/hashicorp/vault/vault/logical_system.go:809 +0x13d
github.com/hashicorp/vault/vault.(*SystemBackend).(github.com/hashicorp/vault/vault.handleUnmount)-fm(0xc420f600a0, 0xc420f4ec20, 0x0, 0x6, 0xc420527000)
	   /gopath/src/github.com/hashicorp/vault/vault/logical_system.go:227 +0x3e
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc4203ba240, 0xc420f600a0, 0xc420f600a0, 0xc420c2b35b, 0xf)
	   /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:206 +0x42e
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc4201a8540, 0xc420f600a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/router.go:269 +0x748
github.com/hashicorp/vault/vault.(*Router).Route(0xc4201a8540, 0xc420f600a0, 0xc420f600a0, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3a
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc4200ee380, 0xc420f600a0, 0x0, 0x0, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:160 +0xb90
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc4200ee380, 0xc420f600a0, 0x0, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/vault/request_handling.go:42 +0x687
github.com/hashicorp/vault/http.request(0xc4200ee380, 0x1ced5c0, 0xc420e5bad0, 0xc4214264b0, 0xc420f600a0, 0x0, 0x0)
	   /gopath/src/github.com/hashicorp/vault/http/handler.go:161 +0x39
github.com/hashicorp/vault/http.handleLogical.func1(0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /gopath/src/github.com/hashicorp/vault/http/logical.go:110 +0x10e
net/http.HandlerFunc.ServeHTTP(0xc420492780, 0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /goroot/src/net/http/server.go:1726 +0x44
github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /gopath/src/github.com/hashicorp/vault/http/handler.go:128 +0x696
net/http.HandlerFunc.ServeHTTP(0xc4204927c0, 0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /goroot/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201a8960, 0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /goroot/src/net/http/server.go:2022 +0x7f
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /gopath/src/github.com/hashicorp/vault/http/help.go:18 +0xd8
net/http.HandlerFunc.ServeHTTP(0xc420492860, 0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /goroot/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42049a300, 0x1ced5c0, 0xc420e5bad0, 0xc4214264b0)
	   /goroot/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421414380, 0x1cee6c0, 0xc420e8d480)
	   /goroot/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	   /goroot/src/net/http/server.go:2293 +0x44d
```

**Comment by jefferai** [comment]
Shucks. We'll fix that for 0.6.2.

**Comment by BSick7** [comment]
I can't even do `vault revoke -force=true`.
This panic is causing problems across the vault cluster.
Any way to get around?

**Comment by jefferai** [comment]
Hi @BSick7 ,

Any chance you can give #1781 a test?

**Comment by BSick7** [comment]
Will do.

**Comment by jefferai** [comment]
Thanks! 

I do appreciate the effort you put into #1780 but I wanted to take the opportunity to both clean up the code and make it more type-safe.

**Comment by BSick7** [comment]
@jefferai Getting this when trying to cut a dev build.
Any ideas?
```
# github.com/circonus-labs/circonus-gometrics
..\..\circonus-labs\circonus-gometrics\submit.go:91: client.RequestLogHook undefined (type *retryablehttp.Client has no field or method RequestLogHook)
```

**Comment by jefferai** [comment]
@BSick7 Issue sorted (comment is deleted at least)

**Comment by BSick7** [comment]
I'm having trouble building on windows.  I dug through the scripts and found the line that got me what I wanted (dev build for linux amd64).

**Comment by jefferai** [comment]
Huh. Strange. We cross-built for Windows and haven't updated deps since. Maybe something different about a dev build.

**Comment by BSick7** [comment]
Here is the error I get.
```
# github.com/hashicorp/vault/vendor/github.com/coreos/go-systemd/journal
vendor\github.com\coreos\go-systemd\journal\journal.go:99: undefined: syscall.UnixRights
```

**Comment by BSick7** [comment]
Just tested the unmount of ssh. It works...sorta.
For the purposes of this PR, it works great.

Since we have immutable infra, we have errors like this that force us to do a `vault revoke -force`.
```
Aug 24 18:55:19 manager-1 vault[10352]: 2016/08/24 18:55:19.610413 [ERR] reconnection error error=dial tcp 172.24.3.74:22: i/o timeout
```

**Comment by jefferai** [comment]
That dep is strange. I honestly have no idea why it's there. I can't find any reference to it currently.

Glad that the panic is fixed for you, though!

BTW -- if you use the OTP mode with the SSH backend, which we generally recommend, you won't have that problem since revocation happens only server-side. Obviously it requires more setup due to the PAM bits.

**Comment by BSick7** [comment]
Since we are running coreos, we have trouble getting PAM modules loaded.
It *may* be possible, but we deprioritized.
