### ISSUE TITLE
correct handling of the zero int64 value

### ISSUE THREAD

**Issue by valli0x** [hashicorp/vault#18730]
If I use a TypeInt64 parameter, I get an error: 
2023-01-16T23:37:48.218+0300 [INFO]  http: panic serving 127.0.0.1:59088: unknown type: unknown type
goroutine 467 [running]:
net/http.(*conn).serve.func1()
	/opt/go/src/net/http/server.go:1802 +0xb9
panic({0x422d0c0, 0xc0014884b0})
	/opt/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/vault/sdk/framework.FieldType.Zero(0xc0001a3380)
	/home/user/go/src/vault-v2/sdk/framework/backend.go:742 +0x254
github.com/hashicorp/vault/sdk/framework.(*FieldSchema).DefaultOrZero(0xc001488250)
	/home/user/go/src/vault-v2/sdk/framework/backend.go:710 +0xe5
github.com/hashicorp/vault/sdk/framework.(*FieldData).Get(0xc001488250, {0x4f95942, 0x6})
	/home/user/go/src/vault-v2/sdk/framework/field_data.go:70 +0x78

You have not added the processing of the zero parameter int64 to the Zero() method:
https://github.com/hashicorp/vault/blob/6365dd6851de72a2f74f9fc4f50dd444d58f3431/sdk/framework/backend.go#L742

#18729

**Comment by ccapurso** [comment]
@valli0x, thank you for addressing this in https://github.com/hashicorp/vault/pull/18729! It looks like there is feedback to provide a test to further guard against potential issues in the future. It seems like it will be ready to merge once that is addressed.
