### ISSUE TITLE
when enabling mlock for custom plugin: fatal error: newosproc

### ISSUE THREAD

**Issue by taitelman** [hashicorp/vault#19471]
**Describe the bug**
if I set ```VAULT_DISABLE_MLOCK=true``` all works well.
however, if I reverse that flag my plugin will crash  with
```
starting plugin
   runtime: failed to create new OS thread (have 18 already; errno=12)
   fatal error: newosproc
  
   runtime stack:
   runtime.throw({0x1ceb377, 0xc000a8be30})   	/usr/local/go/src/runtime/panic.go:1198 +0x71
   runtime.newosproc(0xc000100800)   	/usr/local/go/src/runtime/os_linux.go:160 +0x189
   runtime.newm1(0xc000100800)   	/usr/local/go/src/runtime/proc.go:2251 +0xd3
   runtime.newm(0x0, 0xc000092800, 0x0)   	/usr/local/go/src/runtime/proc.go:2230 +0xe7
   runtime.startm(0x0, 0x1)   	/usr/local/go/src/runtime/proc.go:2485 +0xcf
   runtime.wakep()   	/usr/local/go/src/runtime/proc.go:2584 +0x5a
   runtime.resetspinning()   	/usr/local/go/src/runtime/proc.go:3216 +0x45
   runtime.schedule()   	/usr/local/go/src/runtime/proc.go:3374 +0x25e
   runtime.mstart1()   	/usr/local/go/src/runtime/proc.go:1414 +0xcd
   runtime.mstart0()   	/usr/local/go/src/runtime/proc.go:1365 +0x79
   runtime.mstart()   	/usr/local/go/src/runtime/asm_amd64.s:248 +0x5
  
   goroutine 1 [select]:
   github.com/hashicorp/go-plugin.Serve(0xc00051fc50)   	/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/server.go:469 +0x14b3
   github.com/hashicorp/vault/sdk/plugin.Serve(0xc00051fdb0)   	/go/pkg/mod/github.com/hashicorp/vault/sdk@v0.6.0/plugin/serve.go:86 +0x44e
   main.main()   	/workspace/app/myplugin/cmd/plugin/main.go:47 +0x36f
  
```

is that related to ulimit ?

**Comment by taitelman** [comment]
the only solution I found so far is a complete bypass:
```
 securityContext:
    privileged: true     <--- workaround
    capabilities:
        add:
        - IPC_LOCK
```
which is of course not secured at all

**Comment by taitelman** [comment]
I suspect the other issue with vault + mlock + external plugins is the 
```
rpc error: code = Unavailable desc = error reading from server: read unix @->/tmp/plugin4213242693: use of closed network connection
```
vault copies the plugin to a tmp folder and uses unix pipes to access them. that may require more capabilities

**Comment by taitelman** [comment]
not really relevant or interesting but the `config.hcl` is this:
```
listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

storage "inmem" {}

plugin_directory = "/vault/plugins"
api_addr = "http://127.0.0.1:8200"

log_level = "Debug"
log_format = "json"
```

**Comment by heatherezell** [comment]
Thanks for the report! This issue was filed against Vault `v1.9.6`, which is no longer a supported release.

We're unable to investigate bugs against unsupported versions. If you're still experiencing this on a current supported release of Vault, please open a new issue with updated environment details and we'll take a look.

For a list of currently supported versions, see the [Vault version support page](https://github.com/hashicorp/vault/blob/main/.release/versions.hcl). For Enterprise long-term support information, see the [LTS tracker](https://developer.hashicorp.com/vault/docs/updates/lts-tracker).
