### ISSUE TITLE
Cant unseal vault: Panic: fatal error: fault

### ISSUE THREAD

**Issue by anandkumarpatel** [hashicorp/vault#2027]
# Running vault locally connecting to S3 bucket. I get panic when trying to unseal after last key is inputted

config file:

```
disable_mlock = true

backend "s3" {
  bucket = "runnable.vault"
  access_key = "<redacted>"
  secret_key = "<redacted>"
  region = "us-west-2"
}

listener "tcp" {
  address = "127.0.0.1:31836"
  tls_disable = 1
}
```

system info:

```
$ vault version
Vault v0.5.0

$ $ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323
```

panic log:

```
$ vault server -log-level=trace --config=/tmp/vault.hcl

==> WARNING: mlock not supported on this system!

  The `mlock` syscall to prevent memory from being swapped to
  disk is not supported on this system. Enabling mlock or
  running Vault on a system with mlock is much more secure.

==> Vault server configuration:

         Log Level: trace
             Mlock: supported: false, enabled: false
           Backend: s3
        Listener 1: tcp (addr: "127.0.0.1:31836", tls: "disabled")
           Version: Vault v0.5.0

==> Vault server started! Log data will stream in below:

2016/10/25 13:57:32 [DEBUG] core: cannot unseal, have 1 of 3 keys
2016/10/25 13:57:37 [DEBUG] core: cannot unseal, have 2 of 3 keys
2016/10/25 13:57:41 [INFO] core: vault is unsealed
2016/10/25 13:57:41 [INFO] core: post-unseal setup starting
2016/10/25 13:57:41 [INFO] core: mounted backend of type generic at secret/
2016/10/25 13:57:41 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/10/25 13:57:41 [INFO] core: mounted backend of type system at sys/
2016/10/25 13:57:41 [INFO] core: mounted backend of type pki at production-epsilon/
2016/10/25 13:57:41 [INFO] core: mounted backend of type pki at production-gamma/
2016/10/25 13:57:41 [INFO] core: mounted backend of type pki at production-delta/
2016/10/25 13:57:41 [INFO] rollback: starting rollback manager
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x5d3fc]

goroutine 27 [running]:
runtime.throw(0xf64368, 0x5)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc820568aa0 sp=0xc820568a88
runtime.sigpanic()
    /usr/local/Cellar/go/1.6/libexec/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc820568af0 sp=0xc820568aa0
runtime.memmove(0xc82016def0, 0x141357926b9b7, 0x5)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/memmove_amd64.s:136 +0x36c fp=0xc820568af8 sp=0xc820568af0
strings.Join(0xc8203358c0, 0x3, 0x4, 0xf5d618, 0x1, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/strings/strings.go:364 +0x172 fp=0xc820568bf0 sp=0xc820568af8
github.com/armon/go-metrics.(*InmemSink).flattenKey(0xc8201ee820, 0xc8203358c0, 0x3, 0x4, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/inmem.go:239 +0x60 fp=0xc820568c50 sp=0xc820568bf0
github.com/armon/go-metrics.(*InmemSink).AddSample(0xc8201ee820, 0xc8203358c0, 0x3, 0x4, 0xc8d3abfed1)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/inmem.go:166 +0x4f fp=0xc820568cd0 sp=0xc820568c50
github.com/armon/go-metrics.(*Metrics).MeasureSince(0xc8201ee870, 0xc8203358c0, 0x3, 0x4, 0xecfa1be47, 0x368bad27, 0x16a8360)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/metrics.go:61 +0x51b fp=0xc820568e10 sp=0xc820568cd0
github.com/armon/go-metrics.MeasureSince(0xc820487cc0, 0x2, 0x2, 0xecfa1be47, 0x368bad27, 0x16a8360)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/start.go:94 +0x5d fp=0xc820568e50 sp=0xc820568e10
github.com/hashicorp/vault/physical.(*S3Backend).List(0xc82013c000, 0xc8201dc3c0, 0x25, 0xc82008b780, 0x6, 0x8, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/physical/s3.go:188 +0x575 fp=0xc820568fd0 sp=0xc820568e50
github.com/hashicorp/vault/physical.(*Cache).List(0xc82013c0c0, 0xc8201dc3c0, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/physical/cache.go:83 +0x77 fp=0xc820569028 sp=0xc820568fd0
github.com/hashicorp/vault/vault.(*AESGCMBarrier).List(0xc820290000, 0xc8201dc3c0, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:664 +0x210 fp=0xc8205690c0 sp=0xc820569028
github.com/hashicorp/vault/vault.(*BarrierView).List(0xc82040e340, 0xc820490ac0, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/barrier_view.go:44 +0x17f fp=0xc820569158 sp=0xc8205690c0
github.com/hashicorp/vault/vault.ScanView(0xc82040e340, 0xc8205692f8, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/barrier_view.go:114 +0x103 fp=0xc8205692d8 sp=0xc820569158
github.com/hashicorp/vault/vault.CollectKeys(0xc82040e340, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/barrier_view.go:141 +0x7c fp=0xc820569328 sp=0xc8205692d8
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore(0xc820551580, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/expiration.go:120 +0xb5 fp=0xc8205694a8 sp=0xc820569328
github.com/hashicorp/vault/vault.(*Core).setupExpiration(0xc8203dba40, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/expiration.go:93 +0x260 fp=0xc8205695a8 sp=0xc8205694a8
github.com/hashicorp/vault/vault.(*Core).postUnseal(0xc8203dba40, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/core.go:1298 +0x54e fp=0xc820569700 sp=0xc8205695a8
github.com/hashicorp/vault/vault.(*Core).Unseal(0xc8203dba40, 0xc8204a2bd0, 0x21, 0x21, 0x0, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/core.go:1141 +0xbc1 fp=0xc8205698d0 sp=0xc820569700
github.com/hashicorp/vault/http.handleSysUnseal.func1(0x195b2c8, 0xc820071790, 0xc8204ffb20)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/http/sys_seal.go:82 +0x5fc fp=0xc820569a10 sp=0xc8205698d0
net/http.HandlerFunc.ServeHTTP(0xc82012c470, 0x195b2c8, 0xc820071790, 0xc8204ffb20)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a fp=0xc820569a30 sp=0xc820569a10
net/http.(*ServeMux).ServeHTTP(0xc820518480, 0x195b2c8, 0xc820071790, 0xc8204ffb20)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1910 +0x17d fp=0xc820569a88 sp=0xc820569a30
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x195b2c8, 0xc820071790, 0xc8204ffb20)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/http/help.go:18 +0x11d fp=0xc820569b30 sp=0xc820569a88
net/http.HandlerFunc.ServeHTTP(0xc82013c6e0, 0x195b2c8, 0xc820071790, 0xc8204ffb20)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a fp=0xc820569b50 sp=0xc820569b30
net/http.serverHandler.ServeHTTP(0xc82008a100, 0x195b2c8, 0xc820071790, 0xc8204ffb20)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 +0x19e fp=0xc820569bb0 sp=0xc820569b50
net/http.(*conn).serve(0xc82008bc80)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 +0xf2e fp=0xc820569f78 sp=0xc820569bb0
runtime.goexit()
    /usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820569f80 sp=0xc820569f78
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2137 +0x44e

goroutine 1 [chan receive]:
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc8200d4300, 0xc82000a3e0, 0x2, 0x2, 0xc8201d1e30)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/command/server.go:307 +0x3a8b
github.com/mitchellh/cli.(*CLI).Run(0xc8200d4240, 0xc8200d4240, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/mitchellh/cli/cli.go:153 +0x5ee
github.com/hashicorp/vault/cli.RunCustom(0xc82000a3d0, 0x3, 0x3, 0xc8202023f0, 0xc8200160b8)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/cli/main.go:44 +0x454
github.com/hashicorp/vault/cli.Run(0xc82000a3d0, 0x3, 0x3, 0x657850)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x4c
main.main()
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/main.go:10 +0x60

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/Cellar/go/1.6/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/Cellar/go/1.6/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select, locked to thread]:
runtime.gopark(0x12177e8, 0xc82002e728, 0xf67fc8, 0x6, 0x18, 0x2)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82002e728, 0x0, 0x18)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82002e728)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
    /usr/local/Cellar/go/1.6/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
    /usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/hashicorp/vault/cli.makeShutdownCh.func1(0xc820017d40, 0xc820017ce0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/cli/commands.go:308 +0x36
created by github.com/hashicorp/vault/cli.makeShutdownCh
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/cli/commands.go:311 +0x1a5

goroutine 9 [semacquire]:
sync.runtime_Syncsemacquire(0xc8200d4400)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8200d43f0)
    /usr/local/Cellar/go/1.6/libexec/src/sync/cond.go:63 +0x9b
io.(*pipe).read(0xc8200d43c0, 0xc82024a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc820030278, 0xc82024a000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc8201a1280, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/bufio/scan.go:208 +0x97b
github.com/hashicorp/vault/command.(*Meta).FlagSet.func1(0xc8201a1280, 0xc8200d4320)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/command/meta.go:187 +0x25
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/command/meta.go:190 +0x56b

goroutine 10 [select]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc8202140c0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xf3
created by github.com/armon/go-metrics.NewInmemSignal
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x239

goroutine 11 [sleep]:
time.Sleep(0x3b9aca00)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/time.go:59 +0xf9
github.com/armon/go-metrics.(*Metrics).collectStats(0xc8201ee870)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/metrics.go:67 +0x25
created by github.com/armon/go-metrics.New
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/start.go:61 +0xdc

goroutine 37 [IO wait]:
net.runtime_pollWait(0x18dd7c0, 0x72, 0x18d3050)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202000d0, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202000d0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820200070, 0x0, 0x18e51b0, 0xc820474400)
    /usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820554010, 0x51a80, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/tcpsock_posix.go:254 +0x4d
github.com/hashicorp/vault/command/server.tcpKeepAliveListener.Accept(0xc820554010, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/command/server/listener_tcp.go:35 +0x41
net/http.(*Server).Serve(0xc82008a100, 0x18e5100, 0xc820554010, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2117 +0x129
created by github.com/hashicorp/vault/command.(*ServerCommand).Run
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/command/server.go:296 +0x39b7

goroutine 67 [select]:
github.com/hashicorp/vault/vault.(*RollbackManager).run(0xc820559b60)
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/rollback.go:96 +0x1e0
created by github.com/hashicorp/vault/vault.(*RollbackManager).Start
    /private/tmp/vault20160218-53288-1ba0ddh/gopath/src/github.com/hashicorp/vault/vault/rollback.go:73 +0x35

goroutine 65 [IO wait]:
net.runtime_pollWait(0x18dd580, 0x72, 0xc820234000)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820201870, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820201870, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820201810, 0xc820234000, 0x8000, 0x8000, 0x0, 0x18d3050, 0xc820010058)
    /usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8205540a0, 0xc820234000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204a3620, 0x18dda40, 0xc8205540a0, 0x5, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82048ac00, 0x1217817, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82048ac00, 0xc82028b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x18e4ec0, 0xc82048ac00, 0xc820071998, 0xc82028b000, 0x1000, 0x1000, 0x4ce3, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc820467ea0, 0xc82028b000, 0x1000, 0x1000, 0xc8204b3d0d, 0x0, 0x0)
    <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820559620)
    /usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820559620, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820071930)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:853 +0x10a6

goroutine 66 [select]:
net/http.(*persistConn).writeLoop(0xc820071930)
    /usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:854 +0x10cb
```

**Comment by anandkumarpatel** [comment]
tried again with latest vault (v0.6.2) and it worked. However it took 3 min to unlock:

```
$ vault server -log-level=trace --config=/tmp/vault.hcl
==> Vault server configuration:

                 Backend: s3
              Listener 1: tcp (addr: "127.0.0.1:31836", cluster address: "", tls: "disabled")
               Log Level: trace
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.2

==> Vault server started! Log data will stream in below:

2016/10/25 14:09:10.668428 [TRACE] physical/cache: creating LRU cache: size=1048576
2016/10/25 14:09:10.668727 [TRACE] cluster listener addresses synthesized: cluster_addresses=[127.0.0.1:31837]
2016/10/25 14:09:32.307716 [DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=3
2016/10/25 14:09:36.866530 [DEBUG] core: cannot unseal, not enough keys: keys=2 threshold=3
2016/10/25 14:09:42.308929 [INFO ] core: vault is unsealed
2016/10/25 14:09:42.413362 [INFO ] core: post-unseal setup starting
2016/10/25 14:09:42.561409 [INFO ] core: successfully mounted backend: type=generic path=secret/
2016/10/25 14:09:42.561463 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2016/10/25 14:09:42.561646 [INFO ] core: successfully mounted backend: type=system path=sys/
2016/10/25 14:09:42.561811 [INFO ] core: successfully mounted backend: type=pki path=production-epsilon/
2016/10/25 14:09:42.561900 [INFO ] core: successfully mounted backend: type=pki path=production-gamma/
2016/10/25 14:09:42.562007 [INFO ] core: successfully mounted backend: type=pki path=production-delta/
2016/10/25 14:09:42.562104 [INFO ] rollback: starting rollback manager
2016/10/25 14:10:42.562353 [DEBUG] rollback: attempting rollback: path=sys/
2016/10/25 14:10:42.562442 [DEBUG] rollback: attempting rollback: path=auth/token/
2016/10/25 14:10:42.562494 [DEBUG] rollback: attempting rollback: path=secret/
2016/10/25 14:10:42.562546 [DEBUG] rollback: attempting rollback: path=production-delta/
2016/10/25 14:10:42.562600 [DEBUG] rollback: attempting rollback: path=production-epsilon/
2016/10/25 14:10:42.562647 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2016/10/25 14:10:42.562703 [DEBUG] rollback: attempting rollback: path=production-gamma/
2016/10/25 14:11:42.563211 [DEBUG] rollback: attempting rollback: path=secret/
2016/10/25 14:11:42.563350 [DEBUG] rollback: attempting rollback: path=auth/token/
2016/10/25 14:11:42.563461 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2016/10/25 14:11:42.563570 [DEBUG] rollback: attempting rollback: path=production-gamma/
2016/10/25 14:11:42.563638 [DEBUG] rollback: attempting rollback: path=sys/
2016/10/25 14:11:42.563706 [DEBUG] rollback: attempting rollback: path=production-delta/
2016/10/25 14:11:42.563759 [DEBUG] rollback: attempting rollback: path=production-epsilon/
2016/10/25 14:11:56.108043 [INFO ] expire: leases restored: restored_lease_count=931
2016/10/25 14:11:56.667298 [INFO ] core: post-unseal setup complete
2016/10/25 14:12:42.562610 [DEBUG] rollback: attempting rollback: path=auth/token/
2016/10/25 14:12:42.562736 [DEBUG] rollback: attempting rollback: path=sys/
2016/10/25 14:12:42.562818 [DEBUG] rollback: attempting rollback: path=secret/
2016/10/25 14:12:42.562911 [DEBUG] rollback: attempting rollback: path=cubbyhole/
2016/10/25 14:12:42.562992 [DEBUG] rollback: attempting rollback: path=production-gamma/
2016/10/25 14:12:42.563102 [DEBUG] rollback: attempting rollback: path=production-epsilon/
2016/10/25 14:12:42.563194 [DEBUG] rollback: attempting rollback: path=production-delta/
```

**Comment by jefferai** [comment]
The slow speed you're seeing is purely due to storage operations. I would guess you're running out of IOPS.
