### ISSUE TITLE
panic when starting vault server with -recovery flag

### ISSUE THREAD

**Issue by FalcoSuessgott** [hashicorp/vault#20396]
**Describe the bug**
```bash
vault server -config assets/vault-cfg.hcl -recovery
```

panics with:

```
panic: flag redefined: combine-logs

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0010f0a20, {0x7dab0f8, 0xc0012782d0}, {0x6973c02, 0xc}, {0x0, 0x0})
        /home/runner/actions-runner/_work/_tool/go/1.20.3/x64/src/flag/flag.go:982 +0x2f9
github.com/hashicorp/vault/command.(*FlagSet).Var(0xc0012743f0, {0x7dab0f8, 0xc0012782d0}, {0x6973c02, 0xc}, {0x0, 0x0})
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/base_flags.go:857 +0x45
github.com/hashicorp/vault/command.(*FlagSet).VarFlag(0xc0012743f0, 0xc0010bdb70)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/base_flags.go:807 +0xe5
github.com/hashicorp/vault/command.(*FlagSet).BoolVar(0x194?, 0xc0010bdc18)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/base_flags.go:156 +0x2a5
github.com/hashicorp/vault/command.(*FlagSet).addLogFlags(0x4f496b?, 0xc000d443c8)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/log_flags.go:34 +0x85
github.com/hashicorp/vault/command.(*ServerCommand).Flags(0xc000d443c0)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/server.go:179 +0x1c5
github.com/hashicorp/vault/command.(*ServerCommand).runRecoveryMode(0xc000d443c0)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/server.go:449 +0x8e
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc000d443c0, {0xc00011a020, 0x3, 0x3})
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/server.go:935 +0xb05
github.com/mitchellh/cli.(*CLI).Run(0xc0011fc000)
        /home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
github.com/hashicorp/vault/command.RunCustom({0xc00011a010?, 0x4?, 0x4?}, 0xc0000061a0?)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/main.go:238 +0xa65
github.com/hashicorp/vault/command.Run(...)
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/main.go:142
main.main()
        /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/main.go:16 +0x50
```

**To Reproduce**
1. start the vault server, specify a config file and add the `-recovery` flag

**Expected behavior**
I expect the server to start in recovery mode.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `v.1.13.2`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.13.2+ent (ca5ea376af76440caa5e82e9b659b9e7c09268b4), built 2023-04-25T19:30:45Z`
* Server Operating System/Architecture: `Linux x86_64`

**Comment by FalcoSuessgott** [comment]
panic goes away when using version `v1.12.1`. Will upgrade until I found the version where this "bug" seems to be introduced

**Comment by maxb** [comment]
It looks like this regression was introduced in #18031 and v1.13.0-rc1 - flag setup code which must only be executed once has been moved into the `command.(*ServerCommand).Flags` function which is called from multiple places in the code.
