### ISSUE TITLE
TLS auth login fails on self-signed certificate

### ISSUE THREAD

**Issue by ianunruh** [hashicorp/vault#214]
To test client-side TLS authentication, I generated a self-signed certificate using:

```bash
openssl req -x509 -nodes -days 3650 \
    -newkey rsa:2048 -keyout client-key.pem \
    -out client-cert.pem -config client.cnf
```

With the following OpenSSL config file:

```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = client

[v3_req]
basicConstraints = CA:TRUE
```

I then add the `client-cert.pem` file to the `cert` auth backend, as described in the docs. However, when I try to `POST /v1/auth/certs/login`, the Vault server generates the following exception.

```
2015/05/17 15:45:07 http: panic serving 127.0.0.1:63763: runtime error: slice bounds out of range
goroutine 32 [running]:
net/http.func·011()
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1130 +0xbb
github.com/hashicorp/vault/builtin/credential/cert.validateConnState(0xc2080530e0, 0xc2081b2900, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:158 +0x55e
github.com/hashicorp/vault/builtin/credential/cert.(*backend).pathLogin(0xc2080fcb50, 0xc2080b5730, 0xc20811b150, 0x5cf3c0, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:42 +0xce
github.com/hashicorp/vault/builtin/credential/cert.*backend.(github.com/hashicorp/vault/builtin/credential/cert.pathLogin)·fm(0xc2080b5730, 0xc20811b150, 0x68e610, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:25 +0x4d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc2080ec360, 0xc2080b5730, 0x28, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/logical/framework/backend.go:126 +0x813
github.com/hashicorp/vault/vault.(*Router).Route(0xc208180be0, 0xc2080b5730, 0x0, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/vault/router.go:209 +0x94a
github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0xc208072400, 0xc2080b5730, 0x0, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/vault/core.go:446 +0x2ed
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc208072400, 0xc2080b5730, 0x0, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/vault/core.go:323 +0x173
github.com/hashicorp/vault/http.request(0xc208072400, 0xad3540, 0xc208076dc0, 0xc208110340, 0xc2080b5730, 0x675150, 0x4)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/http/handler.go:74 +0x32
github.com/hashicorp/vault/http.func·002(0xad3540, 0xc208076dc0, 0xc208110340)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/http/logical.go:67 +0x5a9
net/http.HandlerFunc.ServeHTTP(0xc20802bc00, 0xad3540, 0xc208076dc0, 0xc208110340)
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208053a70, 0xad3540, 0xc208076dc0, 0xc208110340)
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0xad3540, 0xc208076dc0, 0xc208110340)
	/Users/mitchellh/code/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc2080b2ae0, 0xad3540, 0xc208076dc0, 0xc208110340)
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2080cbec0, 0xad3540, 0xc208076dc0, 0xc208110340)
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081af540)
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/Users/mitchellh/code/3rdparty/go/src/net/http/server.go:1751 +0x35e
```

I'm not an expert when it comes to certificates, so I may be doing something wrong.

**Comment by ianunruh** [comment]
The same error also occurs when I follow the [instructions used](https://langui.sh/2009/01/18/openssl-self-signed-ca/) to generate the [certificates used by Vault for testing](https://github.com/hashicorp/vault/tree/master/test).

**Comment by armon** [comment]
@ianunruh I think you were hitting a bug, which should be fixed in master. Please retry and let us know if still an issue

**Comment by ianunruh** [comment]
Now I get an 400 Bad Request with the error `invalid certificate`. That's definitely better than a 500 + stack trace.

Should I be able to use a self-signed certificate for TLS auth?

**Comment by armon** [comment]
@ianunruh This means that the certificate presented was not trusted. e.g. none of the installed trusted keys were used to sign the client key.

**Comment by ianunruh** [comment]
For some reason, I still cannot get TLS auth to work. Steps to reproduce:

```bash
git clone https://github.com/hashicorp/vault.git
cd vault/test

openssl verify -CAfile ca/root.cer key/ourdomain.cer # => OK

export VAULT_CAPATH=XXX
vault init
export VAULT_TOKEN=YYY
vault unseal ZZZ
vault auth-enable cert
vault write auth/cert/certs/test policies=test certificate=@ca/root.cer

wget --method=POST --no-check-certificate --certificate=key/ourdomain.cer --private-key=key/ourdomain.key https://localhost:8200/v1/auth/cert/login # => 400 Bad Request
```

The same failure happens from Python too.

```python
import requests
r = requests.post('https://localhost:8200/v1/auth/cert/login', verify=False, cert=('key/ourdomain.cer', 'key/ourdomain.key'))
r.text # => u'{"errors":["invalid certificate"]}\n'
```

**Comment by joemiller** [comment]
My expectation of how it should work is similar to @ianunruh but I am hitting the same issue.

Also it appears `VAULT_CAPATH` is only used by vault in client mode, not in the server mode? I didn't see any code that would indicate it is validating client certs but perhaps that is happening automatically if the client uses a cert in the TLS handshake.

**Comment by joemiller** [comment]
I think I may have figured out the issue. Even if you specify a client cert (I'm using `curl` in my tests with `-E /path/keyandcert.pem`, but presume similar with other clients) there are no client certs being set on the `tls.ConnectionState` struct being passed to `validateConnState` in the cert auth `path_login.go` file.

I changed the tcp listener to request client cert as such:

```
diff --git a/command/server/listener.go b/command/server/listener.go
index 4772606..d96be81 100644
--- a/command/server/listener.go
+++ b/command/server/listener.go
@@ -51,6 +51,7 @@ func listenerWrapTLS(
        }

        tlsConf := &tls.Config{}
+       tlsConf.ClientAuth = tls.RequestClientCert
```
and now I am able to obtain a token:

```
$ curl -kE ./client.pem $VAULT_ADDR/v1/auth/cert/login -XPOST
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"auth":{"client_token":"5a4a5577-98af-787d-1462-26e8b39c8ff0","policies":["root"],"metadata":{"cert_name":"test1"},"lease_duration":3600,"renewable":true}}
```

**Comment by armon** [comment]
I think @joemiller is right, it looks like our tests set RequestClientCert, but the actual build does not.

**Comment by armon** [comment]
I just pushed that fix, so hopefully this resolves the issue you are seeing @ianunruh
