### ISSUE TITLE
Crash during network outage

### ISSUE THREAD

**Issue by g-cassie** [hashicorp/vault#2309]
Last night some network maintenance was performed in a datacenter where we have a vault/consul cluster running.  There was about 2 hours of network outage during which the instances in the cluster could not communicate.  When the network came back up, vault had crashed and was now sealed.  

Looking through the logs we found the following:
```
Jan 27 06:54:05 myhost consul[32730]:     2017/01/27 06:54:05 [ERR] http: Request GET /v1/kv/vault/core/lock?consistent=, error: No cluster leader from=127.0.0.1:39072
Jan 27 06:54:05 myhost consul[32730]:     2017/01/27 06:54:05 [ERR] agent: failed to sync remote state: No cluster leader
Jan 27 06:54:07 myhost consul[32730]:     2017/01/27 06:54:07 [ERR] raft: Failed to make RequestVote RPC to {Voter <internal ip> <internal ip>:8300}: dial tcp <internal ip>:8300: getsockopt: no route to host
Jan 27 06:54:13 myhost consul[32730]:     2017/01/27 06:54:13 [WARN] raft: Election timeout reached, restarting election
Jan 27 06:54:13 myhost consul[32730]:     2017/01/27 06:54:13 [INFO] raft: Node at <internal ip>:8300 [Candidate] entering Candidate state in term 74
Jan 27 06:54:14 myhost consul[32730]:     2017/01/27 06:54:14 [ERR] http: Request GET /v1/kv/vault/core/lock?consistent=, error: No cluster leader from=127.0.0.1:39078
Jan 27 06:54:14 myhost vault[2953]: 2017/01/27 06:54:14.711993 [WRN] core: leadership lost, stopping active operation
Jan 27 06:54:16 myhost consul[32730]:     2017/01/27 06:54:16 [ERR] raft: Failed to make RequestVote RPC to {Voter <internal ip>:8300 <internal ip>:8300}: dial tcp <internal ip>:8300: getsockopt: no route to host
Jan 27 06:54:19 myhost consul[32730]:     2017/01/27 06:54:19 [WARN] raft: Election timeout reached, restarting election
Jan 27 06:54:19 myhost consul[32730]:     2017/01/27 06:54:19 [INFO] raft: Node at <internal ip>:8300 [Candidate] entering Candidate state in term 75
Jan 27 06:54:19 myhost consul[32730]:     2017/01/27 06:54:19 [ERR] raft: Failed to make RequestVote RPC to {Voter <internal ip>:8300 <internal ip>:8300}: dial tcp <internal ip>:8300: getsockopt: no route to host
Jan 27 06:54:19 myhost vault[2953]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 27 06:54:19 myhost vault[2953]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcf098d]
Jan 27 06:54:19 myhost vault[2953]: goroutine 74 [running]:
Jan 27 06:54:19 myhost vault[2953]: panic(0x127b580, 0xc42000c030)
Jan 27 06:54:19 myhost vault[2953]:         /goroot/src/runtime/panic.go:500 +0x1a1
Jan 27 06:54:19 myhost vault[2953]: github.com/hashicorp/vault/vendor/github.com/Azure/azure-sdk-for-go/storage.BlobStorageClient.DeleteBlobIfExists(0x0, 0xc4202547ca, 0x5, 0xc420252f00, 0x40, 0x42, 0x1, 0x146f6ce, 0x10, 0x14653a4, ...)
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go:1000 +0x13d
Jan 27 06:54:19 myhost vault[2953]: github.com/hashicorp/vault/physical.(*AzureBackend).Delete(0xc420750b00, 0xc4208c3710, 0x30, 0x0, 0x0)
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/physical/azure.go:147 +0x1e0
Jan 27 06:54:19 myhost vault[2953]: github.com/hashicorp/vault/physical.(*Cache).Delete(0xc420671e00, 0xc4208c3710, 0x30, 0x2, 0x2)
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/physical/cache.go:76 +0x4b
Jan 27 06:54:19 myhost vault[2953]: github.com/hashicorp/vault/vault.(*AESGCMBarrier).Delete(0xc420754540, 0xc4208c3710, 0x30, 0x0, 0x0)
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:665 +0x190
Jan 27 06:54:19 myhost vault[2953]: github.com/hashicorp/vault/vault.(*Core).clearLeader(0xc4205dfc00, 0xc4201ab530, 0x24, 0xed01cd5b2, 0x4395395)
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/vault/core.go:1472 +0x99
Jan 27 06:54:19 myhost vault[2953]: github.com/hashicorp/vault/vault.(*Core).runStandby(0xc4205dfc00, 0xc420759740, 0xc4207597a0, 0xc420759800)
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/vault/core.go:1285 +0xb7d
Jan 27 06:54:19 myhost vault[2953]: created by github.com/hashicorp/vault/vault.(*Core).Unseal
Jan 27 06:54:19 myhost vault[2953]:         /gopath/src/github.com/hashicorp/vault/vault/core.go:801 +0x58f
Jan 27 06:54:19 myhost systemd[1]: vault.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 27 06:54:19 myhost systemd[1]: vault.service: Unit entered failed state.
Jan 27 06:54:19 myhost systemd[1]: vault.service: Failed with result 'exit-code'.
Jan 27 06:54:19 myhost systemd[1]: vault.service: Service hold-off time over, scheduling restart.
Jan 27 06:54:19 myhost systemd[1]: Stopped Manage the vault server.
Jan 27 06:54:20 myhost systemd[1]: Started Manage the vault server.
Jan 27 06:54:24 myhost consul[32730]:     2017/01/27 06:54:24 [WARN] agent: Check 'vault:<internal ip>:8200:vault-sealed-check' missed TTL, is now critical
Jan 27 06:54:24 myhost consul[32730]:     2017/01/27 06:54:24 [WARN] raft: Election timeout reached, restarting election
Jan 27 06:54:24 myhost consul[32730]:     2017/01/27 06:54:24 [INFO] raft: Node at <internal ip>:8300 [Candidate] entering Candidate state in term 76
Jan 27 06:54:25 myhost vault[18070]: ==> Vault server configuration:
Jan 27 06:54:25 myhost vault[18070]:               HA Backend: consul
Jan 27 06:54:25 myhost vault[18070]:                  Backend: azure
Jan 27 06:54:25 myhost vault[18070]:               Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
Jan 27 06:54:25 myhost vault[18070]:                Log Level: info
Jan 27 06:54:25 myhost vault[18070]:                    Mlock: supported: true, enabled: false
Jan 27 06:54:25 myhost vault[18070]:         Redirect Address: https://<internal ip>:8200
Jan 27 06:54:25 myhost vault[18070]:                  Version: Vault v0.6.1
Jan 27 06:54:25 myhost vault[18070]: ==> Vault server started! Log data will stream in below:
Jan 27 06:54:27 myhost consul[32730]:     2017/01/27 06:54:27 [ERR] agent: coordinate update error: No cluster leader
Jan 27 06:54:27 myhost consul[32730]:     2017/01/27 06:54:27 [ERR] raft: Failed to make RequestVote RPC to {Voter <internal ip>:8300 <internal ip>:8300}: dial tcp <internal ip>:8300: getsockopt: no route to host
Jan 27 06:54:30 myhost consul[32730]:     2017/01/27 06:54:30 [WARN] raft: Election timeout reached, restarting election
Jan 27 06:54:30 myhost consul[32730]:     2017/01/27 06:54:30 [INFO] raft: Node at <internal ip>:8300 [Candidate] entering Candidate state in term 77
Jan 27 06:54:30 myhost consul[32730]:     2017/01/27 06:54:30 [ERR] agent: failed to sync remote state: No cluster leader
Jan 27 06:54:30 myhost consul[32730]:     2017/01/27 06:54:30 [INFO] serf: attempting reconnect to doazure1 <internal ip>:8301
Jan 27 06:54:30 myhost consul[32730]:     2017/01/27 06:54:30 [ERR] raft: Failed to make RequestVote RPC to {Voter <internal ip>:8300 <internal ip>:8300}: dial tcp <internal ip>:8300: getsockopt: no route to host
Jan 27 06:54:32 myhost consul[32730]:     2017/01/27 06:54:32 [ERR] agent: failed to sync changes: No cluster leader
Jan 27 06:54:37 myhost consul[32730]:     2017/01/27 06:54:37 [WARN] agent: Check 'vault:<internal ip>:8200:vault-sealed-check' missed TTL, is now critical
Jan 27 06:54:37 doazure2 consul[32730]:     2017/01/27 06:54:37 [WARN] raft: Election timeout reached, restarting election
```

**Comment by jefferai** [comment]
Hi,

That crash is coming from the Azure library that is being used for your backend. 0.6.1 is pretty old and we update our deps before every release, so it might well be fixed already. Otherwise you'll need to open a bug report with the SDK maintainers.
