### ISSUE TITLE
Vault Agent/Proxy in 1.15.0 Cant Get Token (AWS-IAM Auth)

### ISSUE THREAD

**Issue by patcable** [hashicorp/vault#23481]
**Describe the bug**
`vault agent` receives nil authentication information from the vault server after upgrading to 1.15.0. I was previously running 1.14.0 and this did work.

**To Reproduce**
Run the vault agent with an auto-auth stanza:
```
auto_auth {
  method "aws" {
    mount_path = "auth/aws-ec2"
    config = {
      type = "iam"
      role = "web-server"
      header_value = "vault.dev.mydomain"
    }
  }
  sink "file" {
    wrap_ttl = "5m"
    config = {
        path = "/secret/token"
    }
  }
}
```

```
Oct 03 19:48:01 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:01.291Z [ERROR] agent.auth.handler: error authenticating: error="Put \"https://vault.dev.mydomain:8200/v1/auth/aws-ec2/login\": stream error: stream ID 3; INTERNAL_ERROR; received from peer" backoff=1s
Oct 03 19:48:02 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:02.293Z [INFO]  agent.auth.handler: authenticating
Oct 03 19:48:02 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:02.319Z [ERROR] agent.auth.handler: authentication returned nil auth info: backoff=1.86s
Oct 03 19:48:04 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:04.180Z [INFO]  agent.auth.handler: authenticating
Oct 03 19:48:04 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:04.185Z [ERROR] agent.auth.handler: authentication returned nil auth info: backoff=2.81s
Oct 03 19:48:06 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:06.998Z [INFO]  agent.auth.handler: authenticating
Oct 03 19:48:07 i-abcdef01234567890 vault[26929]: 2023-10-03T19:48:07.003Z [ERROR] agent.auth.handler: authentication returned nil auth info: backoff=4.9s
```

Server side audit shows requests (timestamp doesn't line up because i pulled this later, but confirmed it lined up with another vault-agent's request)
```
{
  "time": "2023-10-03T19:50:56.909630212Z",
  "type": "request",
  "auth": {
    "policy_results": {
      "allowed": true
    },
    "token_type": "default"
  },
  "request": {
    "id": "cc52c4d9-5100-b06a-c006-6d2a98b0cfe2",
    "operation": "update",
    "mount_point": "auth/aws-ec2/",
    "mount_type": "aws-ec2",
    "mount_accessor": "auth_aws-ec2_0549cfca",
    "mount_running_version": "v1.15.0+builtin.vault",
    "mount_class": "auth",
    "namespace": {
      "id": "root"
    },
    "path": "auth/aws-ec2/login",
    "data": {
      "iam_http_request_method": "hmac-sha256:4fd3ff29dd22e8860a50097fc38103210bdd613588cc63e873c85b03697c253f",
      "iam_request_body": "hmac-sha256:08dc674caed80c3bb3e55b646eab4efa520fe2002214f029176bd7e6fe72d667",
      "iam_request_headers": "hmac-sha256:5f332e95c1947f8f183f0538b83cceb50fd37eaf19bdfbea3a8be8f35ca3fd89",
      "iam_request_url": "hmac-sha256:1399113b163ed2354063621961865baef8d4b61fefe0c8fb610554e6d04d709c",
      "role": "hmac-sha256:1ccd9748e8889ec74728ff2ab4f7af3f8e8bb34196e02c55c84fa5fadb78a171"
    },
    "remote_address": "10.1.2.3",
    "remote_port": 49670
  }
```

**Expected behavior**
Vault agent receives a token and carries on with it's life.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.0
* Vault CLI Version (retrieve with `vault version`): 1.15.0, tried with 1.14.4 and 1.14.0 as well, so this seems like a server-side issue.
* Server Operating System/Architecture: Ubuntu 20.04 amd64

Vault server configuration file(s):

```hcl
storage "raft" {
  path    = "/var/lib/vault"
  node_id = "blah"
  retry_join {
    auto_join = "provider=aws region=us-east-1 tag_key=blah tag_value=blah"
  }
}

service_registration "consul" {
  address      = "127.0.0.1:7500"
}

listener "tcp" {
  address = "10.1.2.2:8200"
  tls_cert_file = "/secret/service.pem"
  tls_key_file = "/secret/service-key.pem"
}

seal "awskms" {
  region     = "us-east-1"
  kms_key_id = "blah"
  endpoint   = "https://kms.us-east-1.amazonaws.com"
}

telemetry {
  statsd_address = "127.0.0.1:8125"
  disable_hostname = true
}

default_lease_ttl = "8h"
ui = true
plugin_directory = "/etc/vault/plugins"
api_addr = "https://10.1.2.2:8200"
cluster_addr = "https://10.1.2.2:8201"
disable_mlock = true
```

**Additional context**
EC2 instance identity auth seems to work fine (I have a different plugin that hits /auth/aws-ec2/login and that's working fine), so perhaps this is limited to IAM role based auth?

**Comment by patcable** [comment]
Running vault in trace debug mode... i think this could be the issue 

```
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]: 2023-10-03T20:13:29.065Z [ERROR] core: panic serving forwarded request: path=/v1/auth/aws-ec2/login error="runtime error: invalid memory address or nil pointer dereference"
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   stacktrace=
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | goroutine 4901 [running]:
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | runtime/debug.Stack()
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x64
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*forwardedRequestRPCServer).ForwardRequest.func1.1()
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_forwarding_rpc.go:48 +0x44
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | panic({0x78c0360?, 0x1020b0c0?})
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x218
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/builtin/credential/aws.(*backend).pathLoginIamGetRoleNameCallerIdAndEntity(0x4003b8e780, {0xad5e5c0, 0x400439def0}, 0x4004d3d6c0, 0x400451fb28?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/builtin/credential/aws/path_login.go:326 +0xce4
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/builtin/credential/aws.(*backend).pathLoginUpdateIam(0x4003b8e780, {0xad5e5c0, 0x400439def0}, 0x4004d3d6c0, 0x4004dcf9b0?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/builtin/credential/aws/path_login.go:1356 +0x34
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/builtin/credential/aws.(*backend).pathLoginUpdate(0x0?, {0xad5e5c0, 0x400439def0}, 0x4010105?, 0x1?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/builtin/credential/aws/path_login.go:610 +0x210
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0x400349e870, {0xad5e5c0, 0x400439def0}, 0x4004d3d6c0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/sdk/framework/backend.go:310 +0x900
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/builtin/plugin/v5.(*backend).HandleRequest(0x4005273cc0, {0xad5e5c0, 0x400439def0}, 0x4004d3d6c0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/builtin/plugin/v5/backend.go:95 +0xcc
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Router).routeCommon(0x40033e4060, {0xad5e5c0, 0x400439def0}, 0x4004d3d6c0, 0x0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/router.go:784 +0x11fc
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Router).Route(...)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/router.go:553
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Core).doRouting(0x4003c94840?, {0xad5e5c0?, 0x400439def0?}, 0x40026be230?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_handling.go:922 +0x2c
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0x40033e8000, {0xad5e5c0, 0x400439def0}, 0x4004d3d6c0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_handling.go:1486 +0x91c
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Core).handleCancelableRequest(0x40033e8000, {0xad5e5c0, 0x400439dec0}, 0x4004d3d6c0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_handling.go:764 +0x112c
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Core).switchedLockHandleRequest(0x40033e8000, {0xad5e5c0, 0x400439da40}, 0x4004d3d6c0, 0x1)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_handling.go:573 +0x4cc
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*Core).HandleRequest(...)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_handling.go:530
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.request(0x4004dcf848?, {0xad40090, 0x400439d950}, 0x4004c52900, 0x4004d3d6c0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/handler.go:934 +0x6c
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.handler.handleLogical.handleLogicalInternal.func57({0xad40090, 0x400439d950}, 0x4004c52900)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/logical.go:375 +0x150
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x40033e8000?, {0xad40090?, 0x400439d950?}, 0x6634?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.handler.handleRequestForwarding.func36({0xad40090, 0x400439d950}, 0x4004c52900)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/handler.go:868 +0x240
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x4003437218?, {0xad40090?, 0x400439d950?}, 0x2ddb4f8?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.(*ServeMux).ServeHTTP(0x4004fea910?, {0xad40090, 0x400439d950}, 0x4004c52900)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2514 +0x144
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.handler.wrapHelpHandler.func48({0xad40090, 0x400439d950}, 0x4004c52900)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/help.go:28 +0x114
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x4003900c18?, {0xad40090?, 0x400439d950?}, 0x1721f88?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.handler.wrapCORSHandler.func49({0xad40090, 0x400439d950}, 0x4004c52900)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/cors.go:32 +0x370
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x40033e8000?, {0xad40090?, 0x400439d950?}, 0x40051fd020?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.handler.rateLimitQuotaWrapping.func50({0xad40090, 0x400439d950}, 0x4004c52900)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/util.go:128 +0x914
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x40033e8000?, {0xad40090?, 0x400439d950?}, 0xc13f3b5a43cd60a7?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.wrapGenericHandler.func1({0xad3f918?, 0x4004c307e0}, 0x4004c52600)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/http/handler.go:453 +0xb48
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x4004dcf848?, {0xad3f918?, 0x4004c307e0?}, 0x30?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/http.handler.PrintablePathCheckHandler.func51({0xad3f918, 0x4004c307e0}, 0x4004c52600)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/go/pkg/mod/github.com/hashicorp/go-cleanhttp@v0.5.2/handlers.go:42 +0x88
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | net/http.HandlerFunc.ServeHTTP(0x60?, {0xad3f918?, 0x4004c307e0?}, 0x0?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2136 +0x38
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*forwardedRequestRPCServer).ForwardRequest.func1()
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_forwarding_rpc.go:51 +0x70
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault.(*forwardedRequestRPCServer).ForwardRequest(0x4005327b60, {0x4004f2f900?, 0x40026be0e0?}, 0x0?)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_forwarding_rpc.go:53 +0xe4
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | github.com/hashicorp/vault/vault._RequestForwarding_ForwardRequest_Handler({0x803af40?, 0x4005327b60}, {0xad5e5c0, 0x400439d830}, 0x40026be0e0, 0x0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/work/vault/vault/vault/request_forwarding_service_grpc.pb.go:127 +0x164
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | google.golang.org/grpc.(*Server).processUnaryRPC(0x4003062960, {0xad81f80, 0x4004f2f7c0}, 0x4005cda5a0, 0x4005327bf0, 0x10232100, 0x0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xc04
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | google.golang.org/grpc.(*Server).handleStream(0x4003062960, {0xad81f80, 0x4004f2f7c0}, 0x4005cda5a0, 0x0)
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x7c4
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | google.golang.org/grpc.(*Server).serveStreams.func1.1()
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x84
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 4987
Oct 03 20:13:29 i-abcdef01234567890 vault[1765041]:   | \t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x154
```

**Comment by maxiscoding28** [comment]
Looks related to: https://github.com/hashicorp/vault/issues/23361

**Comment by patcable** [comment]
@maxiscoding28 i'd agree; i had searched around but I didn't quite match it. I'm going to try that workaround and if it works close this issue. Thanks!

**Comment by patcable** [comment]
Yep, that was it. Closing the issue in favor of #23361.
