### ISSUE TITLE
Acme the request message was malformed :: unexpected request parameters: The request message was malformed

### ISSUE THREAD

**Issue by tsiamer** [hashicorp/vault#24131]
Hi all,
Not able to generate a cert,  getting acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: unexpected request parameters: The request message was malformed

 Cluster config:
```
Key         Value

aia_path    https://active.vault.service.consul:8200/v1/pki_int
path        https://active.vault.service.consul:8200/v1/pki_int
```
Acme Config:
```
Key                         Value

allow_role_ext_key_usage    false
allowed_issuers             [*]
allowed_roles               [*]
default_directory_policy    sign-verbatim
dns_resolver                n/a
eab_policy                  always-required
enabled                     true
```
Role
```
Key                                   Value
---                                   -----
allow_any_name                        false
allow_bare_domains                    false
allow_glob_domains                    true
allow_ip_sans                         false
allow_localhost                       true
allow_subdomains                      true
allow_token_displayname               false
allow_wildcard_certificates           true
allowed_domains                       [domain.uk]
allowed_domains_template              false
allowed_other_sans                    []
allowed_serial_numbers                []
allowed_uri_sans                      []
allowed_uri_sans_template             false
allowed_user_ids                      []
basic_constraints_valid_for_non_ca    false
client_flag                           true
cn_validations                        [email hostname]
code_signing_flag                     false
country                               []
email_protection_flag                 false
enforce_hostnames                     false
ext_key_usage                         []
ext_key_usage_oids                    []
generate_lease                        false
issuer_ref                            bc62febf-8394-ddf0-5394-bc55b3e19d8f
key_bits                              256
key_type                              ec
key_usage                             [DigitalSignature KeyAgreement KeyEncipherment]
locality                              []
max_ttl                               0s
no_store                              false
not_after                             n/a
not_before_duration                   0s
organization                          []
ou                                    []
policy_identifiers                    []
postal_code                           []
province                              []
require_cn                            false
server_flag                           true
signature_bits                        0
street_address                        []
ttl                                   0s
use_csr_common_name                   false
use_csr_sans                          false
use_pss                               false
```

Run command
```
certbot certonly --config-dir=. --work-dir=. --logs-dir=. --server https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/directory --standalone -d $HOSTNAME --email tally@hotmail.com --agree-tos --no-eff-email --eab-kid $EAB_KID --eab-hmac-key $EAB_HMAC
```

Error
```

2023-11-15 00:06:34,232:DEBUG:urllib3.connectionpool:https://active.vault.service.consul:8200 "POST /v1/pki_int/roles/learn/acme/authorization/503f68b0-63cc-0758-03c0-d4e797dd4348 HTTP/1.1" 200 757
2023-11-15 00:06:34,232:DEBUG:acme.client:Received response:
HTTP 200
Cache-Control: no-store
Content-Type: application/json
Link: <https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/directory>;rel="index"
Replay-Nonce: dmF1bHQwAL53qgDEHyAInEMUR-IDUKqQRqnef622cZUlqEAqoOepQpGjKoB9VA
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Wed, 15 Nov 2023 00:06:34 GMT
Content-Length: 757

{"challenges":[{"status":"pending","token":"wKZDNPsY7Bqfmy0V9zzKnehZ7TxO","type":"http-01","url":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/challenge/503f68b0-63cc-0758-03c0-d4e797dd4348/http-01"},{"status":"pending","token":"YX5FXEQLr4xYXC6nXuLvJRkOxwQ7","type":"dns-01","url":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/challenge/503f68b0-63cc-0758-03c0-d4e797dd4348/dns-01"},{"status":"pending","token":"V1kfdrqrD0ExT-V_McGxkXngNkfP","type":"tls-alpn-01","url":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/challenge/503f68b0-63cc-0758-03c0-d4e797dd4348/tls-alpn-01"}],"identifier":{"type":"dns","value":"test.domain.uk"},"status":"pending","wildcard":false}
2023-11-15 00:06:34,232:DEBUG:acme.client:Storing nonce: dmF1bHQwAL53qgDEHyAInEMUR-IDUKqQRqnef622cZUlqEAqoOepQpGjKoB9VA
2023-11-15 00:06:34,232:INFO:certbot.auth_handler:Performing the following challenges:
2023-11-15 00:06:34,232:INFO:certbot.auth_handler:http-01 challenge for test.domain.uk
2023-11-15 00:06:34,233:DEBUG:acme.standalone:Successfully bound to :80 using IPv6
2023-11-15 00:06:34,233:DEBUG:acme.standalone:Certbot wasn't able to bind to :80 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.
2023-11-15 00:06:34,234:INFO:certbot.auth_handler:Waiting for verification...
2023-11-15 00:06:34,234:DEBUG:acme.client:JWS payload:
b'{\n  "resource": "challenge",\n  "type": "http-01"\n}'
2023-11-15 00:06:34,235:DEBUG:acme.client:Sending POST request to https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/challenge/503f68b0-63cc-0758-03c0-d4e797dd4348/http-01:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWN0aXZlLnZhdWx0LnNlcnZpY2UuaG9tZS1jb25zdWw6ODIwMC92MS9wa2lfaW50L3JvbGVzL2xlYXJuL2FjbWUvYWNjb3VudC81NmY5ZThlZi02NTZhLWNmNjUtOThiYS1jNjEwYzVkODVlODkiLCAibm9uY2UiOiAiZG1GMWJIUXdBTDUzcWdERUh5QUluRU1VUi1JRFVLcVFScW5lZjYyMmNaVWxxRUFxb09lcFFwR2pLb0I5VkEiLCAidXJsIjogImh0dHBzOi8vYWN0aXZlLnZhdWx0LnNlcnZpY2UuaG9tZS1jb25zdWw6ODIwMC92MS9wa2lfaW50L3JvbGVzL2xlYXJuL2FjbWUvY2hhbGxlbmdlLzUwM2Y2OGIwLTYzY2MtMDc1OC0wM2MwLWQ0ZTc5N2RkNDM0OC9odHRwLTAxIn0",
  "signature": "W-bFGW6E7nUxgINuJYMSjSgLDoPqjyn211xO-UEDDjgcOStuJkjzfsyGEa7xIBZW2EyDv3QFdJG-mL3Nv4rXmZeBUL1ofdk2FmtY2dpzltMhBlrpXFc4Auso_EYhDPN4SDgQIhLyaQJP3CKOQCtoTuFHjKv4nRACiMZEjnXnDj8pPrR2GZlraC-UPrVArsoIt4Lmx8lyAZYmzGcMfZ4OeolUOSdLas2ZqVMpB3cnikYbTSRmGRLSe-QTbzhpl15MoOBajBdHEtWvsvhb8n98F6BqtF29kGIZqBDA7_ua-A0St7AA_1aJKE3NMtlvFmo81NS2gNiURZuarlsoaDr2TA",
  "payload": "ewogICJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLAogICJ0eXBlIjogImh0dHAtMDEiCn0"
}
2023-11-15 00:06:34,237:DEBUG:urllib3.connectionpool:https://active.vault.service.consul:8200 "POST /v1/pki_int/roles/learn/acme/challenge/503f68b0-63cc-0758-03c0-d4e797dd4348/http-01 HTTP/1.1" 400 142
2023-11-15 00:06:34,237:DEBUG:acme.client:Received response:
HTTP 400
Cache-Control: no-store
Content-Type: application/problem+json
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Wed, 15 Nov 2023 00:06:34 GMT
Content-Length: 142

{"type":"urn:ietf:params:acme:error:malformed","detail":"unexpected request parameters: The request message was malformed","subproblems":null}
2023-11-15 00:06:34,238:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 88, in handle_authorizations
    self.acme.answer_challenge(achall.challb, resp)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 165, in answer_challenge
    response = self._post(challb.uri, response)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 95, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1171, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1184, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1042, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: unexpected request parameters: The request message was malformed

2023-11-15 00:06:34,238:DEBUG:certbot.error_handler:Calling registered functions
2023-11-15 00:06:34,238:INFO:certbot.auth_handler:Cleaning up challenges
2023-11-15 00:06:34,238:DEBUG:certbot.plugins.standalone:Stopping server at :::80...
2023-11-15 00:06:34,734:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1382, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1265, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 417, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 348, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 396, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 88, in handle_authorizations
    self.acme.answer_challenge(achall.challb, resp)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 165, in answer_challenge
    response = self._post(challb.uri, response)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 95, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1171, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1184, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1042, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: unexpected request parameters: The request message was malformed
2023-11-15 00:06:34,734:ERROR:certbot.log:An unexpected error occurred:
2023-11-15 00:06:34,734:ERROR:certbot.log:The request message was malformed :: unexpected request parameters: The request message was malformed
```
**Expected behavior**
I am able to generate a cert with both dns and http using certbot without vault,  but when using vault getting. The request message was malformed :: unexpected request parameters: The request message was malformed

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.15.1 
* Vault CLI Version (retrieve with `vault version`):Vault 1.15.1 
* Server Operating System/Architecture:Linux/x86_64

**Comment by stevendpclark** [comment]
Hi @tsiamer, thanks for the report! 

So the issue seems to be that the certbot client is sending us a payload when responding to challenges, even though it is pretty clear in the ACME spec that it shouldn't be. [RFC 8555 Section 7.5.1](https://datatracker.ietf.org/doc/html/rfc8555#section-7.5.1) says the following

> The client indicates to the server that it is ready for the challenge
> validation by sending an empty JSON body ("{}") carried in a POST
> request to the challenge URL (not the authorization URL).

But from the logs it seems like it is sending the following `{"resource": "challenge",  "type": "http-01"}`. We are enforcing the spec, perhaps that is incorrect and we should simply ignore any data sent to us on that endpoint 🤔. 

I noticed in the certbot stack trace the running version seems to be 0.40.0 which is pretty old, end of 2019. Is it possible to try with a newer version, at this time latest version is 2.7.4, or are you required to run this version for some reason?

**Comment by tsiamer** [comment]
Hi Steven,

When i use the latest version:

```
certbot -vvv certonly --config-dir=. --work-dir=. --logs-dir=. --server https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/directory --standalone -d $HOSTNAME --email tally@hotmail.com --agree-tos --no-eff-email --eab-kid $EAB_KID --eab-hmac-key $EAB_HMAC
```

Error:
```
Max retries exceeded with url: /v1/pki_int/roles/learn/acme/directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
```


```
Root logging level set at 0
Saving debug log to /root/letsencrypt.log
Requested authenticator standalone and installer None
Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7ff748ac20d0>
Prep: True
Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x7ff748ac20d0> and installer None
Plugins selected: Authenticator standalone, Installer None
Sending GET request to https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/directory.
Starting new HTTPS connection (1): active.vault.service.consul:8200
Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/snap/certbot/3462/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/snap/certbot/3462/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/snap/certbot/3462/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/certbot/3462/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/snap/certbot/3462/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='active.vault.service.consul', port=8200): Max retries exceeded with url: /v1/pki_int/roles/learn/acme/directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/certbot/3462/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/_internal/main.py", line 1582, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/_internal/main.py", line 833, in _init_le_client
    acc, acme = _determine_account(config)
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/_internal/main.py", line 741, in _determine_account
    acc, acme = client.register(
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/_internal/client.py", line 207, in register
    acme = acme_from_config_key(config, key)
  File "/snap/certbot/3462/lib/python3.8/site-packages/certbot/_internal/client.py", line 72, in acme_from_config_key
    directory = acme_client.ClientV2.get_directory(config.server, net)
  File "/snap/certbot/3462/lib/python3.8/site-packages/acme/client.py", line 331, in get_directory
    return messages.Directory.from_json(net.get(url).json())
  File "/snap/certbot/3462/lib/python3.8/site-packages/acme/client.py", line 706, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/snap/certbot/3462/lib/python3.8/site-packages/acme/client.py", line 648, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/snap/certbot/3462/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/certbot/3462/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/snap/certbot/3462/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='active.vault.service.consul', port=8200): Max retries exceeded with url: /v1/pki_int/roles/learn/acme/directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
An unexpected error occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='active.vault.service.consul', port=8200): Max retries exceeded with url: /v1/pki_int/roles/learn/acme/directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /root/letsencrypt.log or re-run Certbot with -v for more details.
```


Definitely i do have the ca trusted, 

```
curl -Ik https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/directory

HTTP/2 405
cache-control: no-store
content-type: application/json
strict-transport-security: max-age=31536000; includeSubDomains
content-length: 37
date: Wed, 15 Nov 2023 17:41:49 GMT

```


```
curl -v https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/directory


* TCP_NODELAY set
* Connected to active.vault.service.consul (192.168.1.44) port 8200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=client.mdc.consul
*  start date: Jan 14 15:52:52 2023 GMT
*  expire date: Jan 14 15:52:52 2024 GMT
*  subjectAltName: host "active.vault.service.consul" matched cert's "*.vault.service.consul"
*  issuer: C=US; ST=CA; L=San Francisco; street=101 Second Street; postalCode=94105; O=HashiCorp Inc.; CN=Consul Agent CA 271834744395876646111844081152853876813
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55ee360e5920)
> GET /v1/pki_int/roles/learn/acme/directory HTTP/2
> Host: active.vault.service.consul:8200
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
< cache-control: no-store
< content-type: application/json
< strict-transport-security: max-age=31536000; includeSubDomains
< content-length: 536
< date: Wed, 15 Nov 2023 17:42:43 GMT
<
* Connection #0 to host active.vault.service.consul left intact



{"keyChange":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/key-change","meta":{"externalAccountRequired":true},"newAccount":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/new-account","newNonce":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/new-nonce","newOrder":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/new-order","revokeCert":"https://active.vault.service.consul:8200/v1/pki_int/roles/learn/acme/revoke-cert"}


```

**Comment by stevendpclark** [comment]
Hey @tsiamer, thanks for the attempt and thorough reply. 

Based on the output stack trace of certbot, would you be using a snap build of the newer version? I'm not an expert around the various bundling technologies but I don't believe they use the OS's certificate stores by default. That could explain why certbot is failing the CA verification but curl isn't?

Not the best, but could you try adding `--no-verify-ssl` argument to certbot's invocation to eliminate that possibility?

**Comment by tsiamer** [comment]
> Hey @tsiamer, thanks for the attempt and thorough reply.
> 
> Based on the output stack trace of certbot, would you be using a snap build of the newer version? 
Yes

I'm not an expert around the various bundling technologies but I don't believe they use the OS's certificate stores by default. That could explain why certbot is failing the CA verification but curl isn't?

It seems so as it is working now.
> 
> Not the best, but could you try adding `--no-verify-ssl` argument to certbot's invocation to eliminate that possibility?

Yes all working now thank you very much.

**Comment by stevendpclark** [comment]
Great! With the fact that newer versions of Certbot do seem to work, I'll close out this issue keeping our current checks in place.
