### ISSUE TITLE
Master node fall down after error "panic: runtime error: invalid memory address or nil pointer dereference" Vault 1.14.3

### ISSUE THREAD

**Issue by RNDM-01** [hashicorp/vault#24419]
**Describe the bug**
We have a Vault HA cluster with integrated storage on AWS. Cluster consisted 6 nodes. During the update of each node one by one (from version 1.6.1 to 1.14.3) we faced the error "_panic: runtime error: invalid memory address or nil pointer dereference" and fell down vault service. When we had 3/6 already updated nodes, we tried to force one of them to become a master node by stopping vault services on two old vault nodes (1.6.1). After those actions, the cluster quorum consisted of 3 new nodes (v1.14.3) and one (v1.6.1) nodes.  All 3 nodes in version 1.14.3 were successfully initiated, joined to the cluster, and unsealed by the transit node. When one of the new nodes became the master node, it fell down with an error, and other nodes started voting again.

Vault process on raft-node-0 and raft-node-3 was turn off manually. So you can see error: _storage.raft: failed to heartbeat to: peer=node-3_

Error:
 ```
vault[16999]: 2023-12-04T20:17:25.342Z [INFO]  core: starting raft active node
vault[16999]: 2023-12-04T20:17:25.342Z [INFO]  storage.raft: starting autopilot: config="&{false 0 10s 24h0m0s 1000 0 10s false redundancy_zone upgrade_version}" reconcile_interval=0s
 vault[16999]: 2023-12-04T20:17:25.344Z [INFO]  core: usage gauge collection is disabled
 vault[16999]: 2023-12-04T20:17:25.346Z [INFO]  core: post-unseal setup complete
 vault[16999]: 2023-12-04T20:17:25.674Z [INFO]  expiration: lease restore complete
 vault[16999]: 2023-12-04T20:17:25.689Z [ERROR] storage.raft: failed to appendEntries to: peer="{Voter raft-node-0 node-0.vault-cluster.local-env.com:8201}" error="dial tcp 172.22.202.22:8201: connect: connection refused"
 vault[16999]: 2023-12-04T20:17:25.693Z [ERROR] storage.raft: failed to appendEntries to: peer="{Voter raft-node-3 node-3.vault-cluster.local-env.com:8201}" error="dial tcp 172.22.202.12:8201: connect: connection refused" 172.22.202.12:8201: connect: connection refused"
 vault[16999]: 2023-12-04T20:17:26.134Z [ERROR] storage.raft: failed to heartbeat to: peer=node-3.vault-cluster.local-env.com:8201 backoff time=10ms error="dial tcp 172.22.202.12:8201: connect: connection refused"
 vault[16999]: 2023-12-04T20:17:26.182Z [ERROR] storage.raft: failed to heartbeat to: peer=node-0.vault-cluster.local-env.com:8201 backoff time=10ms error="dial tcp 172.22.202.22:8201: connect: connection refused"
 vault[16999]: 2023-12-04T20:17:26.757Z [ERROR] storage.raft: failed to appendEntries to: peer="{Voter raft-node-0 node-0.vault-cluster.local-env.com:8201}" error="dial tcp 172.22.202.22:8201: connect: connection refused"
 vault[16999]: 2023-12-04T20:17:26.792Z [WARN]  storage.raft: appendEntries rejected, sending older logs: peer="{Voter raft-node-3 node-3.vault-cluster.local-env.com:8201}" next=19196560
 vault[16999]: 2023-12-04T20:17:26.807Z [INFO]  storage.raft: pipelining replication: peer="{Voter raft-node-3 node-3.vault-cluster.local-env.com:8201}"
 vault[16999]: 2023-12-04T20:17:26.918Z [ERROR] storage.raft: failed to heartbeat to: peer=node-0.vault-cluster.local-env.com:8201 backoff time=10ms error="dial tcp 172.22.202.22:8201: connect: connection refused"
 vault[16999]: panic: runtime error: invalid memory address or nil pointer dereference
 vault[16999]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x31b4be0]
 vault[16999]: goroutine 888 [running]:
 vault[16999]: github.com/hashicorp/vault/vault.(*Core).GetHAPeerNodesCached(0x4062bd?)
 vault[16999]: /home/runner/work/vault/vault/vault/core.go:3750 +0x180
 vault[16999]: github.com/hashicorp/vault/vault.(*Core).getHAMembers(0xc002df8800)
 vault[16999]: /home/runner/work/vault/vault/vault/ha.go:118 +0x1ff
 vault[16999]: github.com/hashicorp/vault/vault.(*Core).monitorUndoLogs.func1()
 vault[16999]: /home/runner/work/vault/vault/vault/raft.go:244 +0x2bf
 vault[16999]: created by github.com/hashicorp/vault/vault.(*Core).monitorUndoLogs
 vault[16999]: /home/runner/work/vault/vault/vault/raft.go:217 +0x218
```
**To Reproduce**
1. Deploy cluster on  nodes v1.6.1
2. Deploy new nodes (v1.14.3) one by one 
3. Force new node become master node (by using operator step-down command or stoping vault process for 2 old nodes)
4. See error on master node logs

**Expected behavior**
New nodes on vault version 1.14.3 can become master node without fall down 

**Environment:**
* Vault v1.14.3 (56debfa71653e72433345f23cd26276bc90629ce), built 2023-09-11T21:23:55Z
* Server Operating System/Architecture: 
Linux/UNIX x86_64 CIS Amazon Linux 2 Benchmark v2.0.0.26

Vault server configuration file(s):

```
As i mentioned before new nodes, were successfully unsealed and joined to cluster, so config file correct.
```

**Comment by miagilepner** [comment]
Thanks for reporting this! We're working on a fix

**Comment by miagilepner** [comment]
Our [guidance](https://developer.hashicorp.com/vault/docs/upgrading/vault-ha-upgrade#ha-installations) when upgrading is to have the active node be the last one to be upgraded to the higher version. From your description, it sounds like this wasn't the procedure that you followed. Is that correct?
