### ISSUE TITLE
Java Null Error when Jenkins Plugin is selected but no secrets are pulled

### ISSUE THREAD

**Issue by RichardWolford** [hashicorp/vault#2647]
If you have a Jenkins job, and have selected the Vault plugin, but you have not added any secrets to the job yet, you will get an error similar to this:

FATAL: null
java.lang.NullPointerException
	at com.datapipe.jenkins.vault.VaultBuildWrapper.setUp(VaultBuildWrapper.java:208)
	at jenkins.tasks.SimpleBuildWrapper.setUp(SimpleBuildWrapper.java:145)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1733)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)

By simply unchecking the Vault plugin for the job, or by actually adding a secret, this error goes away.

**Comment by jefferai** [comment]
Hi @RichardWolford ,

We do not maintain any such Jenkins plugin -- you'll need to file an issue with the plugin author. Sorry!
