### ISSUE TITLE
Vault unseal process fails with azure as the storage backend

### ISSUE THREAD

**Issue by shubangmck** [hashicorp/vault#27706]
**Describe the bug**

Vault fails to unseal with the error
```
Error unsealing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/unseal
Code: 500. Errors:

* failed to setup audit table
```

**To Reproduce**
1. Run the `vault unseal` command threshold number of times and paste the vault unseal keys.
2. Returns an error
```
Error unsealing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/unseal
Code: 500. Errors:

* failed to setup audit table
```

Vault debug logs
```
```-- Logs begin at Mon 2024-05-06 15:37:04 UTC. --
Jul 06 13:49:37 vaultaz vault[5188]: 2024-07-06T13:49:37.855Z [INFO]  core: pre-seal teardown starting
Jul 06 13:49:37 vaultaz vault[5188]: 2024-07-06T13:49:37.855Z [DEBUG] audit: removing reload function: path=file/
Jul 06 13:49:37 vaultaz vault[5188]: 2024-07-06T13:49:37.856Z [DEBUG] expiration: stop triggered
Jul 06 13:49:37 vaultaz /usr/bin/vault[5188]: 2024/07/06 13:49:37 ==> REQUEST/RESPONSE (Try=1/54.493284ms, OpTime=54.539385ms) -- REQUEST ERROR
                                                 GET https://sensitive_storage_account.blob.core.windows.net/sensitive_container_name?comp=list&maxresults=5000&prefix=sys%2Fexpire%2Fid%2F&restype=container&timeout=61
                                                 Authorization: REDACTED
                                                 User-Agent: [Azure-Storage/0.15 (go1.21.1; linux)]
                                                 X-Ms-Client-Request-Id: [a6fd8aa7-aebb-48f4-54ba-f54eb92c4142]
                                                 X-Ms-Version: [2020-10-02]
                                                 x-ms-date: [Sat, 06 Jul 2024 13:49:37 GMT]
                                                 --------------------------------------------------------------------------------
                                                 RESPONSE Status: 200 OK
                                                 Content-Type: [application/xml]
                                                 Date: [Sat, 06 Jul 2024 13:49:36 GMT]
                                                 Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
                                                 X-Ms-Client-Request-Id: [a6fd8aa7-aebb-48f4-54ba-f54eb92c4142]
                                                 X-Ms-Request-Id: [7445ce8c-101e-005a-34ab-cf54c8000000]
                                                 X-Ms-Version: [2020-10-02]
                                                 --------------------------------------------------------------------------------
                                                 ERROR:
                                              context canceled
                                              goroutine 806 [running]:
                                              github.com/Azure/azure-storage-blob-go/azblob.stack()
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_request_log.go:158 +0x5e
                                              github.com/Azure/azure-storage-blob-go/azblob.NewPipeline.NewRequestLogPolicyFactory.func3.1({0xb8b5a10, 0xc002637110}, {0xc0029c31e0?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_request_log.go:108 +0x66a
                                              github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x9b84ce0?, {0xb8b5a10?, 0xc002637110?}, {0xd?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x29
                                              github.com/Azure/azure-storage-blob-go/azblob.(*SharedKeyCredential).New.func1({0xb8b5a10, 0xc002637110}, {0xdf8475800?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_credential_shared_key.go:66 +0x3d7
                                              github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xb8b59a0?, {0xb8b5a10?, 0xc002637110?}, {0xa317704?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x29
                                              github.com/Azure/azure-storage-blob-go/azblob.NewPipeline.NewRetryPolicyFactory.func2.1({0xb8b59a0, 0xc00350d220}, {0xc0029c0ed0?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_retry.go:204 +0x8d8
                                              github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xf448bbaea78afda6?, {0xb8b59a0?, 0xc00350d220?}, {0xc003646090?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x29
                                              github.com/Azure/azure-storage-blob-go/azblob.NewPipeline.NewUniqueRequestIDPolicyFactory.func1.1({0xb8b59a0, 0xc00350d220}, {0xc0029c3080?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_unique_request_id.go:22 +0xe2
                                              github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x93fbca0?, {0xb8b59a0?, 0xc00350d220?}, {0xa?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x29
                                              github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1({0xb8b59a0, 0xc00350d220}, {0xc0029bc868?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_telemetry.go:34 +0x11e
                                              github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc002db33c0?, {0xb8b59a0?, 0xc00350d220?}, {0x0?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x29
                                              github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc002b56600?, {0xb8b59a0, 0xc00350d220}, {0xb834b40?, 0xc0029be580?}, {0xc002b56608?})
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x4a
                                              github.com/Azure/azure-storage-blob-go/azblob.containerClient.ListBlobFlatSegment({{{{0xc002b56600, 0x5}, {0x0, 0x0}, 0x0, {0xc002b56608, 0x2a}, {0xc002b56632, 0x8}, {0x0, ...}, ...}, ...}}, ...)
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zz_generated_container.go:596 +0x44b
                                              github.com/Azure/azure-storage-blob-go/azblob.ContainerURL.ListBlobsFlatSegment({{{{{...}, {...}, 0x0, {...}, {...}, {...}, 0x0, 0x0, {...}, {...}, ...}, ...}}}, ...)
                                                      /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/url_container.go:238 +0x10e
                                              github.com/hashicorp/vault/physical/azure.(*AzureBackend).List(0xc003385e20, {0xb8b59a0, 0xc00350d220}, {0xc00340a050, 0xe})
                                                      /home/runner/work/vault/vault/physical/azure/azure.go:281 +0x271
                                              github.com/hashicorp/vault/vault.(*sealUnwrapper).List(0xc002f0eb28?, {0xb8b59a0?, 0xc00350d220?}, {0xc00340a050?, 0x99e345?})
                                                      /home/runner/work/vault/vault/vault/sealunwrapper.go:133 +0x2a
                                              github.com/hashicorp/vault/sdk/physical.(*Cache).List(0xc002f0eb28?, {0xb8b59a0?, 0xc00350d220?}, {0xc00340a050?, 0x496c4f?})
                                                      /home/runner/work/vault/vault/sdk/physical/cache.go:225 +0x2a
                                              github.com/hashicorp/vault/vault.(*AESGCMBarrier).List(0xc002b5e380, {0xb8b59a0, 0xc00350d220}, {0xc00340a050, 0xe})
                                                      /home/runner/work/vault/vault/vault/barrier_aes_gcm.go:908 +0x18e
                                              github.com/hashicorp/vault/vault.(*ForwardedWriter).List(0xc0034db8f0, {0xb8b59a0, 0xc00350d220}, {0xc00340a050?, 0xc19a70bc6fc7a81c?})
                                                      /home/runner/work/vault/vault/vault/forwarded_writer_oss.go:60 +0xa4
                                              github.com/hashicorp/vault/sdk/logical.(*StorageView).List(0xc003510c20, {0xb8b59a0, 0xc00350d220}, {0x0, 0x0})
                                                      /home/runner/work/vault/vault/sdk/logical/storage_view.go:31 +0xbc
                                              github.com/hashicorp/vault/vault.(*BarrierView).List(0xc19a70bc6fc7a81c?, {0xb8b59a0?, 0xc00350d220?}, {0x0?, 0xc002c27950?})
                                                      /home/runner/work/vault/vault/vault/barrier_view.go:57 +0x25
                                              github.com/hashicorp/vault/sdk/logical.ScanView({0xb8b59a0, 0xc00350d220}, {0xb85dad8, 0xc003e97ac0}, 0xc002205dc8)
                                                      /home/runner/work/vault/vault/sdk/logical/storage.go:78 +0xf0
                                              github.com/hashicorp/vault/sdk/logical.CollectKeysWithPrefix({0xb8b59a0?, 0xc00350d220?}, {0xb85dad8?, 0xc003e97ac0?}, {0x0?, 0xc0029c0ab0?})
                                                      /home/runner/work/vault/vault/sdk/logical/storage.go:150 +0x85
                                              github.com/hashicorp/vault/sdk/logical.CollectKeys(...)



**Expected behavior**
Vault should unseal without errors or give an auth error if keys are wrong

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    0/3
Unseal Nonce       n/a
Version            1.15.0
Build Date         2023-09-22T16:53:10Z
Storage Type       azure
HA Enabled         false
```

* Vault CLI Version (retrieve with `vault version`):
`Vault v1.15.0 (b4d07277a6c5318bb50d3b94bbd6135dccb4c601), built 2023-09-22T16:53:10Z`
* Server Operating System/Architecture:
Ubuntu 20.04 amd64
Vault server configuration file(s):

```hcl
ui = true
default_lease_ttl = "87600h"
max_lease_ttl = "876000h"

storage "azure" {
  accountName = "sensitive"
  accountKey  = "sensitive"
  container   = "sensitive"
}

listener "tcp" {
 address     = "127.0.0.1:8200"
 tls_disable = 1
}
```

**Additional context**

**Comment by shubangmck** [comment]
This has nothing to do with the azure backend, after disabling debug logs, there is a log statement which says that there are permission errors to write to `/var/log/vault/audit.log`, if you are installing vault 1.15 on Ubuntu manually, I think you will have to create the path `/var/log/vault/audit.log` and make the user `vault` as its owner using the command `chown -R vault:vault /var/log/vault/`. Vault unseals without any issues after this
