### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by sjparkinson** [hashicorp/vault#2839]
Looking at migrating from 0.7.2 to 0.7.3, on unseal we are finding the process panics. Tried restarting the process an unsealing a few times.

```
==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: ...
                 Storage: dynamodb (HA available)
                 Version: Vault v0.7.3
             Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68

==> Vault server started! Log data will stream in below:

2017/06/08 14:23:57.901478 [INFO ] core: vault is unsealed
2017/06/08 14:23:57.901729 [INFO ] core: entering standby mode
2017/06/08 14:24:13.908111 [INFO ] core: acquired lock, enabling active operation
2017/06/08 14:24:13.965876 [INFO ] core: post-unseal setup starting
2017/06/08 14:24:13.970267 [INFO ] core: loaded wrapping token key
2017/06/08 14:24:13.978248 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/06/08 14:24:13.978388 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/06/08 14:24:13.978480 [INFO ] core: successfully mounted backend: type=pki path=pki/.../
2017/06/08 14:24:13.978558 [INFO ] core: successfully mounted backend: type=pki path=pki/.../
2017/06/08 14:24:13.978583 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/06/08 14:24:13.978689 [INFO ] rollback: starting rollback manager
2017/06/08 14:24:13.999039 [INFO ] expiration: restoring leases
panic: runtime error: slice bounds out of range

goroutine 506 [running]:
github.com/hashicorp/vault/vault.(*AESGCMBarrier).decryptKeyring(0xc420052480, 0xc4204b2e60, 0x49, 0x0, 0x0, 0x0, 0x11630309, 0x26ef4a0, 0x2, 0xc4204b2e60, ...)
    /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:816 +0x5fa
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Get(0xc420052480, 0xc4204b2e60, 0x49, 0x0, 0x0, 0x0)
    /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:669 +0x217
github.com/hashicorp/vault/vault.(*BarrierView).Get(0xc420607d40, 0xc420682a80, 0x3b, 0xc4207adf98, 0x2, 0x2)
    /gopath/src/github.com/hashicorp/vault/vault/barrier_view.go:53 +0xbe
github.com/hashicorp/vault/vault.(*ExpirationManager).loadEntry(0xc4206d6320, 0xc420682a80, 0x3b, 0xc42086c600, 0xc420744901, 0x2b)
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:877 +0x47
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore.func1(0xc4206dc020, 0xc420808000, 0xc4206d6320, 0xc4208080c0, 0xc420808120, 0xc420808060)
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:268 +0x116
created by github.com/hashicorp/vault/vault.(*ExpirationManager).Restore
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:282 +0x390
```

```hcl
// We're using DynamoDB as our storage backend.
storage "dynamodb" {
  ha_enabled = "true"
  region = "eu-west-1" // AWS region.
  table = "vault-storage-eu-west-1"
  redirect_addr = "..." // Cluster address returned in 307 responses during failover.
  disable_clustering = "true" // Stop Vault instances from talking to each other.
}

// Listen on the default port with a self-signed certificate.
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 0
  tls_cert_file = "/etc/vault/ssl/server.crt"
  tls_key_file = "/etc/vault/ssl/server.key"
}

// By default encourage an 8h refresh of values.
default_lease_ttl = "8h"
```

**Comment by sjparkinson** [comment]
Just working on getting some debug logs.

We reverted the binary to 0.7.2 and are finding the same panic after unsealing, so perhaps it's unrelated to the version.

**Comment by sjparkinson** [comment]
```
==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
               Log Level: trace
                   Mlock: supported: true, enabled: true
        Redirect Address: ...
                 Storage: dynamodb (HA available)
                 Version: Vault v0.7.2
             Version Sha: d28dd5a018294562dbc9a18c95554d52b5d12390

==> Vault server started! Log data will stream in below:

2017/06/08 14:53:18.482369 [TRACE] physical/cache: creating LRU cache: size=32768
2017/06/08 14:53:38.723989 [DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=2 nonce=ce384e5b-624c-e420-3658-f0be00503ac6
2017/06/08 14:59:29.228466 [INFO ] core: vault is unsealed
2017/06/08 14:59:29.228694 [INFO ] core: entering standby mode
2017/06/08 14:59:29.228720 [TRACE] core: clearing forwarding clients
2017/06/08 14:59:29.228730 [TRACE] core: done clearing forwarding clients
2017/06/08 14:59:30.233343 [INFO ] core: acquired lock, enabling active operation
2017/06/08 14:59:30.247873 [TRACE] core: generating cluster private key
2017/06/08 14:59:30.259912 [TRACE] core: generating local cluster certificate
2017/06/08 14:59:30.280355 [INFO ] core: post-unseal setup starting
2017/06/08 14:59:30.280393 [TRACE] core: clearing forwarding clients
2017/06/08 14:59:30.280405 [TRACE] core: done clearing forwarding clients
2017/06/08 14:59:30.283424 [INFO ] core: loaded wrapping token key
2017/06/08 14:59:30.289393 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/06/08 14:59:30.289530 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/06/08 14:59:30.289636 [INFO ] core: successfully mounted backend: type=pki path=pki/.../
2017/06/08 14:59:30.289714 [INFO ] core: successfully mounted backend: type=pki path=pki/.../
2017/06/08 14:59:30.289748 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/06/08 14:59:30.289981 [INFO ] rollback: starting rollback manager
2017/06/08 14:59:30.309498 [INFO ] expiration: restoring leases
2017/06/08 14:59:30.309532 [DEBUG] expiration: collecting leases
2017/06/08 14:59:31.469208 [DEBUG] expiration: leases collected: num_existing=8666
2017/06/08 14:59:31.469349 [TRACE] expiration: leases loading: progress=0
panic: runtime error: slice bounds out of range

goroutine 612 [running]:
github.com/hashicorp/vault/vault.(*AESGCMBarrier).decryptKeyring(0xc42040a1e0, 0xc4206b6d20, 0x49, 0x0, 0x0, 0x0, 0x1c070958, 0x269d5a0, 0x2, 0xc4206b6d20, ...)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:816 +0x5fa
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Get(0xc42040a1e0, 0xc4206b6d20, 0x49, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:669 +0x217
github.com/hashicorp/vault/vault.(*BarrierView).Get(0xc420590510, 0xc420414a40, 0x3b, 0xc420936f98, 0x2, 0x2)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_view.go:53 +0xbe
github.com/hashicorp/vault/vault.(*ExpirationManager).loadEntry(0xc4206b6780, 0xc420414a40, 0x3b, 0xc421295e00, 0x1, 0x16bc8a0)
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:873 +0x47
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore.func1(0xc420c3d4c0, 0xc4208f6720, 0xc4206b6780, 0xc4208f67e0, 0xc4208f6840, 0xc4208f6780)
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:268 +0x116
created by github.com/hashicorp/vault/vault.(*ExpirationManager).Restore
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:282 +0x390
```

**Comment by jefferai** [comment]
The panic is coming while trying to read the encrypted entry. The entry exists (otherwise it would come back as nil), but when reading the first couple of bytes it's out of range. This suggests that it's some kind of issue with the underlying data in Dynamo. Do you have a backup you can revert to and see if the problem remains?

**Comment by sjparkinson** [comment]
> Do you have a backup you can revert to and see if the problem remains?

Not currently, still trialing vault.

**Comment by jefferai** [comment]
OK. It appears like something in dynamo is coming back as zero-length when fetched.

**Comment by sjparkinson** [comment]
We're not concerned with existing leases, thoughts on clearing them out of the storage so none are loaded?

**Comment by sjparkinson** [comment]
And anything you'd like me to collect that'd be helpful for this issue?

**Comment by sjparkinson** [comment]
Ok we've just wiped the table for simplicity. We did find a number of items in DynamoDB with no `Value` where we'd expect one. Have a feeling this relates to a backup solution we're developing so I wouldn't look too much into this.

**Comment by jefferai** [comment]
@sjparkinson Sorry I didn't get back to you before this, was swamped with HashiDays stuff. My guess is that it is indeed related to whatever is causing your zero values since that's what Vault is saying is happening. Let me know if you need this reopened!
