### ISSUE TITLE
Vault throws exceptions and exits under load

### ISSUE THREAD

**Issue by Constantin07** [hashicorp/vault#3399]
While testing `vault` under a load of ~ 300 API concurrent requests per second it just throws an exception and exits.

**Environment:**
Alpine Linux 3.6 (vault in docker container)
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

* Vault Version:
Host: MacOS Sierra 10.12.6
Docker: Community Edition 17.09.0-ce-rc3-mac30 (19329)

**Vault Config File:**
```
storage "file" {
  path = "/vault/file"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_key_file = "/vault/certs/vault-key.pem"
  tls_cert_file = "/vault/certs/vault-cert.pem"
  tls_min_version = "tls12"
}
```

**Startup Log Output:**
```
==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Storage: file
                 Version: Vault v0.8.3
             Version Sha: 6b29fb2b7f70ed538ee2b3c057335d706b6d4e36

==> Vault server started! Log data will stream in below:
2017/09/27 17:42:58.263076 [INFO ] core: vault is unsealed
2017/09/27 17:42:58.263345 [INFO ] core: post-unseal setup starting
2017/09/27 17:42:58.263588 [INFO ] core: loaded wrapping token key
2017/09/27 17:42:58.263605 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2017/09/27 17:42:58.263943 [INFO ] core: successfully mounted backend: type=kv path=secret/
2017/09/27 17:42:58.264100 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/09/27 17:42:58.264160 [INFO ] core: successfully mounted backend: type=pki path=tes-ca/
2017/09/27 17:42:58.264208 [INFO ] core: successfully mounted backend: type=pki path=tes-in-ca/
2017/09/27 17:42:58.264226 [INFO ] core: successfully mounted backend: type=generic path=secret-dev/
2017/09/27 17:42:58.264254 [INFO ] core: successfully mounted backend: type=database path=database/
2017/09/27 17:42:58.264271 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/09/27 17:42:58.265120 [INFO ] expiration: restoring leases
2017/09/27 17:42:58.265194 [INFO ] rollback: starting rollback manager
2017/09/27 17:42:58.265360 [INFO ] core: post-unseal setup complete
2017/09/27 17:42:58.267333 [INFO ] expiration: lease restore complete

```

**Expected Behavior:**
Handle gracefully (may be throttle) the overload in rate of API requests coming in but do not exit at all.

**Actual Behavior:**
Process just exits.

Here the output from logs:
```
runtime: address space conflict: map(0xc422100000) = 0xb
fatal error: runtime: address space conflict

runtime stack:
runtime.throw(0x1f17f37, 0x1f)
	/goroot/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc422100000, 0x100000, 0x456800, 0x2e6dcd8)
	/goroot/src/runtime/mem_linux.go:220 +0x1b5
runtime.(*mheap).sysAlloc(0x2e53dc0, 0x100000, 0x7fdc53394368)
	/goroot/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x2e53dc0, 0x1, 0x0)
	/goroot/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x2e53dc0, 0x1, 0x2e6dce8, 0x7fdc533942d0)
	/goroot/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x2e53dc0, 0x1, 0x1840010, 0x7fdc533942d0)
	/goroot/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
	/goroot/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0xc42006de98)
	/goroot/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x2e53dc0, 0x1, 0x7fdc53010010, 0x7fdc533942d0)
	/goroot/src/runtime/mheap.go:732 +0xa1
runtime.(*mcentral).grow(0x2e55510, 0x0)
	/goroot/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x2e55510, 0x7fdc535c9aa8)
	/goroot/src/runtime/mcentral.go:106 +0x33a
runtime.(*mcache).refill(0x7fdc53611458, 0x100000000000010, 0x7fdc535c9aa8)
	/goroot/src/runtime/mcache.go:123 +0xa4
runtime.(*mcache).nextFree.func1()
	/goroot/src/runtime/malloc.go:557 +0x32
runtime.systemstack(0xc420a23538)
	/goroot/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/goroot/src/runtime/proc.go:1125

...
goroutine 4745 [semacquire]:
sync.runtime_SemacquireMutex(0xc420a64974, 0x0)
	/goroot/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420a64970)
	/goroot/src/sync/mutex.go:134 +0xee
github.com/hashicorp/vault/plugins/database/mongodb.(*MongoDB).CreateUser(0xc420a3ca00, 0xc421302960, 0x51, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420363d14, ...)
	/gopath/src/github.com/hashicorp/vault/plugins/database/mongodb/mongodb.go:85 +0xa0
github.com/hashicorp/vault/builtin/logical/database/dbplugin.(*databaseMetricsMiddleware).CreateUser(0xc420a3ca20, 0xc421302960, 0x51, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420363d14, ...)
	/gopath/src/github.com/hashicorp/vault/builtin/logical/database/dbplugin/databasemiddleware.go:97 +0x27f
github.com/hashicorp/vault/builtin/logical/database.(*databaseBackend).pathCredsCreateRead.func1(0xc4209b0c40, 0xc42037b250, 0x0, 0x4, 0xc42019ff68)
	/gopath/src/github.com/hashicorp/vault/builtin/logical/database/path_creds_create.go:84 +0x309
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc420408a80, 0xc4209b0c40, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:231 +0x453
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc4202e72c0, 0xc4209b0c40, 0x0, 0x0, 0x6000000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:395 +0x673
github.com/hashicorp/vault/vault.(*Router).Route(0xc4202e72c0, 0xc4209b0c40, 0xc4209b0c40, 0xc4204a1950, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/router.go:281 +0x3a
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc4200be000, 0xc4209b0c40, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:191 +0xa7a
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc4200be000, 0xc4209b0c40, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/request_handling.go:45 +0xb6a
github.com/hashicorp/vault/http.request(0xc4200be000, 0x2dcc380, 0xc4209b0b60, 0xc42153f300, 0xc4209b0c40, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:211 +0x3c
github.com/hashicorp/vault/http.handleLogical.func1(0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/gopath/src/github.com/hashicorp/vault/http/logical.go:122 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc42035d2a0, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:1918 +0x44
github.com/hashicorp/vault/http.handleRequestForwarding.func1(0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:161 +0x1ca
net/http.HandlerFunc.ServeHTTP(0xc42035d2c0, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42037e1e0, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:2254 +0x130
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/gopath/src/github.com/hashicorp/vault/http/help.go:22 +0x166
net/http.HandlerFunc.ServeHTTP(0xc42035d300, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:1918 +0x44
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/gopath/src/github.com/hashicorp/vault/http/cors.go:32 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc42035d340, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:1918 +0x44
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/gopath/src/github.com/hashicorp/vault/http/handler.go:88 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc42035d360, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc4202c8680, 0x2dcc380, 0xc4209b0b60, 0xc42153f300)
	/goroot/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42097a6e0, 0x2dcd780, 0xc4208d7140)
	/goroot/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2720 +0x288

goroutine 4911 [IO wait]:
internal/poll.runtime_pollWait(0x7fdc5342bae8, 0x72, 0x0)
	/goroot/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42038a818, 0x72, 0xffffffffffffff00, 0x2dc04c0, 0x2db5b60)
	/goroot/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42038a818, 0xc42155f000, 0x400, 0x400)
	/goroot/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42038a800, 0xc42155f000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42038a800, 0xc42155f000, 0x400, 0x400, 0x455030615301731, 0x74616572470e1308, 0x6f646e6f4c207265)
	/goroot/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420082710, 0xc42155f000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc420d6b050, 0x7fdc533c7040, 0xc420082710, 0x5, 0xc420082710, 0x4)
	/goroot/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420507500, 0x1f9ae17, 0xc420507620, 0xc38a96ed563aaa79)
	/goroot/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420507500, 0xc420d6b301, 0x1, 0x1, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:1134 +0x110
net/http.(*connReader).backgroundRead(0xc420d6b2f0)
	/goroot/src/net/http/server.go:660 +0x62
created by net/http.(*connReader).startBackgroundRead
	/goroot/src/net/http/server.go:656 +0xd8

goroutine 5454 [runnable]:
net/http.(*conn).serve(0xc4209f9540, 0x2dcd840, 0xc42037e2d0)
	/goroot/src/net/http/server.go:1690
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2720 +0x288

...
``` 

CPU goes up for a while but RAM, network and disk usage remains normal. 
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
vault               160.14%               57.37MiB / 1.952GiB   2.57%               17.7MB / 53.6MB     2.13MB / 98.7MB     23
```

Host system info:
```
MacBook Pro (Retina, 15-inch, Mid 2015)
CPU: 2.5 GHz Intel Core i7
RAM: 16 GB 1600 MHz DDR3
Disk: 500.28 GB SATA SSD 
```

**Steps to Reproduce:**
1. Unseal vault
2. Ensure you have some credentials/roles/secrets populated in.
3. Run a test with ~ 300 API req/sec against API endpoint.
4. Check the logs after failure.

**Comment by jefferai** [comment]
This is something that is seen intermittently on the Golang issue tracker and usually has to do with some request for memory not being granted. What are the limits around your Docker instance? Usually it's some subset of your actual system RAM.

More broadly speaking this seems likely to be a running-container-on-OSX issue than anything specific to Vault.

**Comment by Constantin07** [comment]
@jefferai default - 2 GB of RAM. I don't have many entries in vault:
1 DB configuration (MongoDB), 6 roles, 6 credentials, 2 secrets and one token.

**Comment by briankassouf** [comment]
Are you able to reliably reproduce this issue? If so do you have a script you could share?

**Comment by Constantin07** [comment]
What I found is that if I don't include in the list of API resource to query any dynamic credentials paths - it works just fine. It works fine with static secrets as well.

Here is the script:
```python
#!/usr/bin/env python

import threading
import urllib2, ssl
import time

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

VAULT_ADDR = "https://vault.***.***:8200"
VAULT_TOKEN = "e0b9ce1-7728-cdb2-8502-99ad722e6133"

request_headers = {
    'X-Vault-Token': VAULT_TOKEN
}

start = time.time()
paths = [
    "https://vault.***.***:8200/v1/sys/health",
    "https://vault.***.***:8200/v1/sys/audit",
    "https://vault.***.***:8200/v1/secret/custom",
#    "https://vault.***.***:8200/v1/database/creds/mongodb.db.ro"
#    "https://vault.***.***:8200/v1/database/creds/mongodb.db.rw",

]

def fetch_url(url):
    request = urllib2.Request(url, headers=request_headers)
    urlHandler = urllib2.urlopen(request, context=ctx)
    html = urlHandler.read()
    #print "'%s\' fetched in %ss" % (url, (time.time() - start))

threads = [threading.Thread(target=fetch_url, args=(url,)) for url in 100 * paths]
for thread in threads:
    thread.start()
for thread in threads:
    thread.join()

print "Elapsed Time: %s" % (time.time() - start)

```

PS: you need to populate vault with content before running the script.

**Comment by jefferai** [comment]
When you say "any dynamic credentials paths" do you mean you have reproduced this outside of Mongo?

**Comment by Constantin07** [comment]
Hi @jefferai No, it's reproduced when the dynamic credentials generation paths for mongo is enabled (uncommented). By the way, I monitored the logs of mongo DB in another terminal and I don't see any errors or issues at all.

**Comment by jefferai** [comment]
Do you see the same behavior when running the OSX binary natively?
