### ISSUE TITLE
Panic when local Consul agent unreachable

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/vault#3427]
A panic is observed when Vault is started, but the local Consul agent is not reachable at the configured address.

**Environment:**

* Vault Version: v0.8.3
* Operating System/Architecture: Linux/AMD64

**Vault Config File:**

```
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = "true"
}
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
}
```

**Startup Log Output:**

It is important to note that this issue is caused **when the local Consul agent as defined in Vault's configuration is not running**. When this is true, simply starting `vault` should result in this erorr and panic:

```
Error detecting redirect address: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1061212]
```

**Expected Behavior:**

An error about lack of connectivity to the local Consul agent only

**Actual Behavior:**

Vault panicked after the error:

```
Error detecting redirect address: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1061212]

goroutine 1 [running]:
sync.(*RWMutex).Lock(0x0)
    /goroot/src/sync/rwmutex.go:93 +0x22
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc42037c140, 0xc42000e0e0, 0x1, 0x1, 0x0)
    /gopath/src/github.com/hashicorp/vault/command/server.go:481 +0x1d85
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc420302c80, 0xc420302c80, 0x27, 0x2cd56a8)
    /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
github.com/hashicorp/vault/cli.RunCustom(0xc42000e0d0, 0x2, 0x2, 0xc4203a0150, 0xc4200909b8)
    /gopath/src/github.com/hashicorp/vault/cli/main.go:46 +0x4b6
github.com/hashicorp/vault/cli.Run(0xc42000e0d0, 0x2, 0x2, 0x2589519)
    /gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x56
main.main()
    /gopath/src/github.com/hashicorp/vault/main.go:10 +0x63
```

**Steps to Reproduce:**

1. Ensure that Consul agent is NOT currently started and bound to configured address
2. Start `vault` with above configuration:
  ```
  $ ./vault server -config=$CONFIG_FILENAME
  ```

**Important Factoids:**

**References:**

**Comment by calvn** [comment]
I'm unable to repro, this is the error I get:

```
$ vault server -config /tmp/vault-config.hcl -log-level=trace
==> WARNING: mlock not supported on this system!

  An `mlockall(2)`-like syscall to prevent memory from being
  swapped to disk is not supported on this system. Running
  Vault on an mlockall(2) enabled system is much more secure.

Error detecting redirect address: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
Error initializing core: missing redirect address
```

```
$ vault version
Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
```

**Comment by jefferai** [comment]
@brianshumate What does `vault version` say for you?

**Comment by brianshumate** [comment]
@jefferai

```
./bin/vault version
Vault v0.8.3+ent ('02d9a02dfdd5b7a8becc4e67982a75782f948f58+CHANGES')
```

**Comment by jefferai** [comment]
This is an enterprise issue -- can you file on the enterprise side instead? Thanks!
