### ISSUE TITLE
Server panics when starting due to nil pointer dereference

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#382]
This happens when running vault 0.1.2, downloaded from the vault website, with an empty config file.

```
~/d/f/vault git:master ❯❯❯ /usr/bin/vault server -config /etc/vault/config.hcl -log-level=debug
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4bd6a2]

goroutine 1 [running]:
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc20807e090, 0xc20800a020, 0x3, 0x3, 0xc208044928)
        /Users/mitchellh/code/go/src/github.com/hashicorp/vault/command/server.go:99 +0x38b2
github.com/mitchellh/cli.(*CLI).Run(0xc208066c80, 0xc20801e5c0, 0x0, 0x0)
        /Users/mitchellh/code/go/src/github.com/mitchellh/cli/cli.go:100 +0x3ce
github.com/hashicorp/vault/cli.RunCustom(0xc20800a010, 0x4, 0x4, 0xc20803d410, 0xa606a0)
        /Users/mitchellh/code/go/src/github.com/hashicorp/vault/cli/main.go:44 +0x486
github.com/hashicorp/vault/cli.Run(0xc20800a010, 0x4, 0x4, 0x50dfb0)
        /Users/mitchellh/code/go/src/github.com/hashicorp/vault/cli/main.go:11 +0x53
main.main()
        /Users/mitchellh/code/go/src/github.com/hashicorp/vault/main.go:10 +0x6d

goroutine 2 [runnable]:
runtime.forcegchelper()
        /Users/mitchellh/code/3rdparty/go/src/runtime/proc.go:90
runtime.goexit()
        /Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /Users/mitchellh/code/3rdparty/go/src/runtime/mgc0.go:82
runtime.goexit()
        /Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /Users/mitchellh/code/3rdparty/go/src/runtime/malloc.go:712
runtime.goexit()
        /Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
os/signal.loop()
        /Users/mitchellh/code/3rdparty/go/src/os/signal/signal_unix.go:19
created by os/signal.init·1
        /Users/mitchellh/code/3rdparty/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
github.com/hashicorp/vault/command.func·010()
        /Users/mitchellh/code/go/src/github.com/hashicorp/vault/command/meta.go:197
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
        /Users/mitchellh/code/go/src/github.com/hashicorp/vault/command/meta.go:201 +0x51a
```

Here is some debug information that may be useful:
```
~/d/f/vault git:master ❯❯❯ ll /usr/bin/vault /etc/vault
-rwxr-xr-x 1 root root 14604968 Jun 30 15:15 /usr/bin/vault*

/etc/vault:
total 8
drw-r-xr-x   2 root root 4096 Jun 30 15:15 ./
drwxr-xr-x 116 root root 4096 Jun 30 15:15 ../
-rw-r--r--   1 root root    0 Jun 30 15:15 config.hcl
```
```
~/d/f/vault git:master ❯❯❯ uname -a
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by armon** [comment]
@BRMatt Can you check on master? I believe this is fixed already

**Comment by BRMatt** [comment]
Thanks, you're right - when I build master locally I get:

```
~/d/g/s/g/h/vault git:master ❯❯❯ ./bin/vault server -config /etc/vault/config.hcl
A physical backend must be specified
```
