### ISSUE TITLE
Vault client segfaults when parsing (invalid) subcommand containing spaces

### ISSUE THREAD

**Issue by zx8** [hashicorp/vault#3878]
```
$ vault version
Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')

$ vault 'foo bar'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25cbef7]

goroutine 1 [running]:
github.com/hashicorp/vault/command.printCommand(0x3d07440, 0xc4205ecf00, 0x2cf713a, 0x4, 0x0)
	/private/tmp/vault-20180128-17316-9o8y5g/src/github.com/hashicorp/vault/command/main.go:107 +0x37
github.com/hashicorp/vault/command.groupedHelpFunc.func1(0xc4207d1fb0, 0x7fff5fbfb5fe, 0x3)
	/private/tmp/vault-20180128-17316-9o8y5g/src/github.com/hashicorp/vault/command/main.go:75 +0x1d0
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201b7540, 0xc4201b7540, 0xc4206d6980, 0xc4202545a0)
	/private/tmp/vault-20180128-17316-9o8y5g/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:231 +0x410
github.com/hashicorp/vault/command.Run(0xc42000a090, 0x1, 0x1, 0x2622fb9)
	/private/tmp/vault-20180128-17316-9o8y5g/src/github.com/hashicorp/vault/command/main.go:47 +0x411
main.main()
	/private/tmp/vault-20180128-17316-9o8y5g/src/github.com/hashicorp/vault/main.go:10 +0x63
```

**Comment by calvn** [comment]
This was fixed upstream in https://github.com/mitchellh/cli/pull/69. The deps have been recently updated so this no longer occurs in master.
