### ISSUE TITLE
Nil pointer de-reference when querying LDAP

### ISSUE THREAD

**Issue by swsnider** [hashicorp/vault#410]
Ran vault auth -method=ldap username=ssnider, and got the following error (hostnames redacted):

```
Password (will be hidden):
Error making API request.

URL: PUT https://HOSTNAME:8200/v1/auth/ldap/login/ssnider
Code: 400. Errors:

* user is not member of any authorized group
```

I thought at first that I had some transient error in the ldap server I'm running against (it was working before) but when I tried a different command, it told me the vault was sealed, indicating that the server had restarted.

Server logs had this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7f69bc]

goroutine 23 [running]:
github.com/hashicorp/vault/vault.(*AESGCMBarrier).ReloadKeyring(0xc208054540, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:240 +0x5bc
github.com/hashicorp/vault/vault.(*Core).postUnseal(0xc208098000, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:1217 +0x2a2
github.com/hashicorp/vault/vault.(*Core).runStandby(0xc208098000, 0xc2082abf80, 0xc208326000)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:1346 +0x53c
created by github.com/hashicorp/vault/vault.(*Core).Unseal
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:926 +0xf12

goroutine 1 [chan receive, 25 minutes]:
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc2080cc000, 0xc20800a020, 0x2, 0x2, 0xc208042858)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/command/server.go:243 +0x369e
github.com/mitchellh/cli.(*CLI).Run(0xc208070160, 0xc20801d340, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/mitchellh/cli/cli.go:112 +0x5be
github.com/hashicorp/vault/cli.RunCustom(0xc20800a010, 0x3, 0x3, 0xc208082750, 0xbd0be0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/cli/main.go:44 +0x486
github.com/hashicorp/vault/cli.Run(0xc20800a010, 0x3, 0x3, 0x536810)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/cli/main.go:11 +0x53
main.main()
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/main.go:10 +0x6d

goroutine 5 [syscall, 25 minutes]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive, 25 minutes]:
github.com/hashicorp/vault/cli.func·033()
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/cli/commands.go:290 +0x52
created by github.com/hashicorp/vault/cli.makeShutdownCh
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/cli/commands.go:293 +0x21f

goroutine 7 [semacquire, 25 minutes]:
sync.(*Cond).Wait(0xc2080cc0f0)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2080cc0c0, 0xc20807a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc208032068, 0xc20807a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/pipe.go:134 +0x5b
bufio.(*Scanner).Scan(0xc20809a000, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/scan.go:180 +0x688
github.com/hashicorp/vault/command.func·010()
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/command/meta.go:221 +0x3d
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/command/meta.go:224 +0x5f0

goroutine 8 [semacquire]:
sync.(*WaitGroup).Wait(0xc2304414a0)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/waitgroup.go:132 +0x169
github.com/samuel/go-zookeeper/zk.(*Conn).loop(0xc20803d5f0)
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:263 +0x7b3
github.com/samuel/go-zookeeper/zk.func·001()
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:168 +0x2c
created by github.com/samuel/go-zookeeper/zk.ConnectWithDialer
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:172 +0x5bb

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc20807c140, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20807c140, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20807c0e0, 0x0, 0x7f10e26a1f40, 0xc2482de870)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080320e0, 0xc2482de860, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x4e
github.com/hashicorp/vault/command/server.tcpKeepAliveListener.Accept(0xc2080320e0, 0x0, 0x0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/command/server/listener_tcp.go:35 +0x4c
crypto/tls.(*listener).Accept(0xc2082976a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/tls.go:46 +0x6b
net/http.(*Server).Serve(0xc20828c240, 0x7f10e26a8a30, 0xc2082976a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1728 +0x92
created by github.com/hashicorp/vault/command.(*ServerCommand).Run
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/command/server.go:220 +0x3178

goroutine 14 [select, 25 minutes]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc20800ac40)
	/Users/sethvargo/Development/go/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xf1
created by github.com/armon/go-metrics.NewInmemSignal
	/Users/sethvargo/Development/go/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x258

goroutine 199 [chan receive]:
github.com/hashicorp/vault/physical.(*ZookeeperHALock).monitorLock(0xc248c479a0, 0xc248bde840, 0xc248bde6c0)
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/physical/zookeeper.go:295 +0x63
created by github.com/hashicorp/vault/physical.(*ZookeeperHALock).Lock
	/Users/sethvargo/Development/go/src/github.com/hashicorp/vault/physical/zookeeper.go:258 +0x585

goroutine 13 [sleep]:
net.func·019()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/usr/local/Cellar/go/1.4.2/libexec/src/net/dnsclient_unix.go:269 +0x20c

goroutine 15 [sleep]:
github.com/armon/go-metrics.(*Metrics).collectStats(0xc208034960)
	/Users/sethvargo/Development/go/src/github.com/armon/go-metrics/metrics.go:67 +0x2c
created by github.com/armon/go-metrics.New
	/Users/sethvargo/Development/go/src/github.com/armon/go-metrics/start.go:61 +0xe8

goroutine 197 [IO wait]:
net.(*pollDesc).Wait(0xc239802ae0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc239802ae0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc239802a80, 0xc229218000, 0x4, 0x180000, 0x0, 0x7f10e26a1f40, 0xc23cee1290)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc23d888140, 0xc229218000, 0x4, 0x180000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
io.ReadAtLeast(0x7f10e26a8b40, 0xc23d888140, 0xc229218000, 0x4, 0x180000, 0x4, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:298 +0xf1
io.ReadFull(0x7f10e26a8b40, 0xc23d888140, 0xc229218000, 0x4, 0x180000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:316 +0x6d
github.com/samuel/go-zookeeper/zk.(*Conn).recvLoop(0xc20803d5f0, 0x7f10e26a8330, 0xc23d888140, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:523 +0x1b6
github.com/samuel/go-zookeeper/zk.func·003()
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:255 +0x5f
created by github.com/samuel/go-zookeeper/zk.(*Conn).loop
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:261 +0x7a3

goroutine 196 [select]:
github.com/samuel/go-zookeeper/zk.(*Conn).sendLoop(0xc20803d5f0, 0x7f10e26a8330, 0xc23d888140, 0xc2165c6060, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:459 +0xce9
github.com/samuel/go-zookeeper/zk.func·002()
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:248 +0x5a
created by github.com/samuel/go-zookeeper/zk.(*Conn).loop
	/Users/sethvargo/Development/go/src/github.com/samuel/go-zookeeper/zk/conn.go:251 +0x6c6

goroutine 187 [IO wait]:
net.(*pollDesc).Wait(0xc2083c8840, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083c8840, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083c87e0, 0xc246df369c, 0x2, 0x2, 0x0, 0x7f10e26a1f40, 0xc246df38d0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc23d8881e0, 0xc246df369c, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
io.ReadAtLeast(0x7f10e26a8b40, 0xc23d8881e0, 0xc246df369c, 0x2, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:298 +0xf1
io.ReadFull(0x7f10e26a8b40, 0xc23d8881e0, 0xc246df369c, 0x2, 0x2, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:316 +0x6d
gopkg.in/asn1-ber%2ev1.ReadPacket(0x7f10e26a8b40, 0xc23d8881e0, 0xc23d8881e0, 0x0, 0x0)
	/Users/sethvargo/Development/go/src/gopkg.in/asn1-ber.v1/ber.go:186 +0xaf
github.com/go-ldap/ldap.(*Conn).reader(0xc2083bf200)
	/Users/sethvargo/Development/go/src/github.com/go-ldap/ldap/conn.go:334 +0x127
created by github.com/go-ldap/ldap.(*Conn).Start
	/Users/sethvargo/Development/go/src/github.com/go-ldap/ldap/conn.go:105 +0x32

goroutine 188 [select]:
github.com/go-ldap/ldap.(*Conn).processMessages(0xc2083bf200)
	/Users/sethvargo/Development/go/src/github.com/go-ldap/ldap/conn.go:276 +0x9cb
created by github.com/go-ldap/ldap.(*Conn).Start
	/Users/sethvargo/Development/go/src/github.com/go-ldap/ldap/conn.go:106 +0x4c
```

**Comment by swsnider** [comment]
I'm running 0.2.0.rc1, because my ldap groups all have hyphens.

**Comment by armon** [comment]
Pushed bff57f8 which guards against this nil pointer dereference. There is definitely some deeper issue with ZK, since this is not coming from the LDAP backend at all. Instead a key which should presumably always exist is coming back as nil causing the panic. This will avoid the panic, but the fact that this is happening at all means something is wrong with the ZK backend.
