### ISSUE TITLE
Error running v0.10 under WASL (Ubuntu on Win10)

### ISSUE THREAD

**Issue by coverband** [hashicorp/vault#4339]
**Environment:**
* Vault Version:
0.10
* Operating System/Architecture:
Ubuntu 16.04 LTS (running in WASL)

**Vault Config File:**
n/a

**Startup Log Output:**

```text
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x22ced55, 0x17)
        /goroot/src/runtime/panic.go:616 +0x81
runtime.netpoll(0xca8e323d00, 0xc400000000)
        /goroot/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /goroot/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /goroot/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /goroot/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable, locked to thread]:
github.com/hashicorp/vault/vendor/github.com/denisenkom/go-mssqldb.init()
        /gopath/src/github.com/hashicorp/vault/vendor/github.com/denisenkom/go-mssqldb/cp949.go:17310 +0x29f

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /goroot/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /goroot/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /goroot/src/os/signal/signal_unix.go:28 +0x41
```

**Expected Behavior:**
Usual vault behavior as was observed with 0.9.5

**Actual Behavior:**
vault fails to initiate and shows fatal error

**Steps to Reproduce:**
run vault binary

**Important Factoids:**
An attempt was made to replace a working copy of vault 0.9.5 with the updated version.

**References:**
n/a

**Comment by jefferai** [comment]
Cannot reproduce:
```
jeff@Kraken:~$ file vault
vault: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
jeff@Kraken:~$ ./vault version
Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
jeff@Kraken:~$ ./vault server -dev
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
                 Storage: inmem
                 Version: Vault v0.10.0
             Version Sha: 5dd7f25f5c4b541f2da62d70075b6f82771a650d

WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
and starts unsealed with a single unseal key. The root token is already
authenticated to the CLI, so you can immediately begin using Vault.

You may need to set the following environment variable:

    $ export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: hqtwvBbdRPG96BpBLOphGZXoIwBT0BovjKaePtk+xaE=
Root Token: 407b05f3-8c9a-bb6e-3bc0-af2a9dfbaf63

Development mode should NOT be used in production installations!

==> Vault server started! Log data will stream in below:

2018-04-12T10:06:58.890-0400 [INFO ] core: security barrier not initialized
2018-04-12T10:06:58.890-0400 [INFO ] core: security barrier initialized: shares=1 threshold=1
2018-04-12T10:06:58.890-0400 [INFO ] core: post-unseal setup starting
2018-04-12T10:06:58.898-0400 [INFO ] core: loaded wrapping token key
2018-04-12T10:06:58.898-0400 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018-04-12T10:06:58.899-0400 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018-04-12T10:06:58.899-0400 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018-04-12T10:06:58.899-0400 [INFO ] core: successfully mounted backend: type=system path=sys/
2018-04-12T10:06:58.899-0400 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018-04-12T10:06:58.900-0400 [INFO ] core: restoring leases
2018-04-12T10:06:58.901-0400 [INFO ] rollback: starting rollback manager
2018-04-12T10:06:58.901-0400 [INFO ] identity: entities restored
2018-04-12T10:06:58.901-0400 [INFO ] identity: groups restored
2018-04-12T10:06:58.901-0400 [INFO ] core: post-unseal setup complete
2018-04-12T10:06:58.901-0400 [INFO ] core: root token generated
2018-04-12T10:06:58.901-0400 [INFO ] core: pre-seal teardown starting
2018-04-12T10:06:58.901-0400 [INFO ] core: cluster listeners not running
2018-04-12T10:06:58.901-0400 [INFO ] expiration: lease restore complete
2018-04-12T10:06:58.911-0400 [INFO ] rollback: stopping rollback manager
2018-04-12T10:06:58.911-0400 [INFO ] core: pre-seal teardown complete
2018-04-12T10:06:58.911-0400 [INFO ] core: vault is unsealed
2018-04-12T10:06:58.911-0400 [INFO ] core: post-unseal setup starting
2018-04-12T10:06:58.911-0400 [INFO ] core: loaded wrapping token key
2018-04-12T10:06:58.911-0400 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018-04-12T10:06:58.911-0400 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018-04-12T10:06:58.911-0400 [INFO ] core: successfully mounted backend: type=system path=sys/
2018-04-12T10:06:58.911-0400 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018-04-12T10:06:58.911-0400 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018-04-12T10:06:58.912-0400 [INFO ] core: restoring leases
2018-04-12T10:06:58.912-0400 [INFO ] rollback: starting rollback manager
2018-04-12T10:06:58.912-0400 [INFO ] identity: entities restored
2018-04-12T10:06:58.912-0400 [INFO ] identity: groups restored
2018-04-12T10:06:58.912-0400 [INFO ] core: post-unseal setup complete
2018-04-12T10:06:58.912-0400 [INFO ] expiration: lease restore complete
2018-04-12T10:06:58.915-0400 [INFO ] core: mount tuning of options: path=secret/ options=map[version:2]
2018-04-12T10:06:58.916-0400 [INFO ] secrets.kv.kv_aaa67d0e: collecting keys to upgrade
2018-04-12T10:06:58.916-0400 [INFO ] secrets.kv.kv_aaa67d0e: done collecting keys: num_keys=1
2018-04-12T10:06:58.916-0400 [INFO ] secrets.kv.kv_aaa67d0e: upgrading keys finished
```

**Comment by coverband** [comment]
I'm still having the same issue, after removing/reinstalling/etc. Any suggestions? Note that the "no repro" did not mention installing over prior vault instance.

**Comment by jjuel** [comment]
It happens every time on my machine as well under the WSL. Although when I do it I am behind a proxy. Not sure if there is a setting for vault with a proxy or not. So I guess not sure if this is a proxy issue or if it is a WSL issue.

**Comment by conanbee** [comment]
i have the same issue also. It happens on my WSL even only running vault binary.


  [16:59:08][root@GH-9NCJ4H2:/tmp]# vault
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x22d8ff6, 0x17)
        /goroot/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x2386cf022f600, 0xc400000000)
        /goroot/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /goroot/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /goroot/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /goroot/src/runtime/proc.go:1193 +0x76

goroutine 1 [syscall, locked to thread]:
regexp.makeOnePass(0xc420273830, 0xc420273830)
        /goroot/src/regexp/onepass.go:309 +0x233
regexp.compileOnePass(0xc4202737d0, 0xc4202737d0)
        /goroot/src/regexp/onepass.go:502 +0x1b3
regexp.compile(0x23782b7, 0x434, 0xd4, 0x10, 0x1f2d160, 0xc42022de58)
        /goroot/src/regexp/regexp.go:186 +0xed
regexp.Compile(0x23782b7, 0x434, 0x1d25440, 0x358b801, 0xc4201e3020)
        /goroot/src/regexp/regexp.go:133 +0x41
regexp.MustCompile(0x23782b7, 0x434, 0x5)
        /goroot/src/regexp/regexp.go:238 +0x4d

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /goroot/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /goroot/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /goroot/src/os/signal/signal_unix.go:28 +0x41

**Comment by coverband** [comment]
@conanbee Did you have a previously working version (like me), or did it fail when attempting to use it the very first time?

**Comment by coverband** [comment]
As of  Windows Version 10.0.16299.371 this is now working for me. I haven't changed anything except for upgrading Win10 to 1709. Although I regularly run sudo apt-get upgrade, I think it was fixed on the Windows side.

**Comment by jefferai** [comment]
Glad it's fixed! I think I was on 1709 before which might be why I didn't see it.
