### ISSUE TITLE
Passing in an array of policies to userpass panics

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#478]
```
2015/07/31 11:22:11 [INFO] core: enabled credential backend 'userpass/' type: userpass
2015/07/31 11:22:48 http: panic serving 127.0.0.1:62513: error reading policies: '' expected type 'string', got unconvertible type '[]interface {}'
goroutine 13 [running]:
net/http.func·011()
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/hashicorp/vault/logical/framework.(*FieldData).GetOk(0xc20809ebe0, 0x832010, 0x8, 0x0, 0x0, 0xf60000000000e601)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/logical/framework/field_data.go:49 +0x2b7
github.com/hashicorp/vault/logical/framework.(*FieldData).Get(0xc20809ebe0, 0x832010, 0x8, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/logical/framework/field_data.go:31 +0x1fd
github.com/hashicorp/vault/builtin/credential/userpass.(*backend).pathUserWrite(0xc20806a318, 0xc208116080, 0xc20809ebe0, 0x71ebc0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/builtin/credential/userpass/path_users.go:88 +0xe2
github.com/hashicorp/vault/builtin/credential/userpass.*backend.(github.com/hashicorp/vault/builtin/credential/userpass.pathUserWrite)·fm(0xc208116080, 0xc20809ebe0, 0x803be0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/builtin/credential/userpass/path_users.go:33 +0x4d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc208136240, 0xc208116080, 0x28, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/logical/framework/backend.go:126 +0x813
github.com/hashicorp/vault/vault.(*Router).Route(0xc20811a020, 0xc208116080, 0x0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/router.go:208 +0xac1
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc2080c4640, 0xc208116080, 0x0, 0x0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:420 +0x811
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc2080c4640, 0xc208116080, 0x0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:362 +0x452
github.com/hashicorp/vault/http.request(0xc2080c4640, 0xd2d088, 0xc208084280, 0xc208050820, 0xc208116080, 0x7e8720, 0x4)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/http/handler.go:78 +0x32
github.com/hashicorp/vault/http.func·002(0xd2d088, 0xc208084280, 0xc208050820)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/http/logical.go:65 +0x53f
net/http.HandlerFunc.ServeHTTP(0xc20809e870, 0xd2d088, 0xc208084280, 0xc208050820)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2080a0360, 0xd2d088, 0xc208084280, 0xc208050820)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0xd2d088, 0xc208084280, 0xc208050820)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc2081141e0, 0xd2d088, 0xc208084280, 0xc208050820)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20806c3c0, 0xd2d088, 0xc208084280, 0xc208050820)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20816c780)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
2015/07/31 11:22:48 http: panic serving 127.0.0.1:62514: error reading policies: '' expected type 'string', got unconvertible type '[]interface {}'
goroutine 37 [running]:
net/http.func·011()
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/hashicorp/vault/logical/framework.(*FieldData).GetOk(0xc20809ef60, 0x832010, 0x8, 0x0, 0x0, 0x6f0000000000e601)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/logical/framework/field_data.go:49 +0x2b7
github.com/hashicorp/vault/logical/framework.(*FieldData).Get(0xc20809ef60, 0x832010, 0x8, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/logical/framework/field_data.go:31 +0x1fd
github.com/hashicorp/vault/builtin/credential/userpass.(*backend).pathUserWrite(0xc20806a318, 0xc208116300, 0xc20809ef60, 0x71ebc0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/builtin/credential/userpass/path_users.go:88 +0xe2
github.com/hashicorp/vault/builtin/credential/userpass.*backend.(github.com/hashicorp/vault/builtin/credential/userpass.pathUserWrite)·fm(0xc208116300, 0xc20809ef60, 0x803be0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/builtin/credential/userpass/path_users.go:33 +0x4d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc208136240, 0xc208116300, 0x28, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/logical/framework/backend.go:126 +0x813
github.com/hashicorp/vault/vault.(*Router).Route(0xc20811a020, 0xc208116300, 0x0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/router.go:208 +0xac1
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc2080c4640, 0xc208116300, 0x0, 0x0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:420 +0x811
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc2080c4640, 0xc208116300, 0x0, 0x0, 0x0)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/vault/core.go:362 +0x452
github.com/hashicorp/vault/http.request(0xc2080c4640, 0xd2d088, 0xc208085400, 0xc208051110, 0xc208116300, 0x7e8720, 0x4)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/http/handler.go:78 +0x32
github.com/hashicorp/vault/http.func·002(0xd2d088, 0xc208085400, 0xc208051110)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/http/logical.go:65 +0x53f
net/http.HandlerFunc.ServeHTTP(0xc20809e870, 0xd2d088, 0xc208085400, 0xc208051110)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2080a0360, 0xd2d088, 0xc208085400, 0xc208051110)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0xd2d088, 0xc208085400, 0xc208051110)
    /Users/sethvargo/Development/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc2081141e0, 0xd2d088, 0xc208085400, 0xc208051110)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20806c3c0, 0xd2d088, 0xc208085400, 0xc208051110)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080850e0)
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
```
1. Enable user-pass auth
2. Create user with JSON policy like this:
   
   ``` json
   policies: ["a", "b"]
   ```
   
   The "correct" way to do this is with CSV:
   
   ``` json
     policies: "a,b"
   ```
   
   But I think the array approach should still work or at least not panic and kill Vault.

**Comment by ctennis** [comment]
The panic portion of this should be fixed with https://github.com/hashicorp/vault/pull/503
