### ISSUE TITLE
Postgresql DB backend nil-interface panics when revocation_statements is not present

### ISSUE THREAD

**Issue by harrisjoseph** [hashicorp/vault#4963]
**Describe the bug**
Using the postgres db backend - when a role is defined without `revocation_statements`, the server panics when trying to revoke a credential due to a nil interface where a string is expected.

See `revocationSQL` var here:
https://github.com/hashicorp/vault/blob/v0.10.3/builtin/logical/postgresql/secret_creds.go#L107
There seems to be some more explicit conversion here:
https://github.com/hashicorp/vault/blob/v0.10.3/builtin/logical/database/secret_creds.go#L114

**To Reproduce**
1 . Enable DB secrets backend with terraform.
2. Create role without revocation_statements
```hcl
resource "vault_mount" "db" {
  path                      = "database"
  type                      = "database"
  description               = "Database secrets backend"
  default_lease_ttl_seconds = 1800
  max_lease_ttl_seconds     = 43200
}

resource "vault_database_secret_backend_connection" "name_of_backend" {
  backend       = "${vault_mount.db.path}"
  name          = "name_of_backend"
  allowed_roles = ["*"]

  postgresql {
    connection_url = "postgresql://user:pass@my-beloved-db.internet.com:5432/database"
  }
}

resource "vault_database_secret_backend_role" "role" {
  backend             = "${vault_mount.db.path}"
  name                = "role"
  db_name             = "${vault_database_secret_backend_connection.name_of_backend.name}"
  creation_statements = "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO \"{{name}}\";"
  default_ttl         = 1800
  max_ttl             = 43200
}
```
3. Create a login - `vault read database/creds/role`
4. Server will panic when trying to revoke token
5. This prevents deletion of the backend, and after token expiry period servers fail immediately after unseal - as the server retries revocation immediately on startup.
```
panic: interface conversion: interface {} is nil, not []string
 goroutine 816 [running]:
github.com/hashicorp/vault/builtin/logical/database.(*databaseBackend).secretCredsRevoke.func1(0x2586340, 0xc4205ccb00, 0xc4200b2360, 0xc4207d3720, 0x0, 0x0, 0x0)
    /gopath/src/github.com/hashicorp/vault/builtin/logical/database/secret_creds.go:114 +0x7e8
github.com/hashicorp/vault/logical/framework.(*Secret).HandleRevoke(0xc420619860, 0x2586340, 0xc4205ccb00, 0xc4200b2360, 0xc4200b22f8, 0xc42074d201, 0xc400000001)
    /gopath/src/github.com/hashicorp/vault/logical/framework/secret.go:87 +0x9a
github.com/hashicorp/vault/logical/framework.(*Backend).handleRevokeRenew(0xc42074d1e0, 0x2586340, 0xc4205ccb00, 0xc4200b2360, 0x396335345ddc2e27, 0x6635312d37626538, 0xc420611988)
    /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:394 +0x1fb
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc42074d1e0, 0x2586340, 0xc4205ccb00, 0xc4200b2360, 0x0, 0x0, 0x0)
    /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:169 +0x6fb
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc42059a100, 0x2586340, 0xc4205ccb00, 0xc4200b2360, 0x410600, 0x0, 0x22e0000, 0x0, 0x0)
    /gopath/src/github.com/hashicorp/vault/vault/router.go:523 +0x7c2
github.com/hashicorp/vault/vault.(*Router).Route(0xc42059a100, 0x2586340, 0xc4205ccb00, 0xc4200b2360, 0xc420611d78, 0xc420611dc0, 0x19de3e1)
    /gopath/src/github.com/hashicorp/vault/vault/router.go:378 +0x4e
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeEntry(0xc4206da300, 0xc42086ef30, 0x38, 0xc42086ef30)
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:1092 +0x1c7
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeCommon(0xc4206da300, 0xc4209381c0, 0x38, 0x0, 0x0, 0x0)
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:510 +0x491
github.com/hashicorp/vault/vault.(*ExpirationManager).Revoke(0xc4206da300, 0xc4209381c0, 0x38, 0x0, 0x0)
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:489 +0x112
github.com/hashicorp/vault/vault.(*ExpirationManager).expireID(0xc4206da300, 0xc4209381c0, 0x38)
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:1066 +0x1ce
github.com/hashicorp/vault/vault.(*ExpirationManager).updatePendingInternal.func1()
    /gopath/src/github.com/hashicorp/vault/vault/expiration.go:1031 +0x3f
created by time.goFunc
    /goroot/src/time/sleep.go:172 +0x44
```

**Expected behavior**
* DB backend Handles nil interface in role config safely / doesn't allow invalid config to be written
* Vault doesn't attempt to revoke token when revocation statement is not present. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.3
* Vault CLI Version (retrieve with `vault version`): v0.10.3
* Server Operating System/Architecture: Official vault docker image (vault@sha256:af586d7f0ceb5b278673ef655bb688d299b031d07abbe157542011eeda48013e)
* Running in k8s - HA mode with dynamodb backend
* Terraform v0.11.7
  * provider.aws v1.23.0
  * provider.github v1.1.0
  * provider.vault v1.1.0

Vault server configuration file(s):

```hcl
ui = true

listener "tcp" {
    address                         = "[::]:8200"
    tls_cert_file                   = "/vault/tls/server.crt"
    tls_key_file                    = "/vault/tls/server.key"
    tls_prefer_server_cipher_suites = true
}

  storage "dynamodb" {
    ha_enabled    = "true"
    region        = "region"
    table         = "{table-name}"
}
```

**Comment by briankassouf** [comment]
This has already been fixed by #4850 and will be in the next release
