### ISSUE TITLE
Go panic at Vault startup, when using bad JSON

### ISSUE THREAD

**Issue by mafrosis** [hashicorp/vault#5401]
**Describe the bug**
Go panic at Vault startup, when passing invalid JSON as GCP credentials for `seal "gcpckms"`

**To Reproduce**
Use a config such as:
```
seal "gcpckms" {
  credentials = "/etc/vault/data/key.json"
}
```

Where the content of `key.json` is base64-encoded JSON :)

**Expected behavior**
No crash. A firm warning of silly behaviour.

**Environment:**
* `Vault v0.11.1+ent ('cad34697de2e7116f3c0f037cf17df1d0c535523')`
* Docker alpine on GKE

Vault server configuration file(s):

```hcl
api_addr     = "https://222.222.222.222:8200"
cluster_addr = "https://10.171.0.1:8201"
cluster_name = "gcp"

ui = true

storage "consul" {
	address = "10.171.0.2:8500"
	path = "vault/"
}

seal "gcpckms" {
  credentials = "/etc/vault/data/key.json"
  project     = "vault-1234567678900"
  region      = "australia-southeast1"
  key_ring    = "XXX"
  crypto_key  = "XXX"
}

listener "tcp" {
	address       = "0.0.0.0:8200"
	tls_cert_file = "/etc/vault/tls/vault.crt"
	tls_key_file  = "/etc/vault/tls/vault.key"

	tls_disable_client_certs = false
}
```

**Additional context**
The panic log:

```
/ # docker-entrypoint.sh server -log-level=trace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe600c4]

goroutine 1 [running]:
github.com/hashicorp/vault/vendor/golang.org/x/oauth2/jwt.jwtSource.Token(0x2be51a0, 0xc420072ba0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vendor/golang.org/x/oauth2/jwt/jwt.go:89 +0x64
github.com/hashicorp/vault/vendor/golang.org/x/oauth2.(*reuseTokenSource).Token(0xc42000b620, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vendor/golang.org/x/oauth2/oauth2.go:285 +0xb3
github.com/hashicorp/vault/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0xc420072bd0, 0xc420282500, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vendor/golang.org/x/oauth2/transport.go:48 +0x71
net/http.send(0xc420282500, 0x2bc8f20, 0xc420072bd0, 0x0, 0x0, 0x0, 0xc42000c308, 0x0, 0xc4206648a0, 0x1)
	/goroot/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc420072c00, 0xc420282500, 0x0, 0x0, 0x0, 0xc42000c308, 0x0, 0x1, 0x0)
	/goroot/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc420072c00, 0xc420282500, 0x2929ba6, 0xf, 0x403ba60)
	/goroot/src/net/http/client.go:615 +0x28d
github.com/hashicorp/vault/vendor/google.golang.org/api/gensupport.SendRequest(0x0, 0x0, 0xc420072c00, 0xc420282500, 0xc420664c80, 0x0, 0xc420282500)
	/gopath/src/github.com/hashicorp/vault/vendor/google.golang.org/api/gensupport/send.go:43 +0x254
github.com/hashicorp/vault/vendor/google.golang.org/api/cloudkms/v1.(*ProjectsLocationsKeyRingsCryptoKeysGetCall).doRequest(0xc420664e58, 0x2915078, 0x4, 0x0, 0xc420664d58, 0x406e0d)
	/gopath/src/github.com/hashicorp/vault/vendor/google.golang.org/api/cloudkms/v1/cloudkms-gen.go:2923 +0x48f
github.com/hashicorp/vault/vendor/google.golang.org/api/cloudkms/v1.(*ProjectsLocationsKeyRingsCryptoKeysGetCall).Do(0xc420664e58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vendor/google.golang.org/api/cloudkms/v1/cloudkms-gen.go:2935 +0x85
github.com/hashicorp/vault/vault/seal/gcpckms.(*GCPCKMSSeal).SetConfig(0xc420534200, 0xc4200729f0, 0xc420534200, 0xc420665078, 0x40fee9)
	/gopath/src/github.com/hashicorp/vault/vault/seal/gcpckms/gcpckms.go:145 +0x712
github.com/hashicorp/vault/command.(*ServerCommand).configureGCPCKMSSeal(0xc420644b40, 0xc4205c4000, 0xc4206658a8, 0xc4206653c8, 0x2bfc600, 0xc420551980, 0x2bfbfc0, 0xc4200774c0, 0x247a6e0, 0xffffffffffffffff, ...)
	/gopath/src/github.com/hashicorp/vault/command/server_seal_gcpckms.go:14 +0x75
github.com/hashicorp/vault/command.(*ServerCommand).configureSeal(0xc420644b40, 0xc4205c4000, 0xc4206658a8, 0xc4206653c8, 0x2bfc600, 0xc420551980, 0x2bfbfc0, 0xc4200774c0, 0x0, 0xc4206651c8, ...)
	/gopath/src/github.com/hashicorp/vault/command/server_seal.go:26 +0x3d7
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc420644b40, 0xc4200a4020, 0x4, 0x4, 0x0)
	/gopath/src/github.com/hashicorp/vault/command/server.go:479 +0xc81
github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4205b5cc0, 0xc4205b5cc0, 0xc420622a40, 0xc4206161e0)
	/gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
github.com/hashicorp/vault/command.RunCustom(0xc4200a4010, 0x5, 0x5, 0xc42025be50, 0xc420620ea0)
	/gopath/src/github.com/hashicorp/vault/command/main.go:170 +0x776
github.com/hashicorp/vault/command.Run(0xc4200a4010, 0x5, 0x5, 0xc42008e058)
	/gopath/src/github.com/hashicorp/vault/command/main.go:81 +0x48
main.main()
	/gopath/src/github.com/hashicorp/vault/main.go:10 +0x63
/ # command terminated with exit code 2
```

**Comment by calvn** [comment]
Thanks for the report! We have a fix pending review that should make it into the next release.
