### ISSUE TITLE
Unexpected end of file when trying to seal the vault

### ISSUE THREAD

**Issue by richard-hulm** [hashicorp/vault#579]
Successfully logged in using the userpass HTTP api

Then tried to seal the vault over the HTTP API and the connection failed.

The logs had the following

```
Aug 28 16:38:03 [IP-REDACTED] vault: 2015/08/28 16:38:03 http: panic serving 172.31.37.158:39363: runtime error: invalid memory address or nil pointer dereference
Aug 28 16:38:03 [IP-REDACTED] vault: goroutine 1074 [running]:
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.func·011()
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1130 +0xbb
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*TokenStore).SaltID(0x0, 0xc20865af60, 0x24, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/token_store.go:233 +0x31
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*TokenStore).Lookup(0x0, 0xc20865af60, 0x24, 0x0, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/token_store.go:339 +0x1a6
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*Core).checkToken(0xc2080a8000, 0xe73cf0, 0x5, 0xeb29d0, 0x8, 0xc20865af60, 0x24, 0x0, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:563 +0x1c8
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*Core).Seal(0xc2080a8000, 0xc20865af60, 0x24, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:945 +0x1e1
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/http.func·022(0x7fc2df73e2e8, 0xc2080757c0, 0xc2084805b0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/http/sys_seal.go:25 +0xf5
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.HandlerFunc.ServeHTTP(0xc20803ae40, 0x7fc2df73e2e8, 0xc2080757c0, 0xc2084805b0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1265 +0x41
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.(*ServeMux).ServeHTTP(0xc2080fc360, 0x7fc2df73e2e8, 0xc2080757c0, 0xc2084805b0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1541 +0x17d
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/http.func·001(0x7fc2df73e2e8, 0xc2080757c0, 0xc2084805b0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.HandlerFunc.ServeHTTP(0xc2080fe1e0, 0x7fc2df73e2e8, 0xc2080757c0, 0xc2084805b0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1265 +0x41
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.serverHandler.ServeHTTP(0xc208064360, 0x7fc2df73e2e8, 0xc2080757c0, 0xc2084805b0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1703 +0x19a
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.(*conn).serve(0xc208075720)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1204 +0xb57
Aug 28 16:38:03 [IP-REDACTED] vault: created by net/http.(*Server).Serve
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1751 +0x35e
Aug 28 16:38:03 [IP-REDACTED] vault: 2015/08/28 16:38:03 http: panic serving 172.31.37.158:39364: runtime error: invalid memory address or nil pointer dereference
Aug 28 16:38:03 [IP-REDACTED] vault: goroutine 1075 [running]:
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.func·011()
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1130 +0xbb
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*TokenStore).SaltID(0x0, 0xc20865b0b0, 0x24, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/token_store.go:233 +0x31
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*TokenStore).Lookup(0x0, 0xc20865b0b0, 0x24, 0x0, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/token_store.go:339 +0x1a6
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*Core).checkToken(0xc2080a8000, 0xe73cf0, 0x5, 0xeb29d0, 0x8, 0xc20865b0b0, 0x24, 0x0, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:563 +0x1c8
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/vault.(*Core).Seal(0xc2080a8000, 0xc20865b0b0, 0x24, 0x0, 0x0)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:945 +0x1e1
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/http.func·022(0x7fc2df73e2e8, 0xc208074820, 0xc208480680)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/http/sys_seal.go:25 +0xf5
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.HandlerFunc.ServeHTTP(0xc20803ae40, 0x7fc2df73e2e8, 0xc208074820, 0xc208480680)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1265 +0x41
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.(*ServeMux).ServeHTTP(0xc2080fc360, 0x7fc2df73e2e8, 0xc208074820, 0xc208480680)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1541 +0x17d
Aug 28 16:38:03 [IP-REDACTED] vault: github.com/hashicorp/vault/http.func·001(0x7fc2df73e2e8, 0xc208074820, 0xc208480680)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/projects/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.HandlerFunc.ServeHTTP(0xc2080fe1e0, 0x7fc2df73e2e8, 0xc208074820, 0xc208480680)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1265 +0x41
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.serverHandler.ServeHTTP(0xc208064360, 0x7fc2df73e2e8, 0xc208074820, 0xc208480680)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1703 +0x19a
Aug 28 16:38:03 [IP-REDACTED] vault: net/http.(*conn).serve(0xc208075a40)
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1204 +0xb57
Aug 28 16:38:03 [IP-REDACTED] vault: created by net/http.(*Server).Serve
Aug 28 16:38:03 [IP-REDACTED] vault: /Users/armon/go/src/net/http/server.go:1751 +0x35e
```

**Comment by jefferai** [comment]
What version of Vault is this?

**Comment by richard-hulm** [comment]
Sorry, it's 0.2.0

On 28 August 2015 at 17:18, Jeff Mitchell <notifications@github.com> wrote:

> What version of Vault is this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/579#issuecomment-135823135>.
>



-- 

*Richard Hulm*

Junior Developer

*Crunch*



www.crunch.co.uk | @teamcrunch <https://twitter.com/teamcrunch> | +44 (0)
33 3311 8000

Unit 11, Hove Business Centre, Fonthill Road, Hove, BN3 6HA

Registered in England No. 06014477

--------------------------------------------------------------------------------------------------------------------------------

Let us say thank you - get a free month for every new client you refer to
Crunch <http://www.crunch.co.uk/client-referral-scheme>!
--------------------------------------------------------------------------------------------------------------------------------

This email and any files transmitted with it are confidential and intended
solely for the use of the addressee. If you have received this email in
error, please let us know by replying to the sender and immediately delete
this email. In these circumstances, the use, disclosure, distribution or
copying of this information is strictly prohibited.

**Comment by richard-hulm** [comment]
Sorry, it's 0.2.0

**Comment by jefferai** [comment]
Any chance you can try it with the latest code? 0.2.0 was a while back and many many things have been fixed and changed.

**Comment by richard-hulm** [comment]
Not currently, Don't have a go build environment handy. I restarted the vault service and it didn't happen the second/third time, thought it may be worth raising an issue in case the issue could be easily spotted in the codebase.

Will try updating next time a version is released, and will keep this ticket updated with any news

**Comment by jefferai** [comment]
I'll take a look in the code. That's a very well-tested path which is why it was surprising to me and I thought maybe it was something fixed since.

I can provide you with an updated build if that would be useful and if you tell me which platform you're on.

**Comment by richard-hulm** [comment]
Sure thing,

We're on 64bit Linux (CentOS 7 if that makes any difference)

We've had some similar looking crashes a couple of times now when trying to unseal, so if you could give us an updated version that would be great. Is there a 'proper' release coming up with the new changes?

Thanks,

**Comment by jefferai** [comment]
Hi Richard,

Here's a fresh build: https://www.dropbox.com/s/izrfdqds9y5tudz/vault_amd64?dl=0 -- I'll keep it up for a couple of days.

If you could send along traces of the crash when unsealing that would be great -- it'd be good to see if it really is the same issue.

There is a proper release coming, but not for a bit. There's a lot we're trying to put in there beforehand.

**Comment by richard-hulm** [comment]
Hi Jeff,

Thanks for that. I've updated our packaging step with that version of Vault, so will be getting results shortly. It was a fairly intermittent issue, so will keep you updated with any more stack traces I get, or resolve the issue if it doesn't happen again

Cheers,

**Comment by richard-hulm** [comment]
Seems to have been sorted! Thanks
