### ISSUE TITLE
"invalid memory address" when attempting to configure ldap auth backend

### ISSUE THREAD

**Issue by Poohblah** [hashicorp/vault#599]
Here are the steps I'm following:

```
[vagrant@ldap-centos-71 ~]$ vault auth -methods
Path    Type   Description
token/  token  token based credentials
[vagrant@ldap-centos-71 ~]$ vault auth-enable ldap
Successfully enabled 'ldap' at 'ldap'!
[vagrant@ldap-centos-71 ~]$ vault auth -methods
Path    Type   Description
ldap/   ldap   
token/  token  token based credentials
[vagrant@ldap-centos-71 ~]$ vault write auth/ldap/config url='ldaps://ldap.example.com:636'
Error writing data to auth/ldap/config: Put http://127.0.0.1:8200/v1/auth/ldap/config: EOF
```

And here is the log output.  The "panic" occurs when I'm attempting the "vault write" to auth/ldap/config:

```
[vagrant@ldap-centos-71 ~]$ vault server -dev
==> WARNING: Dev mode is enabled!

In this mode, Vault is completely in-memory and unsealed.
Vault is configured to only have a single unseal key. The root
token has already been authenticated with the CLI, so you can
immediately begin using the Vault CLI.

The only step you need to take is to set the following
environment variables:

    export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are reproduced below in case you
want to seal/unseal the Vault or play with authentication.

Unseal Key: 7c3b648e814108e7d6b86ce895dbd058f5c838f854ba57706e1d473cc9ad14fb
Root Token: ee74c01a-34c2-6b27-2db0-54dcbc902abb

==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: false
           Backend: inmem
        Listener 1: tcp (addr: "127.0.0.1:8200", tls: "disabled")

==> Vault server started! Log data will stream in below:

2015/09/08 18:41:16 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/09/08 18:41:16 [INFO] core: post-unseal setup starting
2015/09/08 18:41:16 [INFO] core: post-unseal setup complete
2015/09/08 18:41:16 [INFO] core: root token generated
2015/09/08 18:41:16 [INFO] core: pre-seal teardown starting
2015/09/08 18:41:16 [INFO] rollback: starting rollback manager
2015/09/08 18:41:16 [INFO] rollback: stopping rollback manager
2015/09/08 18:41:16 [INFO] core: pre-seal teardown complete
2015/09/08 18:41:16 [INFO] core: vault is unsealed
2015/09/08 18:41:16 [INFO] core: post-unseal setup starting
2015/09/08 18:41:16 [INFO] core: post-unseal setup complete
2015/09/08 18:41:16 [INFO] rollback: starting rollback manager
2015/09/08 18:42:41 [INFO] core: enabled credential backend 'ldap/' type: ldap
2015/09/08 18:43:20 http: panic serving 127.0.0.1:33234: runtime error: invalid memory address or nil pointer dereference
goroutine 31 [running]:
net/http.func·011()
	/Users/armon/go/src/net/http/server.go:1130 +0xbb
github.com/go-ldap/ldap.(*Conn).Close(0x0)
	/Users/armon/projects/go/src/github.com/go-ldap/ldap/conn.go:127 +0x7c
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).pathConfigWrite(0xc2080364e8, 0xc20805eb80, 0xc20815b560, 0xd31e00, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/builtin/credential/ldap/path_config.go:140 +0x642
github.com/hashicorp/vault/builtin/credential/ldap.*backend.(github.com/hashicorp/vault/builtin/credential/ldap.pathConfigWrite)·fm(0xc20805eb80, 0xc20815b560, 0xe73cf0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/builtin/credential/ldap/path_config.go:52 +0x4d
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc208094990, 0xc20805eb80, 0x28, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/logical/framework/backend.go:126 +0x813
github.com/hashicorp/vault/vault.(*Router).Route(0xc2080ba940, 0xc20805eb80, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/router.go:208 +0xac1
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc208096780, 0xc20805eb80, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:420 +0x811
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc208096780, 0xc20805eb80, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:362 +0x452
github.com/hashicorp/vault/http.request(0xc208096780, 0x7f2d078a9668, 0xc208158000, 0xc2081452b0, 0xc20805eb80, 0xe4b630, 0x4)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/http/handler.go:78 +0x32
github.com/hashicorp/vault/http.func·002(0x7f2d078a9668, 0xc208158000, 0xc2081452b0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/http/logical.go:65 +0x53f
net/http.HandlerFunc.ServeHTTP(0xc208059330, 0x7f2d078a9668, 0xc208158000, 0xc2081452b0)
	/Users/armon/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2080f92c0, 0x7f2d078a9668, 0xc208158000, 0xc2081452b0)
	/Users/armon/go/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0x7f2d078a9668, 0xc208158000, 0xc2081452b0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc2080bbc40, 0x7f2d078a9668, 0xc208158000, 0xc2081452b0)
	/Users/armon/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20803a9c0, 0x7f2d078a9668, 0xc208158000, 0xc2081452b0)
	/Users/armon/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208065ea0)
	/Users/armon/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/Users/armon/go/src/net/http/server.go:1751 +0x35e
```

(I'm not sure what's up with the references to the path `/Users/armon/...`. This looks like a path to the project directory on a developer's system. Should this information be leaking?)

I've been able to reproduce this issue a couple times with both dev servers and regular servers (with mlock system call disabled) in my CentOS 7 Vagrant boxes.

Oh, and also:

```
[vagrant@ldap-centos-71 ~]$ vault --version
Vault v0.2.0
```

**Comment by dylancanfield** [comment]
This is only a problem when the LDAP server specified by url does not respond to your request. When using "ldap.example.com", I can replicate the behavior. When connecting to a "real" LDAP server, I do not get an error.

The error message is a bit misleading, however, I am not sure that there is an actual bug here.

**Comment by Poohblah** [comment]
Dylan,

I think there's more to it than that.  I've been able to resolve this issue by specifying certain "real" directory servers in the "url" field, but I can reproduce this issue with our organization's Active Directory instance. I can verify that the vault server can contact the Active Directory server with a packet capture tool, so I think more digging is needed to pinpoint the cause of the issue.

Jay

**Comment by Poohblah** [comment]
Seems to only be a problem when talking to the LDAP server over SSL/TLS, even with `insecure_tls=true`, for instance:

```
[birdsnest ~][I]% vault write auth/ldap/config url='ldaps://ldap.my.org:636' insecure_tls=true
Error writing data to auth/ldap/config: Put http://127.0.0.1:8200/v1/auth/ldap/config: EOF
[birdsnest ~][I]% vault write auth/ldap/config url='ldap://ldap.my.org'
Success! Data written to: auth/ldap/config
```

**Comment by jefferai** [comment]
The panic looks like it's an issue with the underlying go-ldap connection being invalid when the SSL connection fails. IIRC, the `EOF` error message is a common one returned when the underlying Go TLS connection code encounters a failure during SSL/TLS setup. Not useful, but you're probably not seeing the better LDAP message because the error is coming before the LDAP handler is being invoked.

You may be interested in https://github.com/hashicorp/vault/issues/546 which may or may not help this issue, but is possibly relevant.

**Comment by Poohblah** [comment]
Thanks, @jefferai . I'm having a number of issues with the LDAP auth backend (e.g. https://github.com/hashicorp/vault/issues/596 and https://groups.google.com/forum/#!topic/vault-tool/Dt2jA8DJEe4), so I'm hoping that https://github.com/hashicorp/vault/issues/546 will help resolve those issues.

**Comment by horsehay** [comment]
I'm also having runtime error: invalid memory address or nil pointer dereference when the LDAP server is unavailable. Very confusing. I didn't realize what was going on until other apps that relied on LDAP started failing.

**Comment by jefferai** [comment]
I'm curious if people are having a better experience with 0.5, as we did update the underlying `go-ldap` dependency.

**Comment by jefferai** [comment]
If anyone is interested in working with me to debug this issue in the short term that would also be appreciated.

**Comment by wsh** [comment]
I'm encountering this same issue on 0.5.2.

**Comment by jefferai** [comment]
@wsh Can you provide a stack trace and configuration information? Thanks!

**Comment by wsh** [comment]
Sure thing.

`vault server -dev -log-level=debug`
`vault auth-enable ldap`

`vault write auth/ldap/config url="ldaps://my-server-here:636"` produces `Error writing data to auth/ldap/config: Put http://127.0.0.1:8200/v1/auth/ldap/config: EOF` in response and in the logs I see:

```
2016/04/18 16:40:12 http: panic serving 127.0.0.1:49216: runtime error: invalid memory address or nil pointer dereference
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc82009d480)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1389 +0xc1
panic(0xdeeee0, 0xc820012150)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/hashicorp/vault/vendor/github.com/go-ldap/ldap.(*Conn).Close(0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/vendor/github.com/go-ldap/ldap/conn.go:132 +0x6d
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).pathConfigWrite(0xc820326350, 0xc82009d580, 0xc8204d3660, 0x6010103, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/path_config.go:186 +0x9d2
github.com/hashicorp/vault/builtin/credential/ldap.(*backend).(github.com/hashicorp/vault/builtin/credential/ldap.pathConfigWrite)-fm(0xc82009d580, 0xc8204d3660, 0x0, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/builtin/credential/ldap/path_config.go:78 +0x42
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc8203248f0, 0xc82009d580, 0xc82009d580, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:189 +0x833
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc8202c88d0, 0xc82009d580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/vault/router.go:265 +0xb9f
github.com/hashicorp/vault/vault.(*Router).Route(0xc8202c88d0, 0xc82009d580, 0xc82009d580, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc8202d0000, 0xc82009d580, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/vault/core.go:540 +0x9c8
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc8202d0000, 0xc82009d580, 0x0, 0x0, 0x0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/vault/core.go:461 +0x7dc
github.com/hashicorp/vault/http.request(0xc8202d0000, 0x1c0dd90, 0xc820124000, 0xc8200f10a0, 0xc82009d580, 0x30, 0xc820227e90)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/http/handler.go:75 +0x2f
github.com/hashicorp/vault/http.handleLogical.func1(0x1c0dd90, 0xc820124000, 0xc8200f10a0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/http/logical.go:77 +0x608
net/http.HandlerFunc.ServeHTTP(0xc82000e7c0, 0x1c0dd90, 0xc820124000, 0xc8200f10a0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8202f4d80, 0x1c0dd90, 0xc820124000, 0xc8200f10a0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1910 +0x17d
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x1c0dd90, 0xc820124000, 0xc8200f10a0)
	/private/tmp/vault20160327-6159-2yvwhr/gopath/src/github.com/hashicorp/vault/http/help.go:18 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc82000e800, 0x1c0dd90, 0xc820124000, 0xc8200f10a0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc82009c480, 0x1c0dd90, 0xc820124000, 0xc8200f10a0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82009d480)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2137 +0x44e
```

Does that help? I've been running Vault for a little while at this point but am a total LDAP novice, so pardon any obvious oversights. :smile:

**Comment by jefferai** [comment]
Hi @wsh ,

I believe that this particular stack trace is actually something already resolved in `master` -- it's an error during testing of the configuration that is not being caught properly. If you can build `master` and try again I think you'll get a more descriptive error of the problem (and not a stack trace).

**Comment by wsh** [comment]
On master, it works as expected (well, other than not being able to get LDAP to verify my credentials, but I'll chalk that up to necessary config work on my part. :smile:

**Comment by jefferai** [comment]
Great!

I'm actually going to close this ticket as I am fairly certain that the fixed behavior was the original issue, too.

**Comment by Poohblah** [comment]
OP here. Looks like the original issue is no longer present in the most recent version available via the Arch Linux AUR.

```
vagrant@archlinux:~$ vault -version
Vault v0.5.2
```

**Comment by jefferai** [comment]
Great!
