### ISSUE TITLE
Allow users to pass in answers to CLI questions

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#7072]
# Description

In testing out Vault related to [this question](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/3zPZ0TklPS8/n0tyUgxzBAAJ), I found that even without Docker in the mix, if a `tls_key_file` requires a password, I'm unable to do it non-interactively. This seems like it could block users from automating Vault to spin up in situations where that file is encrypted - it's definitely blocking the forum user from using the Docker Vault.

# Steps to Reproduce

Generate a private key and be sure to enter a password.
```
openssl genrsa -des3 -out private.key 2048
```

Generate a certificate using that private key.
```
openssl req \
       -key private.key \
       -new \
       -x509 -days 365 -out tls.crt
```

Create a Vault configuration using that key and cert, something like:
```
storage "inmem" {}
disable_mlock = true
api_addr = "http://127.0.0.1:8200"
log_level = "debug"
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_cert_file = "/home/tbex/Documents/vault_configs/key-with-pass/tls.crt"
  tls_key_file = "/home/tbex/Documents/vault_configs/key-with-pass/private.key"
}
```

Run Vault and be interactively prompted to enter the private key's password. Observe that it, of course, succeeds:
```
$ vault server -config=/home/tbex/Documents/vault_configs/key-with-pass/private-key-tls-cert-test.hcl
Enter passphrase for /home/tbex/Documents/vault_configs/key-with-pass/private.key: 
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: debug
                   Mlock: supported: true, enabled: false
                 Storage: inmem
                 Version: Vault v1.2.0-beta1
             Version Sha: a640411471c20dc16394c14df2ee66e880bef26b

==> Vault server started! Log data will stream in below:
```

Attempt to pass in the password through conventional methods and observe a panic:
```
$ export PASSWORD=what-you-set

$ echo $PASSWORD | vault server -config=/home/tbex/Documents/vault_configs/key-with-pass/private-key-tls-cert-test.hcl
Enter passphrase for /home/tbex/Documents/vault_configs/key-with-pass/private.key: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5a6f90]

goroutine 72 [running]:
bufio.(*Reader).fill(0xc000525f58)
	/usr/local/go/src/bufio/bufio.go:100 +0xe0
bufio.(*Reader).ReadSlice(0xc000746f58, 0x7f8c2a568a0a, 0x1245401, 0x101000000000010, 0x0, 0x1000, 0xc000740000)
	/usr/local/go/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadBytes(0xc000746f58, 0x100a, 0x1000, 0xc000740000, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:434 +0x70
bufio.(*Reader).ReadString(...)
	/usr/local/go/src/bufio/bufio.go:474
github.com/mitchellh/cli.(*BasicUi).ask.func1(0xc0006e1d01, 0xc0005804e0, 0xc0006e1ce0, 0xc0006e1d40)
	/home/tbex/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/ui.go:83 +0xd6
created by github.com/mitchellh/cli.(*BasicUi).ask
	/home/tbex/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/ui.go:76 +0x243
```

**Comment by ncabatoff** [comment]
This is a dup of #3844.
