### ISSUE TITLE
Panic in AWS secrets engine when generating OpenAPI

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#7095]
I have noticed that if I run `./scripts/gen_openapi.sh` I receive this panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf20487]

goroutine 458 [running]:
github.com/hashicorp/vault/builtin/credential/aws.(*backend).upgrade(0xc00070a0b0, 0x3781680, 0xc000224540, 0x0, 0x0, 0xc000758700, 0x3f7799e520000000, 0x3f7799e520000000)
	/home/tbex/go/src/github.com/hashicorp/vault/builtin/credential/aws/path_role.go:379 +0x37
github.com/hashicorp/vault/builtin/credential/aws.(*backend).initialize.func1(0xc00070a0b0, 0x3781680, 0xc000224540, 0x0, 0x0, 0x37ceb60, 0xc0000a2960)
	/home/tbex/go/src/github.com/hashicorp/vault/builtin/credential/aws/path_role.go:352 +0xa0
created by github.com/hashicorp/vault/builtin/credential/aws.(*backend).initialize
	/home/tbex/go/src/github.com/hashicorp/vault/builtin/credential/aws/path_role.go:343 +0x1b7
```
I'm currently poking at the issue. We've worked on that area of code lately so I want to document this just in case it might indicate an issue with the beta we're currently in.

**Comment by tyrannosaurus-becks** [comment]
I've found when an `*logical.InitializationRequest` is provided during initialization, sometimes storage may be nil, which is the cause of the panic on line 378.

**Comment by tyrannosaurus-becks** [comment]
I'm also noting a second unexpected behavior. Despite this:
```
	// InitializeFunc is the callback, which if set, will be invoked via
	// Initialize() just after a plugin has been mounted.
	InitializeFunc InitializeFunc
```
I'm seeing that the method is not called right after `vault auth enable aws`, but rather when the engine is first called into (I believe) so we might want to update that comment.

**Comment by tyrannosaurus-becks** [comment]
I found the issue and a fix is forthcoming. It only effects the `openapi` endpoint so should not be a major concern for the beta.
