### ISSUE TITLE
Vault panic, invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by taleksandrv** [hashicorp/vault#7588]
**Describe the bug**

Vault server output log:

```
Oct 04 04:34:31  vault[11578]: 2019-10-04T04:34:31.827-0500 [WARN]  secrets.pki.pki_68aa7942.tidy: revoked entry is nil; tidying up since it is no longer useful for any server operations: serial=BLAH
Oct 04 04:34:31  vault[11578]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 04 04:34:31  vault[11578]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18e4669]
Oct 04 04:34:31  vault[11578]: goroutine 26764629 [running]:
Oct 04 04:34:31  vault[11578]: github.com/hashicorp/vault/builtin/logical/pki.(*backend).pathTidyWrite.func1.1(0x0, 0x0)
Oct 04 04:34:31  vault[11578]: /gopath/src/github.com/hashicorp/vault/builtin/logical/pki/path_tidy.go:161 +0x2b9
Oct 04 04:34:31  vault[11578]: github.com/hashicorp/vault/builtin/logical/pki.(*backend).pathTidyWrite.func1(0xc00f588780, 0xc13af79190, 0x4bfff01, 0xc0fbabcc80, 0x4e94914f0000, 0xc143510100)
Oct 04 04:34:31  vault[11578]: /gopath/src/github.com/hashicorp/vault/builtin/logical/pki/path_tidy.go:199 +0x170
Oct 04 04:34:31  vault[11578]: created by github.com/hashicorp/vault/builtin/logical/pki.(*backend).pathTidyWrite
Oct 04 04:34:31  vault[11578]: /gopath/src/github.com/hashicorp/vault/builtin/logical/pki/path_tidy.go:87 +0x290
```

**To Reproduce**
Vault PKI tidying up procedure https://github.com/hashicorp/vault/blob/1.1.3/website/source/api/secret/pki/index.html.md#tidy

**Expected behavior**
Vault server works without any panic errors.

**Environment:**
* Vault Server Version: 1.1.3

Vault server configuration file(s):

```hcl
storage "consul" {
    address       = "<consul address>:8500"
}

listener "tcp" {
    address     = "<vault>:8200"
}
```

**Additional context**
Looks like the same issue https://github.com/hashicorp/vault/issues/5931, but it fixed in the version 1.0.1

**Comment by ibogomazov** [comment]
@jefferai can this please be backported to v1.1.3?

**Comment by chrishoffman** [comment]
@ibogomazov Sorry we don't backport these patches to older releases.  This should be a pretty easy patch to integrate yourself, if necessary.
