### ISSUE TITLE
vault v0.4.0: runtime error with aws-sdk-go

### ISSUE THREAD

**Issue by Friz-zy** [hashicorp/vault#836]
Environment (perfect work for v0.3.1):
- [vault for linux amd64](https://releases.hashicorp.com/vault/0.4.0/vault_0.4.0_linux_amd64.zip)
- OS: aws linux, access to S3 via AWS IAM Role
- config:
```
backend "s3" {
  bucket = "test-bucket"
    # you should set AWS_ACCESS_KEY_ID environment variable!
      # you should set AWS_SECRET_ACCESS_KEY environment variable!
      # you can OPTIONAL set AWS_SESSION_TOKEN environment variable...
      region = "us-east-1"
  }

listener "tcp" {
  address = "0.0.0.0:8200"
    tls_disable = 1
  }


# for Linux systems that only use encrypted swap or do not use swap at all
disable_mlock = true
```

Log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb39340]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x130e360, 0x19, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b0
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:129 +0x74
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc820190b70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:86 +0x7b
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc820190ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:67 +0xf2
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc8201b65f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:182 +0x111
github.com/aws/aws-sdk-go/private/signer/v4.(*signer).sign(0xc8201e0c88, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:123 +0x3bf
github.com/aws/aws-sdk-go/private/signer/v4.Sign(0xc8201f4000)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:97 +0x1e7
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8201f4118, 0xc8201f4000)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc8201f4000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request.go:197 +0xce
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc8201f4000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request.go:207 +0x54
github.com/aws/aws-sdk-go/service/s3.(*S3).HeadBucket(0xc8200203a0, 0xc8200203a8, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/api.go:888 +0x4f
github.com/hashicorp/vault/physical.newS3Backend(0xc820190990, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/s3.go:82 +0xc68
github.com/hashicorp/vault/physical.NewBackend(0xc82018da50, 0x2, 0xc820190990, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/physical.go:75 +0x1db
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc82014c0c0, 0xc82000a1d0, 0x1, 0x1, 0xc8201aae58)
	/gopath/src/github.com/hashicorp/vault/command/server.go:108 +0xdeb
github.com/mitchellh/cli.(*CLI).Run(0xc82018e210, 0xc82018e210, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/mitchellh/cli/cli.go:112 +0x655
github.com/hashicorp/vault/cli.RunCustom(0xc82000a1c0, 0x2, 0x2, 0xc820199ef0, 0x2)
	/gopath/src/github.com/hashicorp/vault/cli/main.go:44 +0x452
github.com/hashicorp/vault/cli.Run(0xc82000a1c0, 0x2, 0x2, 0x9c1d00)
	/gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x4c
main.main()
	/gopath/src/github.com/hashicorp/vault/main.go:10 +0x60

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable, locked to thread]:
runtime.gopark(0x1484c00, 0xc820013d98, 0x1228600, 0x9, 0x16, 0x3)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.goparkunlock(0xc820013d98, 0x1228600, 0x9, 0x16, 0x3)
	/usr/local/go/src/runtime/proc.go:191 +0x54
runtime.chansend(0xdd3e40, 0xc820013d40, 0xc82001e70c, 0xc82001e601, 0x450629, 0x2)
	/usr/local/go/src/runtime/chan.go:197 +0x499
runtime.chansend1(0xdd3e40, 0xc820013d40, 0xc82001e70c)
	/usr/local/go/src/runtime/chan.go:92 +0x43
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:238 +0x2a9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 8 [runnable]:
github.com/hashicorp/vault/cli.makeShutdownCh.func1(0xc820013ce0, 0xc820013c80)
	/gopath/src/github.com/hashicorp/vault/cli/commands.go:294
created by github.com/hashicorp/vault/cli.makeShutdownCh
	/gopath/src/github.com/hashicorp/vault/cli/commands.go:299 +0x195

goroutine 9 [runnable]:
github.com/hashicorp/vault/command.(*Meta).FlagSet.func1(0xc82016ab80, 0xc82014c0e0)
	/gopath/src/github.com/hashicorp/vault/command/meta.go:186
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
	/gopath/src/github.com/hashicorp/vault/command/meta.go:190 +0x5e6
```

**Comment by jefferai** [comment]
Can you give more information about what you are doing when you see that panic?

I just created a new S3 bucket and `init`ed Vault in it, without hitting any issues.

**Comment by jefferai** [comment]
Log from my session:

```
$ vault server -config s3.hcl 
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: false
           Backend: s3
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
           Version: Vault v0.5.0-dev

==> Vault server started! Log data will stream in below:

2015/12/11 10:22:34 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/12/11 10:22:34 [INFO] core: post-unseal setup starting
2015/12/11 10:22:34 [INFO] core: mounted backend of type generic at logical/82076f3d-a562-8581-5bae-311c881bcd29/
2015/12/11 10:22:34 [INFO] core: mounted backend of type cubbyhole at logical/85e07df0-b40f-c389-044c-9aa94a0671b7/
2015/12/11 10:22:34 [INFO] core: mounted backend of type system at sys/
2015/12/11 10:22:34 [INFO] rollback: starting rollback manager
2015/12/11 10:22:35 [INFO] core: post-unseal setup complete
2015/12/11 10:22:35 [INFO] core: root token generated
2015/12/11 10:22:35 [INFO] core: pre-seal teardown starting
2015/12/11 10:22:35 [INFO] rollback: stopping rollback manager
2015/12/11 10:22:35 [INFO] core: pre-seal teardown complete
2015/12/11 10:22:43 [INFO] core: vault is unsealed
2015/12/11 10:22:43 [INFO] core: post-unseal setup starting
2015/12/11 10:22:43 [INFO] core: mounted backend of type generic at logical/82076f3d-a562-8581-5bae-311c881bcd29/
2015/12/11 10:22:43 [INFO] core: mounted backend of type cubbyhole at logical/85e07df0-b40f-c389-044c-9aa94a0671b7/
2015/12/11 10:22:43 [INFO] core: mounted backend of type system at sys/
2015/12/11 10:22:43 [INFO] rollback: starting rollback manager
2015/12/11 10:22:43 [INFO] core: post-unseal setup complete
```
and on the client end:
```
$ vault init -key-shares=1 -key-threshold=1
Key 1: b6499d2545bf1649cad170cd07eb8da8a317d30d4ab89b6f91ab2f6abf729dc3                                                          
Initial Root Token: 2d60755a-95df-e65c-2fb5-bda5db5a0028                                                                         
                                                                                                                                 
Vault initialized with 1 keys and a key threshold of 1. Please                                                                   
securely distribute the above keys. When the Vault is re-sealed,                                                                 
restarted, or stopped, you must provide at least 1 of these keys                                                                 
to unseal it again.                                                                                                              
                                                                                                                                 
Vault does not store the master key. Without at least 1 keys,                                                                    
your Vault will remain permanently sealed.                                                                                       
✔ ~/vaulttest [master|✔]                                                                                                         
10:22 $ vault unseal b6499d2545bf1649cad170cd07eb8da8a317d30d4ab89b6f91ab2f6abf729dc3                                            
Sealed: false                                                                                                                    
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
✔ ~/vaulttest [master|✔] 
10:22 $ vault auth 2d60755a-95df-e65c-2fb5-bda5db5a0028
Successfully authenticated!
token: 2d60755a-95df-e65c-2fb5-bda5db5a0028
token_duration: 0
token_policies: [root]
✔ ~/vaulttest [master|✔] 
10:22 $ vault write secret/foo bar=baz
Success! Data written to: secret/foo
```

**Comment by Friz-zy** [comment]
I used clean t2.micro ec2 instance in private VPC with IAM Role with only one policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::test-bucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::test-bucket/*"
            ]
        }
    ]
}
```
No init and unseal, just first execution: 'vault server -config /etc/vault/config.hcl'
How you set aws access tokens?

Up: You checked it with Vault v0.5.0-dev, right? I saw this bug only with 0.4.0

**Comment by jefferai** [comment]
I set up a user via IAM and gave them full permissions through IAM onto the S3 bucket.

Any chance you can test this with full permissions for S3 for that user, rather than a more restrictive policy? I wonder if this is a change in how the AWS SDK and/or API is handling permissions.

Vault v0.5.0-dev is at this point basically 0.4...very few changes, and non relating to AWS.

**Comment by bbasata** [comment]
I see the same panic using Vault v0.4.0 and an IAM role that allows `s3:*`.

**Comment by bbasata** [comment]
Related: https://github.com/aws/aws-sdk-go/issues/452

**Comment by bbasata** [comment]
Related terraform fix: https://github.com/hashicorp/terraform/pull/4024

**Comment by jefferai** [comment]
Thanks for the pointer! I'll take a look and get a fix into master.

**Comment by bbasata** [comment]
@jefferai In my case and @Friz-zy's case, we're using an IAM Role. From your comment, it sounds like you're using an IAM User. That distinction would explain why the nil EC2 Metadata service is not affecting you.

**Comment by jefferai** [comment]
Any chance one or more of you can check out the "issue-836" branch and ensure that it fixes the problem for you?

Thanks!

**Comment by bbasata** [comment]
@jefferai This works for me. `vault server` now starts without issue for me using an s3 backend and an IAM role. Thank you!

**Comment by jefferai** [comment]
Awesome!

**Comment by Friz-zy** [comment]
Thanks, guys!

**Comment by cludden** [comment]
I'm still seeing this issue with v0.4.1

```bash
[ec2-user@ip-XXX-XX-XX-XXX vault]$ vault -v
Vault v0.4.1
```

in `config.hcl`
```
backend "s3" {
    bucket = "######"
    region = "######"
}

listener "tcp" {
    address = "0.0.0.0:8080"
    tls_cert_file = "/home/ec2-user/.tls/server.crt"
    tls_key_file = "/home/ec2-user/.tls/server.key"
}

disable_mlock = true
```

log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb3a600]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x130f380, 0x19, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b0
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:129 +0x74
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc820194c90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:86 +0x7b
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc820194cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:67 +0xf2
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc8201b25f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:182 +0x111
github.com/aws/aws-sdk-go/private/signer/v4.(*signer).sign(0xc8201dec70, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:123 +0x3bf
github.com/aws/aws-sdk-go/private/signer/v4.Sign(0xc8201f4000)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:97 +0x1e7
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8201f4118, 0xc8201f4000)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc8201f4000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request.go:197 +0xce
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc8201f4000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request.go:207 +0x54
github.com/aws/aws-sdk-go/service/s3.(*S3).HeadBucket(0xc8200283c0, 0xc8200283c8, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/api.go:888 +0x4f
github.com/hashicorp/vault/physical.newS3Backend(0xc820194ab0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/s3.go:82 +0xc68
github.com/hashicorp/vault/physical.NewBackend(0xc82018fa70, 0x2, 0xc820194ab0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/physical.go:75 +0x1db
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc82014e0c0, 0xc82000a2c0, 0x1, 0x1, 0xc8201a1748)
	/gopath/src/github.com/hashicorp/vault/command/server.go:108 +0xdeb
github.com/mitchellh/cli.(*CLI).Run(0xc8201e0000, 0xc8201e0000, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/mitchellh/cli/cli.go:112 +0x698
github.com/hashicorp/vault/cli.RunCustom(0xc82000a2b0, 0x2, 0x2, 0xc820194000, 0x2)
	/gopath/src/github.com/hashicorp/vault/cli/main.go:44 +0x452
github.com/hashicorp/vault/cli.Run(0xc82000a2b0, 0x2, 0x2, 0x9c2d00)
	/gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x4c
main.main()
	/gopath/src/github.com/hashicorp/vault/main.go:10 +0x60

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable, locked to thread]:
runtime.gopark(0x1485d40, 0xc82001bd98, 0x1229610, 0x9, 0x16, 0x3)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.goparkunlock(0xc82001bd98, 0x1229610, 0x9, 0x16, 0x3)
	/usr/local/go/src/runtime/proc.go:191 +0x54
runtime.chansend(0xdd4e40, 0xc82001bd40, 0xc82002670c, 0xc820026601, 0x450c99, 0x2)
	/usr/local/go/src/runtime/chan.go:197 +0x499
runtime.chansend1(0xdd4e40, 0xc82001bd40, 0xc82002670c)
	/usr/local/go/src/runtime/chan.go:92 +0x43
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:238 +0x2a9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 8 [runnable]:
github.com/hashicorp/vault/cli.makeShutdownCh.func1(0xc82001bce0, 0xc82001bc80)
	/gopath/src/github.com/hashicorp/vault/cli/commands.go:294
created by github.com/hashicorp/vault/cli.makeShutdownCh
	/gopath/src/github.com/hashicorp/vault/cli/commands.go:299 +0x195

goroutine 9 [runnable]:
github.com/hashicorp/vault/command.(*Meta).FlagSet.func1(0xc82016cb80, 0xc82014e0e0)
	/gopath/src/github.com/hashicorp/vault/command/meta.go:186
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
	/gopath/src/github.com/hashicorp/vault/command/meta.go:190 +0x5e6
```

**Comment by Friz-zy** [comment]
Looks like it was fixed only in 5 version

**Comment by mconigliaro** [comment]
Same problem here. Anyone have a workaround for 0.4.1?

**Comment by jefferai** [comment]
@mconigliaro Can you explain what you mean by "doesn't say so on the official website"? It's the version on the downloads page, there's a blog post about it, and there was an email to the mailing list about it.

Not harping on you for missing it, but if you are still seeing 0.4.1 as the "current" version somewhere, I really want to get that fixed. I just don't know where else it would be since those are the three locations I know of where we talk about releases and I know all three of those are updated.

**Comment by mconigliaro** [comment]
Damn, looks like [the page](https://www.vaultproject.io/downloads.html) was cached. I see it now. Sorry for the false alarm.

**Comment by jefferai** [comment]
No problem! Cache happens.
