### ISSUE TITLE
"nil pointer dereference" when using disable_clustering

### ISSUE THREAD

**Issue by wneessen** [hashicorp/vault#8762]
**Describe the bug**
A "nil pointer dereference" occurs when a vault is set up with clustering enabled and later the clustering is disabled via "disable_clustering = 1"

**To Reproduce**
* Create a new Vault instance using the "raft" storage
* Define the key shares
* Shut down the instance
* Add "disabled_clustering = 1" to your config
* Start up Vault and unlock it via the UI
* Once unlocked, the vault will thow the "nil pointer dereference":
```
2020-04-17T16:23:05.267Z [INFO]  http2: panic serving 10.0.131.9:64831: runtime error: invalid memory address or nil pointer dereference
goroutine 68 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc00000e5e8, 0xc000287f8e, 0xc00011f980)
        /usr/lib/go/src/net/http/h2_bundle.go:5713 +0x16d
panic(0x77c668f52a0, 0x77c68932c40)
        /usr/lib/go/src/runtime/panic.go:967 +0x16a
github.com/hashicorp/vault/vault/cluster.(*Listener).TLSConfig(0x0, 0x77c66fa7d40, 0xc000118020, 0x0, 0x0, 0x0)
        /build/vault/src/src/github.com/hashicorp/vault/vault/cluster/cluster.go:222 +0x196
github.com/hashicorp/vault/physical/raft.(*RaftBackend).SetupCluster(0xc00046cdd0, 0x77c66fa7d40, 0xc000118020, 0xc0006465c0, 0x77c66fc5660, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/vault/src/src/github.com/hashicorp/vault/physical/raft/raft.go:445 +0x263
github.com/hashicorp/vault/vault.(*Core).startRaftStorage(0xc000156580, 0x77c66fa7d40, 0xc000118020, 0x0, 0x0)
        /build/vault/src/src/github.com/hashicorp/vault/vault/raft.go:125 +0x2b7
github.com/hashicorp/vault/vault.(*Core).unsealInternal(0xc000156580, 0x77c66fa7d40, 0xc000118020, 0xc0000a1f20, 0x20, 0x21, 0x0, 0x0, 0x0)
        /build/vault/src/src/github.com/hashicorp/vault/vault/core.go:1306 +0x168
github.com/hashicorp/vault/vault.(*Core).unseal(0xc000156580, 0xc0000a1e90, 0x21, 0x21, 0x0, 0x0, 0x0, 0x0)
        /build/vault/src/src/github.com/hashicorp/vault/vault/core.go:999 +0x5b1
github.com/hashicorp/vault/vault.(*Core).Unseal(...)
        /build/vault/src/src/github.com/hashicorp/vault/vault/core.go:909
github.com/hashicorp/vault/http.handleSysUnseal.func1(0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /build/vault/src/src/github.com/hashicorp/vault/http/sys_seal.go:145 +0x65a
net/http.HandlerFunc.ServeHTTP(0xc000327b50, 0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /usr/lib/go/src/net/http/server.go:2012 +0x46
net/http.(*ServeMux).ServeHTTP(0xc0007fef00, 0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /usr/lib/go/src/net/http/server.go:2387 +0x1a7
github.com/hashicorp/vault/http.wrapHelpHandler.func1(0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /build/vault/src/src/github.com/hashicorp/vault/http/help.go:24 +0x152
net/http.HandlerFunc.ServeHTTP(0xc00024c520, 0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /usr/lib/go/src/net/http/server.go:2012 +0x46
github.com/hashicorp/vault/http.wrapCORSHandler.func1(0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /build/vault/src/src/github.com/hashicorp/vault/http/cors.go:29 +0x93e
net/http.HandlerFunc.ServeHTTP(0xc00024c540, 0x77c66f95380, 0xc00000e5e8, 0xc000628700)
        /usr/lib/go/src/net/http/server.go:2012 +0x46
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x77c66f95380, 0xc00000e5e8, 0xc000628500)
        /build/vault/src/src/github.com/hashicorp/vault/http/handler.go:225 +0x33e
net/http.HandlerFunc.ServeHTTP(0xc000383c20, 0x77c66f95380, 0xc00000e5e8, 0xc000628500)
        /usr/lib/go/src/net/http/server.go:2012 +0x46
github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x77c66f95380, 0xc00000e5e8, 0xc000628500)
        /build/vault/src/pkg/mod/github.com/hashicorp/go-cleanhttp@v0.5.1/handlers.go:42 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc00024c560, 0x77c66f95380, 0xc00000e5e8, 0xc000628500)
        /usr/lib/go/src/net/http/server.go:2012 +0x46
net/http.serverHandler.ServeHTTP(0xc0002f07e0, 0x77c66f95380, 0xc00000e5e8, 0xc000628500)
        /usr/lib/go/src/net/http/server.go:2807 +0xa5
net/http.initALPNRequest.ServeHTTP(0x77c66fa7dc0, 0xc00025a2a0, 0xc0007fd180, 0xc0002f07e0, 0x77c66f95380, 0xc00000e5e8, 0xc000628500)
        /usr/lib/go/src/net/http/server.go:3381 +0x8f
net/http.(*http2serverConn).runHandler(0xc00011f980, 0xc00000e5e8, 0xc000628500, 0xc00000d7a0)
        /usr/lib/go/src/net/http/h2_bundle.go:5720 +0x8d
created by net/http.(*http2serverConn).processHeaders
        /usr/lib/go/src/net/http/h2_bundle.go:5454 +0x4e3
```

**Expected behavior**
No "nil pointer dereference" should be thrown but the exception should be handled

**Environment:**
* Vault Server Version: v1.3.4
* Vault CLI Version: v1.3.4
* Server Operating System/Architecture: Latest Arch Linux (using 5.6.3.a-1-hardened Kernel)

Vault server configuration file(s):

During setup:
```hcl
listener "tcp" {
  address          = "10.0.32.31:8200"
  cluster_address = "10.0.32.31:8201"
  tls_cert_file = "/etc/vault.d/vault1.cgn.domain.com.crt"
  tls_key_file = "/etc/vault.d/vault1.cgn.domain.com.key"
  tls_ca_file = "/etc/vault.d/cleverCA_ServerCA.cabundle"
}

listener "tcp" {
  address          = "127.0.0.1:8200"
cluster_address = "127.0.0.1:8201"
  tls_cert_file = "/etc/vault.d/vault1.cgn.domain.com.crt"
  tls_key_file = "/etc/vault.d/vault1.cgn.domain.com.key"
  tls_ca_file = "/etc/vault.d/cleverCA_ServerCA.cabundle"
}


storage "raft" {
path = "/var/lib/vault/vault_raft"
node_id = "cb_vault_1"
}

api_addr = "https://vault1.cgn.domain.com:8200"
cluster_addr  = "https://vault1.cgn.domain.com:8201"
ui = 1
```

After successful initialization:
```hcl
listener "tcp" {
  address          = "10.0.32.31:8200"
  cluster_address = "10.0.32.31:8201"
  tls_cert_file = "/etc/vault.d/vault1.cgn.domain.com.crt"
  tls_key_file = "/etc/vault.d/vault1.cgn.domain.com.key"
  tls_ca_file = "/etc/vault.d/cleverCA_ServerCA.cabundle"
}

listener "tcp" {
  address          = "127.0.0.1:8200"
cluster_address = "127.0.0.1:8201"
  tls_cert_file = "/etc/vault.d/vault1.cgn.domain.com.crt"
  tls_key_file = "/etc/vault.d/vault1.cgn.domain.com.key"
  tls_ca_file = "/etc/vault.d/cleverCA_ServerCA.cabundle"
}


storage "raft" {
path = "/var/lib/vault/vault_raft"
node_id = "cb_vault_1"
}
#storage "file" {
#path = "/var/lib/vault/vault_local"
#}

api_addr = "https://vault1.cgn.domain.com:8200"
cluster_addr  = "https://vault1.cgn.domain.com:8201"
disable_clustering = 1
#disable_mlock = 1
ui = 1
```

**Comment by briankassouf** [comment]
@wneessen Thanks for the report! This is specific to the integrated raft storage backend. We can definitely get it patched, but I'm curious what your use case for disabling clustering with raft storage is?

**Comment by wneessen** [comment]
@briankassouf No real usecase. I was actually troubleshooting a different issue (https://github.com/hashicorp/vault/issues/8760) in which I was trying different settings - turning out it was totally unrelated.
