### ISSUE TITLE
vault client crashes when reading empty secret string (vault read "")

### ISSUE THREAD

**Issue by feliksik** [hashicorp/vault#923]
If you do `vault read ""`, vault 0.4.0 crashes:

```
$ vault read ""
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/vault/command.(*ReadCommand).Run(0xc8201ea820, 0xc82000a1d0, 0x1, 0x1, 0xc82022c7e0)
	/gopath/src/github.com/hashicorp/vault/command/read.go:34 +0xe31
github.com/mitchellh/cli.(*CLI).Run(0xc820224370, 0xc820224370, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/mitchellh/cli/cli.go:112 +0x655
github.com/hashicorp/vault/cli.RunCustom(0xc82000a1c0, 0x2, 0x2, 0xc8201d8780, 0x2)
	/gopath/src/github.com/hashicorp/vault/cli/main.go:44 +0x452
github.com/hashicorp/vault/cli.Run(0xc82000a1c0, 0x2, 0x2, 0x9c1d00)
	/gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x4c
main.main()
	/gopath/src/github.com/hashicorp/vault/main.go:10 +0x60

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 17 [runnable]:
github.com/hashicorp/vault/command.(*Meta).FlagSet.func1(0xc8201e0280, 0xc8201ea820)
	/gopath/src/github.com/hashicorp/vault/command/meta.go:186
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
	/gopath/src/github.com/hashicorp/vault/command/meta.go:190 +0x5e6
```

**Comment by jefferai** [comment]
Fixed, thanks!

**Comment by ravichigurupalli** [comment]
how you fixed this

**Comment by ravichigurupalli** [comment]
i am facing same issue
