### ISSUE TITLE
panic when visiting /ui

### ISSUE THREAD

**Issue by greut** [hashicorp/vault#9335]
**Describe the bug**

vault panic when visiting `/ui`

**To Reproduce**
1. Run `vault server -dev`
2. Run `curl http://localhost:8200/ui`
3. See error

```
2020-06-29T14:08:24.261+0200 [INFO]  http: panic serving 127.0.0.1:53046: runtime error: slice bounds out of range [4:3]
goroutine 56 [running]:
net/http.(*conn).serve.func1(0xc000ad17c0)
        /usr/lib/go/src/net/http/server.go:1772 +0x139
panic(0x34edb20, 0xc000cd5920)
        /usr/lib/go/src/runtime/panic.go:975 +0x3e3
github.com/hashicorp/vault/http.buildLogicalRequestNoAuth(0xc0000c1800, 0x3f7dd80, 0xc000958380, 0xc0005caf00, 0x5e2a2d8, 0x5dcb800, 0x3f99bc0, 0xc00067a2a0, 0x42fcb9, 0x7f0e75925f98)
        /home/yoan/go/src/github.com/hashicorp/vault/http/logical.go:47 +0x14eb
github.com/hashicorp/vault/http.wrapGenericHandler.func1(0x3f7dd80, 0xc000958380, 0xc0005cad00)
        /home/yoan/go/src/github.com/hashicorp/vault/http/handler.go:307 +0x5d7
net/http.HandlerFunc.ServeHTTP(0xc000b58630, 0x3f7dd80, 0xc000958380, 0xc0005cad00)
        /usr/lib/go/src/net/http/server.go:2012 +0x44
github.com/hashicorp/go-cleanhttp.PrintablePathCheckHandler.func1(0x3f7dd80, 0xc000958380, 0xc0005cad00)
        /home/yoan/go/pkg/mod/github.com/hashicorp/go-cleanhttp@v0.5.1/handlers.go:42 +0xba
net/http.HandlerFunc.ServeHTTP(0xc000b781c0, 0x3f7dd80, 0xc000958380, 0xc0005cad00)
        /usr/lib/go/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc0009582a0, 0x3f7dd80, 0xc000958380, 0xc0005cad00)
        /usr/lib/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000ad17c0, 0x3f99b00, 0xc0006ad400)
        /usr/lib/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2933 +0x35c
```

**Expected behavior**

Using Vault 1.4.2

```
<a href="/ui/">Temporary Redirect</a>.
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 
* Vault CLI Version (retrieve with `vault version`): Vault v1.4.0 ('b3f0e9badfaac44ef4300acf13144abb2cec25d3+CHANGES')
* Server Operating System/Architecture: GNU/Linux

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

This was not spotted by myself, https://gitter.im/hashicorp-vault/Lobby?at=5ef8812054d7862dc4b33cae

**Comment by aphorise** [comment]
@greut I think this has since been resolved. Maybe you can confirm and close 👍
